# Generated by Django 6.1.2 on 2026-10-09 03:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_paper_is_sample'),
        ('learn', '0002_quizattempt_chosen'),
        ('shop', '0020_cart_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('school', 'school'), ('distributor', 'distributor')], max_length=11)),
                ('external_ref', models.CharField(help_text="The account's name in ERPNext.", max_length=140)),
                ('score', models.IntegerField()),
                ('bucket', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-computed_at', '-score'],
            },
        ),
        migrations.CreateModel(
            name='CodeActivationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=40)),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
                ('printed', models.PositiveIntegerField(help_text="On the batch's row only.", null=True)),
                ('redeemed', models.PositiveIntegerField()),
                ('redeemed_7d', models.PositiveIntegerField(verbose_name='redeemed in the last 7 days')),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-computed_at', 'batch', 'district'],
            },
        ),
        migrations.CreateModel(
            name='CohortStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_month', models.DateField(help_text='The first day of the month the course opened.')),
                ('source', models.CharField(choices=[('book_code', 'book code'), ('purchase', 'purchase'), ('grant', 'staff grant')], max_length=10)),
                ('week_index', models.PositiveSmallIntegerField(help_text='Weeks since the course opened (0: the first).')),
                ('n', models.PositiveIntegerField(help_text='Learners counted that week (their exam still ahead).')),
                ('active_share', models.FloatField(help_text='Empty below 5 learners.', null=True)),
                ('churned_share', models.FloatField(help_text='No activity for 14 days; empty below 5 or in week 0.', null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-computed_at', 'cohort_month', 'source', 'week_index'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(max_length=80)),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
                ('n', models.PositiveIntegerField()),
                ('median_days', models.FloatField()),
                ('p90_days', models.FloatField()),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-computed_at', 'courier', 'district'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('forecast', 'demand forecast'), ('backtest', 'backtest'), ('print_run', 'print-run advice')], max_length=10)),
                ('method', models.CharField(max_length=200)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('data_as_of', models.DateTimeField(help_text='When the job read the data.')),
                ('code_version', models.CharField(blank=True, help_text='RELEASE, as Sentry gets it.', max_length=60)),
                ('status', models.CharField(choices=[('running', 'running'), ('done', 'done'), ('skipped', 'nothing to work on'), ('failed', 'failed')], default='running', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FraudSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('codes_failed_account', 'failed book codes from one account in an hour'), ('codes_failed_ip', 'failed book codes from one IP address in an hour'), ('codes_failed_spike', 'failed book codes: an hour far above the usual'), ('codes_per_account', 'one account redeeming many codes'), ('accounts_per_code', 'one code tried by several accounts'), ('shared_phone', 'accounts sharing a phone number on COD or coupon orders'), ('shared_address', 'accounts sharing an address on COD or coupon orders')], max_length=25)),
                ('subject', models.CharField(help_text='A keyed hash, or “all”.', max_length=64)),
                ('count', models.PositiveIntegerField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('batch', models.CharField(blank=True, help_text='Empty: no such code.', max_length=40)),
                ('outcome', models.CharField(choices=[('redeemed', 'redeemed'), ('unknown', 'no such code'), ('used', 'used by another account')], max_length=10)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ChapterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_learners', models.PositiveIntegerField()),
                ('mean_accuracy', models.FloatField(help_text='Empty below 5 learners.', null=True)),
                ('trend', models.FloatField(help_text="The last 4 weeks' accuracy less the 4 weeks before.", null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learn.chapter')),
            ],
            options={
                'ordering': ['-computed_at', 'chapter'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
                ('week_start', models.DateField()),
                ('p10', models.FloatField()),
                ('p50', models.FloatField()),
                ('p90', models.FloatField()),
                ('n_history', models.PositiveIntegerField(help_text='Copies sold in the history it stands on.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.product')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='insights.forecastrun')),
            ],
            options={
                'ordering': ['-run', 'product', 'week_start', 'district'],
            },
        ),
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_weeks', models.PositiveSmallIntegerField()),
                ('wape', models.FloatField(help_text='Sum of absolute errors ÷ sum of copies sold.', null=True, verbose_name='WAPE')),
                ('mase_vs_seasonal_naive', models.FloatField(help_text="Mean absolute error ÷ the seasonal naive's on the same weeks: below 1 beats it.", null=True, verbose_name='MASE')),
                ('n_weeks', models.PositiveSmallIntegerField()),
                ('shown', models.BooleanField(default=False, help_text='It beats the seasonal naive, so the panel may show it.')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.product')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='insights.forecastrun')),
            ],
            options={
                'ordering': ['-run', 'product', 'horizon_weeks'],
            },
        ),
        migrations.CreateModel(
            name='PrintCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='print cost per copy (₹)')),
                ('salvage', models.DecimalField(decimal_places=2, default=0, help_text='What a copy left after the exams fetches (pulping, a later sale); 0 when the papers change yearly.', max_digits=8, verbose_name='salvage per copy (₹)')),
                ('on_order', models.PositiveIntegerField(default=0, help_text='Ordered, not yet in stock.', verbose_name='copies on order')),
                ('lead_time_weeks', models.PositiveSmallIntegerField(default=3, verbose_name='reprint lead time (weeks)')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(limit_choices_to={'kind__in': ['sample-papers', 'solutions']}, on_delete=django.db.models.deletion.CASCADE, related_name='print_cost', to='shop.product')),
            ],
            options={
                'verbose_name': 'print cost',
            },
        ),
        migrations.CreateModel(
            name='PrintRunAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='net price (₹)')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='print cost (₹)')),
                ('salvage', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='salvage (₹)')),
                ('critical_ratio', models.FloatField(help_text='(net price − cost) ÷ (net price − salvage): the quantile to print.')),
                ('target_quantity', models.PositiveIntegerField(help_text="The season's demand from now at the critical ratio.")),
                ('supply', models.PositiveIntegerField(help_text='Copies in stock and on order.')),
                ('recommended_quantity', models.PositiveIntegerField(help_text='Copies to print now: the target less the supply.')),
                ('reprint_trigger_units', models.PositiveIntegerField(help_text='Reprint once the supply is at or below this: the P90 of the demand over the reprint lead time.')),
                ('weeks_of_cover', models.FloatField(help_text='Empty: the supply outlasts the season.', null=True)),
                ('projected_leftover', models.PositiveIntegerField(help_text='Copies left at the exam if nothing more is printed.')),
                ('n_history', models.PositiveIntegerField(help_text='Copies sold in the history the forecast stands on.')),
                ('level', models.CharField(choices=[('ok', 'nothing to do'), ('watch', 'watch'), ('act', 'act now')], default='ok', max_length=5)),
                ('alert', models.CharField(blank=True, max_length=200)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.product')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice', to='insights.forecastrun')),
            ],
            options={
                'verbose_name_plural': 'print-run advice',
                'ordering': ['-run', 'product'],
            },
        ),
        migrations.CreateModel(
            name='ExamSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='2026-27', max_length=7)),
                ('exam_start', models.DateField(help_text='The first written paper (practicals before it do not count).')),
                ('exam_end', models.DateField(help_text='The last paper.')),
                ('notes', models.TextField(blank=True, help_text="Where the dates come from (the board's notice).")),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.board')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.classlevel')),
            ],
            options={
                'ordering': ['-exam_start'],
                'constraints': [models.UniqueConstraint(fields=('board', 'class_level', 'academic_year'), name='one_exam_season_a_year')],
            },
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveIntegerField(help_text='Learners who answered it (first attempts).')),
                ('p', models.FloatField(help_text='Share who got it right.', null=True)),
                ('discrimination', models.FloatField(help_text="Corrected item-total point-biserial against the chapter's other items.", null=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run_date', models.DateField(default=django.utils.timezone.localdate)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learn.quizitem')),
            ],
            options={
                'ordering': ['-run_date', 'item'],
                'constraints': [models.UniqueConstraint(fields=('item', 'run_date'), name='one_item_stat_a_day')],
            },
        ),
        migrations.CreateModel(
            name='OfferStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('orders', models.PositiveIntegerField(help_text='Orders that used it.')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='their revenue (₹)')),
                ('discount_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='discount given (₹)')),
                ('period_orders', models.PositiveIntegerField(help_text='Every order while it ran.')),
                ('baseline_orders', models.PositiveIntegerField(help_text='Every order in the same weeks last season.')),
                ('baseline_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interval_low', models.FloatField(help_text="95 % interval of orders while it ran ÷ the baseline's.", null=True)),
                ('interval_high', models.FloatField(null=True)),
                ('note', models.CharField(max_length=200)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.coupon')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.offer')),
            ],
            options={
                'ordering': ['-computed_at', 'period_start'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('coupon__isnull', False), ('offer__isnull', True)), models.Q(('coupon__isnull', True), ('offer__isnull', False)), _connector='OR'), name='offer_stat_of_a_coupon_or_an_offer')],
            },
        ),
    ]
