# Generated by Django 6.1.2 on 2026-10-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionattempt',
            name='device_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Empty: the app sent none.', max_length=64),
        ),
        migrations.AlterField(
            model_name='fraudsignal',
            name='kind',
            field=models.CharField(choices=[('codes_failed_account', 'failed book codes from one account in an hour'), ('codes_failed_ip', 'failed book codes from one IP address in an hour'), ('codes_failed_spike', 'failed book codes: an hour far above the usual'), ('codes_per_account', 'one account redeeming many codes'), ('accounts_per_code', 'one code tried by several accounts'), ('shared_phone', 'accounts sharing a phone number on COD or coupon orders'), ('shared_address', 'accounts sharing an address on COD or coupon orders'), ('codes_failed_device', 'failed book codes from one device in an hour'), ('codes_undispatched', 'codes redeemed from a batch not yet dispatched (a leak)')], max_length=25),
        ),
        migrations.AlterField(
            model_name='redemptionattempt',
            name='outcome',
            field=models.CharField(choices=[('redeemed', 'redeemed'), ('unknown', 'no such code'), ('used', 'used by another account'), ('void', 'a void code')], max_length=10),
        ),
    ]
