# Generated by Django 6.1.2 on 2026-10-09 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_phase_b_content'),
        ('insights', '0002_roles'),
        ('learn', '0002_quizattempt_chosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHealthStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('last7', 'the 7 days to yesterday'), ('last28', 'the 28 days to yesterday')], max_length=6)),
                ('period_start', models.DateField(help_text="The day, the week's Monday, the month's first day, or a window's first.")),
                ('active_learners', models.PositiveIntegerField(help_text='Learners with any activity in the period.')),
                ('clips_started', models.PositiveIntegerField()),
                ('clips_completed', models.PositiveIntegerField()),
                ('quiz_answers', models.PositiveIntegerField()),
                ('quiz_correct', models.PositiveIntegerField()),
                ('card_reviews', models.PositiveIntegerField()),
                ('card_lapses', models.PositiveIntegerField(help_text='Flash cards turned over that the learner did not know.')),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('computed_for', models.DateField(help_text="The day it counted up to: yesterday's complete periods end here.")),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learn.chapter')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.subject')),
            ],
            options={
                'ordering': ['grain', 'period_start'],
                'indexes': [models.Index(fields=['grain', 'subject', 'chapter', 'period_start'], name='course_health_read')],
            },
        ),
    ]
