# Generated by Django 6.1.2 on 2026-10-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_phase_b_course'),
        ('insights', '0003_phase_b_reports'),
    ]

    operations = [
    ]
