// Test data for the support module's unit tests (Vitest only): a ticket as GET support/tickets/{number}/ answers it,
// with the parts a test changes.
import type { TicketRecord } from "@/lib/api/staff";

export function ticketWith(extra: Partial<TicketRecord> = {}): TicketRecord {
  return {
    id: 4101,
    number: "SR-2026-000101",
    subject: "Where is my order?",
    source: "form",
    nch_docket: "",
    category: "order",
    priority: "medium",
    status: "open",
    language: "en",
    requester: { name: "Bikash Deka", email: "bi•••@example.com", phone: "••••••1873", user: 7102 },
    assignee: null,
    order: null,
    received_at: "2026-10-09T04:30:00Z",
    acknowledged_at: "2026-10-09T04:31:00Z",
    first_response_at: null,
    resolved_at: null,
    closed_at: null,
    ack_due_at: "2026-10-11T04:30:00Z",
    due_at: "2026-11-09T04:30:00Z",
    next_due_at: "2026-11-09T04:30:00Z",
    ack_breached: false,
    due_breached: false,
    overdue: false,
    clock: "due",
    is_test: false,
    reopened_count: 0,
    message_count: 1,
    last_message_at: "2026-10-09T04:30:00Z",
    data_request: null,
    record: null,
    resolution: "",
    complaint_copy_sent_at: null,
    ack_held: false,
    redress_due_at: "2026-11-09T04:30:00Z",
    nch_due_at: null,
    dpdp_due_at: null,
    it_due_at: null,
    clocks: [],
    closing_fields: ["category", "resolution", "order"],
    transitions: ["waiting_customer", "waiting_third_party", "resolved", "closed", "spam"],
    messages: [],
    sidebar: { account: null, orders: [], entitlements: null, codes: null, devices: null, tickets: [], consents: null },
    saved_replies: [
      { id: 61, title: "Refund timeline", language: "en", text: "Dear Bikash, the refund is on its way." },
      { id: 62, title: "Parcel on its way", language: "en", text: "Dear Bikash, your parcel is with the courier." },
      { id: 63, title: "অনুৰোধ পোৱা গৈছে", language: "as", text: "নমস্কাৰ Bikash" },
    ],
    ...extra,
  };
}
