// Every word the panel shows, in one place (the copied design-system kit in src/components/ui/ keeps its own few words,
// identical to the public site's, so that a shared package later is a move). English now; Assamese and Bengali follow
// as objects of the same shape (`as`, `bn`), chosen by the person's language, with no i18n library: a function where
// a sentence takes a number or a name, a string everywhere else. The API's own words (its `detail`) are shown as they
// come: the backend decides, the panel draws.

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const plural = (count: number, one: string, many: string) =>
  `${count.toLocaleString("en-IN")} ${count === 1 ? one : many}`;

export const en = {
  lang: "en",
  app: {
    name: "ExamLeaf Admin",
    short: "Admin",
    titleTemplate: "%s · ExamLeaf Admin",
    description: "The staff console of ExamLeaf.",
    skip: "Skip to the content",
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    retry: "Try again",
    reload: "Reload",
    copy: "Copy",
    copied: "Copied",
    open: "Open",
    remove: "Remove",
    confirm: "Confirm",
    continue: "Continue",
    yes: "Yes",
    no: "No",
    none: "None",
    unknown: "Not known",
    never: "Never",
    optional: "optional",
    reason: "Reason",
    reasonHelp: "Saved in the audit trail with your name.",
    reasonRequired: "Give a reason: it is saved in the audit trail.",
    details: "Details",
    actions: "Actions",
    loading: "Loading…",
    working: "Working…",
    done: "Done",
    me: "Me",
    anyone: "Anyone",
    all: "All",
    on: "On",
    off: "Off",
    from: "From",
    to: "To",
    search: "Search",
    clear: "Clear",
    apply: "Apply",
    opensElsewhere: "(opens in a new tab)",
    recorded: "Recorded in the audit trail.",
    signOut: "Sign out",
  },
  time: {
    months: MONTHS,
    justNow: "just now",
    minutesAgo: (minutes: number) => `${plural(minutes, "minute", "minutes")} ago`,
    hoursAgo: (hours: number) => `${plural(hours, "hour", "hours")} ago`,
    daysAgo: (days: number) => `${plural(days, "day", "days")} ago`,
    duration: (days: number, hours: number, minutes: number) =>
      days > 0 ? `${days} d ${hours} h` : hours > 0 ? `${hours} h ${minutes} min` : `${minutes} min`,
    left: (duration: string) => `${duration} left`,
    overdue: (duration: string) => `overdue by ${duration}`,
    at: (date: string, time: string) => `${date}, ${time}`,
    until: (when: string) => `until ${when}`,
  },
  errors: {
    unavailable: "The ExamLeaf server cannot be reached just now. Check your connection, then try again.",
    unconfirmed: "The server didn't answer in time, so this may have gone through. Check before you try again.",
    signedOut: "Your session has ended. Sign in again; what you typed is kept on this device.",
    forbidden: "You don't have access to this.",
    permissionDenied: "Your role does not allow this.",
    scopeDenied: "This is outside the part of the records you look after.",
    reauthRequired: "Confirm it's you to do this.",
    reauthCancelled: "Nothing was changed: this needs you to confirm it's you first.",
    approvalRequired: "This needs a second person's approval.",
    mfaSetup: "Staff accounts need two-step sign-in first.",
    notFound: "We could not find that.",
    conflict: "Someone else changed this while you were editing.",
    conflictHint: "Reload to see their change; what you typed is kept.",
    throttled: "Too many requests. Wait a little, then try again.",
    throttledUntil: (time: string) => `Too many requests. You can try again after ${time}.`,
    server: "Something went wrong on our side. Please try again.",
    badRequest: "Check what you entered.",
    badResponse: "The server's answer was not what this page expects. Nothing was changed by this page.",
    problem: "There is a problem",
    timedOut: "The form timed out. Reload the page and send it again.",
    reference: (digest: string) => `Reference: ${digest}`,
    unavailableTitle: "The server can't be reached right now",
    unavailableText: "Nothing is wrong with the records. Please try again in a minute.",
    pageFailedTitle: "Something went wrong on our side",
    pageFailedText: "This page could not be shown. Please try again in a minute.",
    notFoundTitle: "This page isn't in the console",
    notFoundText: "The address may be mistyped, or the record was removed.",
    goHome: "Go to Home",
  },
  auth: {
    signInTitle: "Sign in to ExamLeaf Admin",
    signInLead: "For ExamLeaf staff. Every sign-in is recorded.",
    email: "Email address",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    show: "Show",
    hide: "Hide",
    signIn: "Sign in",
    google: "Continue with Google",
    or: "or",
    unavailableTitle: "Sign-in is not available just now",
    unavailableText: "The ExamLeaf server cannot be reached. Please try again in a minute.",
    twoStepTitle: "Two-step check",
    twoStepLead: "Open your authenticator app and enter the 6-digit code for ExamLeaf.",
    recoveryLead: "Type one of your recovery codes.",
    recoveryCode: "Recovery code",
    useRecovery: "Use a recovery code",
    useApp: "Use the app's code",
    usePasskey: "Use a passkey or security key",
    nothingDueTitle: "No second step is waiting",
    nothingDueText: "The step may have timed out, or it was done already. Sign in again to start over.",
    startAgain: "Start again",
    tooManyTitle: "Too many tries",
    tooMany: (time: string) => `To keep accounts safe, sign-in tries are limited. You can try again after ${time}.`,
    next: (path: string) => `After signing in you'll go back to ${path}`,
    nextLabel: "NEXT",
    idleNotice: "You were signed out after a time without activity. Sign in to go back; what you typed is kept.",
    expiredNotice: "Your session ended. Sign in to go back; what you typed is kept on this device.",
    signedOutNotice: "You are signed out.",
    googleCancelled: "You didn't finish signing in with Google. Nothing was changed.",
    googleFailed: "Google couldn't sign you in. Please try once more.",
    inactiveTitle: "This account is switched off",
    inactiveText:
      "A switched-off account cannot sign in to the console. If you think this is a mistake, ask the owner or an admin.",
    noAccessTitle: "This account has no access to the console",
    noAccessText:
      "You are signed in, but the console is for ExamLeaf staff. Sign out, then sign in with your staff account.",
    setupTitle: "Set up two-step sign-in first",
    setupText:
      "Staff accounts need an authenticator app or a passkey before the console opens. Set one up on your ExamLeaf account page, then come back and sign in again.",
    setupLink: "Set it up on the website",
    setupThen: "Once it is set up, sign out here and sign in again.",
    confirmTitle: "Confirm it's you",
    confirmLead: "For your safety, this action needs a fresh check.",
    confirmCode: "Enter the 6-digit code from your authenticator app.",
    confirmPassword: "Type your password instead",
    confirmUseCode: "Use the authenticator code instead",
    confirmPasskey: "Use a passkey instead",
    confirm: "Confirm",
  },
  idle: {
    warnTitle: "You'll be signed out soon",
    warnText: (time: string) =>
      `For safety, the console signs you out after a time without activity. That happens at ${time}.`,
    endTitle: "Your session ends soon",
    endText: (time: string) => `Sessions last a fixed time. This one ends at ${time}; sign in again then.`,
    stay: "Stay signed in",
    signOutNow: "Sign out now",
    keep: "What you typed in a form is kept on this device.",
  },
  shell: {
    menu: "Menu",
    closeMenu: "Close",
    modules: "Modules",
    search: "Search or jump to…",
    inbox: "Inbox",
    /** After the inbox's count, for screen readers: "Inbox 6 open". */
    inboxOpen: "open",
    /** After the person's name on their menu's button: "Anita Baruah, your account". */
    yourAccount: ", your account",
    account: "My account and sessions",
    shortcuts: "Keyboard shortcuts",
    shortcutsSwitch: "Single-key shortcuts",
    signOutEverywhere: "Sign out everywhere",
    roles: "Roles",
    erp: "In ERPNext",
    erpOpens: "opens ERPNext",
    soon: "soon",
    test: "Test",
    testLabel: "Test environment",
    testText: "Not the live site: what you see and do here is test data.",
    impersonating: (email: string, until: string) =>
      `You are signed in to the website as ${email} until ${until}. Every action is recorded.`,
    endImpersonation: "End",
    impersonationEnded: "Ended",
    shortcutsTitle: "Keyboard shortcuts",
    shortcutsList: [
      ["⌘ K or Ctrl K", "Search or jump to a page"],
      ["/", "Search the list"],
      ["j / k", "Next or previous row"],
      ["Enter", "Open the row"],
      ["x", "Select the row"],
      ["?", "This list"],
      ["Esc", "Close a dialog"],
    ] as [string, string][],
    shortcutsNote: "Single-key shortcuts can be switched off in your account menu.",
  },
  palette: {
    title: "Search or jump to",
    label: "Search the console",
    placeholder: "A page, a customer, a staff member…",
    pages: "Pages",
    recent: "Recent",
    actions: "Actions",
    customers: "Customers",
    people: "Staff",
    nothing: "Nothing matches.",
    searching: "Searching…",
    failed: "Search could not reach the server.",
    hint: "Type at least two letters to search customers and staff.",
    inviteAction: "Invite a staff member",
    incidentAction: "Record an incident",
    requestAction: "Log a data request",
    signOutAction: "Sign out",
    shortcutsAction: "Show keyboard shortcuts",
  },
  nav: {
    groups: {
      work: "Work",
      shop: "Shop",
      learning: "Content and course",
      customers: "Customers and partners",
      privacy: "Legal and privacy",
      staff: "Staff",
      system: "System",
      erp: "In ERPNext",
    },
    modules: {
      home: "Home",
      inbox: "Inbox",
      approvals: "Approvals",
      audit: "Audit trail",
      orders: "Orders",
      catalogue: "Catalogue",
      marketing: "Marketing",
      content: "Content",
      course: "Course",
      users: "Customers",
      partners: "Partners",
      support: "Support",
      requests: "Data requests",
      incidents: "Incidents",
      processors: "Processors",
      people: "People",
      accessReview: "Access review",
      apiKeys: "API keys",
      settings: "Settings",
      system: "System",
      account: "My account",
      finance: "Finance",
      tax: "Tax",
      inventory: "Inventory",
      purchases: "Purchases",
      crm: "CRM",
    },
  },
  table: {
    select: (label: string) => `Select ${label}`,
    selectPage: "Select every row on this page",
    selected: (count: number) => `${count.toLocaleString("en-IN")} selected`,
    clearSelection: "Clear selection",
    bulkLimit: (limit: number) =>
      `More than ${limit.toLocaleString("en-IN")} rows at once needs a second person's approval.`,
    columns: "Columns",
    columnsLegend: "Columns to show",
    sortedAscending: "sorted, first to last",
    sortedDescending: "sorted, last to first",
    sortBy: (label: string) => `Sort by ${label}`,
    previous: "Previous page",
    next: "Next page",
    pages: "Pages of the list",
    density: "Rows",
    exportLabel: "Export",
    exportHelp: (limit: number) =>
      `Exports what the filters show, up to ${limit.toLocaleString("en-IN")} rows; the file waits in your inbox.`,
    exportReady: "Download the file",
    emptyTitle: "Nothing here yet",
    emptyText: "When there is something, it shows here.",
    noMatchTitle: "The filters match nothing",
    noMatchText: "Change or clear the filters to see more.",
    clearFilters: "Clear the filters",
    region: (label: string) => `${label}, a table`,
  },
  filters: {
    label: "Filters",
    search: "Search",
    searchList: (what: string) => `Search ${what}`,
    any: "Any",
    from: "From",
    to: "To",
    apply: "Apply",
    clear: "Clear the filters",
  },
  views: {
    label: "Saved views",
    standard: "Everything",
    save: "Save as a view",
    saveText: "Its filters, columns and sort are kept under a name, as a tab above the list.",
    update: "Update this view",
    remove: "Delete this view",
    name: "Name of the view",
    share: "Share with",
    onlyMe: "Only me",
    role: (role: string) => `Everyone with the ${role} role`,
    saved: "View saved",
    updated: "View updated",
    removed: "View deleted",
    removeTitle: (name: string) => `Delete the view "${name}"?`,
    removeText: "The filters and columns it keeps are deleted for everyone it is shared with.",
    changed: "The filters or columns differ from this view.",
    shared: "shared",
  },
  bulk: {
    started: "Started",
    progress: (done: number, total: number) =>
      `${done.toLocaleString("en-IN")} of ${total.toLocaleString("en-IN")} done`,
    finished: (done: number, failed: number) =>
      failed ? `Done: ${done.toLocaleString("en-IN")}, ${plural(failed, "row", "rows")} failed` : "All done",
    failedTitle: "These rows failed",
    jobFailed: "The job stopped before it finished.",
    queued: "Waiting to start…",
    progressName: "Progress of the job",
  },
  masked: {
    reveal: "Reveal",
    revealWhat: (what: string) => `Reveal the ${what}`,
    revealTitle: (what: string) => `Reveal the ${what}?`,
    revealText: "Revealing personal data is recorded with your reason. It is shown for 60 seconds, then hidden again.",
    revealButton: "Reveal it",
    hiddenIn: (seconds: number) => `Hidden again in ${seconds} s`,
    hide: "Hide now",
    email: "email address",
    phone: "mobile number",
    none: "None on record",
  },
  confirmTyped: {
    instruction: (label: string) => `To confirm, type ${label} below.`,
    field: "Type to confirm",
    mismatch: "What you typed does not match.",
  },
  approval: {
    title: "A second person needs to approve this",
    text: "Nothing has changed yet. A change request was made; an approver has been asked, and you'll see the outcome in your inbox.",
    open: "Open the change request",
    number: (id: string) => `Change request ${id}`,
  },
  home: {
    title: "Home",
    lead: "What waits for you today.",
    inbox: "Your inbox",
    inboxEmpty: "Nothing waits for you.",
    openInbox: "Open the inbox",
    approvals: "Approvals",
    approvalsForYou: (count: number) => `${plural(count, "request", "requests")} waiting for a decision`,
    approvalsYours: (count: number) => `${plural(count, "request", "requests")} of yours waiting for someone else`,
    approvalsEmpty: "No change request is waiting.",
    openApprovals: "Open approvals",
    clocks: "Clocks",
    clocksLead: "Data requests and incidents, nearest to due first.",
    clocksEmpty: "No clock is running.",
    health: "System health",
    healthOk: "Every check passes.",
    healthFailing: (count: number) => `${plural(count, "check", "checks")} failing`,
    openSystem: "Open System",
    quickLinks: "Your modules",
    more: (count: number) => `more than ${count.toLocaleString("en-IN")}`,
  },
  inbox: {
    title: "Inbox",
    lead: "Things that wait for a person: approvals, requests, reports and jobs.",
    states: { open: "Open", snoozed: "Snoozed", done: "Done" } as Record<string, string>,
    stateLabel: "Show",
    kind: "Kind",
    assignee: "Assigned to",
    columns: { title: "What", kind: "Kind", due: "Due", assignee: "Assigned to", created: "Arrived" },
    done: "Mark done",
    snooze: "Snooze",
    snoozeUntil: "Snooze until",
    assignToMe: "Assign to me",
    markedDone: "Marked done",
    snoozed: "Snoozed",
    assigned: "Assigned",
    unassigned: "No one",
    snoozedUntil: (when: string) => `snoozed until ${when}`,
    emptyTitle: "Nothing waits",
    emptyText: "When something needs you, it arrives here.",
    kinds: {
      approval: "Approval",
      change_request: "Approval",
      data_request: "Data request",
      incident: "Incident",
      export: "Export",
      job: "Job",
      report: "Report",
      sync: "Sync",
      ticket: "Ticket",
    } as Record<string, string>,
  },
  audit: {
    title: "Audit trail",
    lead: "Every staff action and every look at personal data, newest first. It cannot be edited.",
    filters: {
      q: "Search",
      actor: "Who (email)",
      action: "Action",
      targetType: "Record type",
      targetId: "Record id",
    },
    columns: { ts: "When", actor: "Who", action: "Action", target: "Record", outcome: "Outcome", reason: "Reason" },
    eventTitle: "Audit event",
    onBehalfOf: "On behalf of",
    requestId: "Request id",
    ip: "Address",
    hash: "Chain hash",
    changes: "What changed",
    field: "Field",
    before: "Before",
    after: "After",
    noChanges: "No field changed.",
    outcomes: { success: "Done", denied: "Refused", failure: "Failed", error: "Failed" } as Record<string, string>,
    actorTypes: { staff: "staff", system: "the system", integration: "an API key", customer: "a customer" } as Record<
      string,
      string
    >,
    export: "Export",
    exportTitle: "Export the audit trail",
    exportText: "The export runs in the background; the file waits in your inbox when it is ready.",
    exportStart: "Start the export",
    emptyTitle: "No event matches",
    emptyText: "Change the filters, or widen the dates.",
  },
  approvals: {
    title: "Approvals",
    lead: "Changes that need a second person. The approver sees and approves the exact request that will run.",
    states: {
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      expired: "Expired",
      executed: "Done",
      failed: "Failed",
    } as Record<string, string>,
    columns: {
      action: "Change",
      target: "Record",
      amount: "Amount",
      maker: "Asked by",
      expires: "Expires",
      state: "State",
    },
    maker: "Asked by",
    reason: "Their reason",
    amount: "Amount",
    target: "Record",
    expires: "Expires",
    created: "Asked",
    payload: "The exact request that will run",
    payloadHelp: "This is what runs when the request is approved and carried out, byte for byte.",
    payloadJson: "The request, as JSON",
    resultJson: "The result, as JSON",
    sha: "Its SHA-256",
    decisions: "Decisions",
    noDecisions: "No one has decided yet.",
    decision: { approve: "approved", reject: "rejected" } as Record<string, string>,
    comment: "Comment",
    commentHelp: "Saved with your decision.",
    approve: "Approve",
    reject: "Reject",
    execute: "Carry it out",
    approved: "Approved",
    rejected: "Rejected",
    executed: "Carried out",
    ownRequest: "You asked for this change, so someone else must approve it.",
    result: "Result",
    emptyTitle: "No change request here",
    emptyText: "When a change needs a second person, it waits here.",
  },
  people: {
    title: "People",
    lead: "Staff, their roles and scopes, and how they sign in.",
    columns: {
      name: "Name",
      roles: "Roles",
      mfa: "Two-step",
      lastLogin: "Last sign-in",
      sessions: "Sessions",
      status: "Status",
    },
    statuses: {
      active: "Active",
      invited: "Invited",
      suspended: "Suspended",
      offboarded: "Offboarded",
      inactive: "Switched off",
    } as Record<string, string>,
    mfaOn: "On",
    mfaOff: "Not set up",
    invite: "Invite a staff member",
    inviteTitle: "Invite a staff member",
    inviteText: "They get an email with a link that works once, for 72 hours. Privileged roles need an approval.",
    inviteEmail: "Their work email address",
    inviteRole: "Role",
    inviteSend: "Send the invitation",
    invited: "Invitation sent",
    roles: "Roles",
    grant: "Grant a role",
    grantButton: "Grant the role",
    role: "Role",
    expires: "Expires",
    expiresHelp: "Leave empty for a role that stays until it is revoked.",
    grantedBy: (who: string) => `granted by ${who}`,
    noExpiry: "no end date",
    revoke: "Revoke",
    revokeRole: (role: string) => `Revoke ${role}`,
    revokeTitle: (role: string) => `Revoke the ${role} role?`,
    revokeText: "It ends at once: the next request they make no longer has it.",
    granted: "Role granted",
    revoked: "Role revoked",
    noRoles: "No role.",
    scopes: "Scopes",
    scopesLead: "A scope narrows what a role reaches: a subject, a board and class, a warehouse or a queue.",
    noScopes: "No scope: their roles reach every record.",
    scopeKind: "Kind",
    scopeValue: "Value",
    addScope: "Add a scope",
    addScopeButton: "Add the scope",
    scopeAdded: "Scope added",
    scopeRemoved: "Scope removed",
    removeScope: (scope: string) => `Remove the scope ${scope}`,
    scopeKinds: {
      subject: "Subject",
      board_class: "Board and class",
      order_status: "Order status",
      warehouse: "Warehouse",
      school: "School",
      ticket_queue: "Ticket queue",
    } as Record<string, string>,
    sessions: "Sessions",
    sessionsCount: (count: number) => `Signed in on ${plural(count, "device", "devices")}.`,
    endSessions: "End all their sessions",
    endSessionsTitle: "End all their sessions?",
    endSessionsText: "Every browser and app they are signed in on is signed out at once.",
    sessionsEnded: "Sessions ended",
    offboard: "Offboard",
    offboardTitle: "Offboard this person",
    offboardText:
      "Switches the account off, ends every session, revokes their roles, scopes and API keys, and hands their open work to an admin. It cannot be undone from here.",
    offboardButton: "Offboard them",
    offboarded: "Offboarded",
    accessReview: "Access review",
    accessReviewLead:
      "Everyone's roles, scopes, last sign-in and the permissions they have not used. Change what should change from the person's page.",
    reviewColumns: {
      person: "Person",
      roles: "Roles",
      scopes: "Scopes",
      lastLogin: "Last sign-in",
      unused: "Unused permissions",
      flags: "Flags",
    },
    dormant: "Dormant",
    generated: (when: string) => `Made ${when}`,
    emptyTitle: "No staff member matches",
    emptyText: "Change the search, or invite someone.",
    roleNames: {
      OWNER: "Owner",
      ADMIN: "Admin",
      FINANCE: "Finance",
      SALES: "Sales",
      PACKER: "Packer",
      SUPPORT: "Support",
      CONTENT_EDITOR: "Content editor",
      REVIEWER: "Reviewer",
      MARKETING: "Marketing",
      AUDITOR: "Auditor",
    } as Record<string, string>,
  },
  users: {
    title: "Customers",
    lead: "Students, parents and teachers. Contact details stay masked unless you reveal them with a reason.",
    columns: {
      name: "Name",
      email: "Email",
      phone: "Mobile",
      kind: "Kind",
      status: "Status",
      joined: "Joined",
      lastSeen: "Last seen",
    },
    kinds: { student: "Student", parent: "Parent", teacher: "Teacher" } as Record<string, string>,
    statuses: {
      active: "Active",
      suspended: "Suspended",
      inactive: "Switched off",
      pending_deletion: "Deletion due",
      erased: "Erased",
    } as Record<string, string>,
    flags: {
      child: "Under 18",
      consent_pending: "Consent pending",
      locked: "Locked",
      suspended: "Suspended",
    } as Record<string, string>,
    recordLogged: "Opening this record is recorded in the audit trail.",
    childLogged: "This is a child's account: opening it is recorded as a look at a child's data.",
    contact: "Contact",
    email: "Email address",
    phone: "Mobile number",
    details: "Details",
    joined: "Joined",
    lastSeen: "Last seen",
    verified: "Verified",
    notVerified: "Not verified",
    mfa: "Two-step sign-in",
    consent: "Parent's consent",
    consentStates: {
      none: "None",
      declared: "Declared",
      pending: "Waiting for the parent",
      verified: "Verified",
      withdrawn: "Withdrawn",
      expired: "Expired",
    } as Record<string, string>,
    sessions: "Signed-in devices",
    actions: "Actions",
    actionsLead: "Each one is recorded with your name; the customer is told where the law or our policy asks.",
    action: {
      resendVerification: "Send the email confirmation again",
      passwordReset: "Send a password reset link",
      unlock: "Unlock sign-in",
      endSessions: "Sign them out everywhere",
      suspend: "Suspend the account",
      unsuspend: "Lift the suspension",
      resetMfa: "Reset two-step sign-in",
      impersonate: "Sign in as this customer",
    },
    done: {
      resendVerification: "Email sent",
      passwordReset: "Link sent",
      unlock: "Unlocked",
      endSessions: "Signed out",
      suspend: "Suspended",
      unsuspend: "Suspension lifted",
    },
    suspendTitle: "Suspend this account?",
    suspendText: "They are signed out at once and cannot sign in until the suspension is lifted.",
    resetMfaTitle: "Reset their two-step sign-in?",
    resetMfaText:
      "They will sign in with their password alone until they set it up again. Prove who they are first, as strongly as when they set it up. A second person approves it.",
    impersonateTitle: "Sign in to the website as this customer",
    impersonateText:
      "You see the website as they do for 15 minutes. Payments, passwords, email, consent and deletion stay closed, and they can see that you did it.",
    impersonateReasonHelp: "A ticket number and why: saved with every page you open as them.",
    impersonateButton: "Start",
    impersonateOpen: "Open the website as them",
    impersonateUntil: (time: string) => `Open until ${time}.`,
    danger: "Danger zone",
    emptyTitle: "No customer matches",
    emptyText: "Search by name, email or the last digits of a mobile number.",
  },
  privacy: {
    requestsTitle: "Data requests",
    requestsLead:
      "Requests to see, correct or erase personal data, nominations and grievances, with the clocks the law sets.",
    incidentsTitle: "Incidents",
    incidentsLead: "The breach register. CERT-In within 6 hours, the Data Protection Board within 72 hours.",
    processorsTitle: "Processors",
    processorsLead: "Who processes personal data for ExamLeaf, for what, and where.",
    types: {
      access: "Access",
      correction: "Correction",
      erasure: "Erasure",
      nomination: "Nomination",
      grievance: "Grievance",
      complaint: "Complaint",
    } as Record<string, string>,
    states: {
      received: "Received",
      acknowledged: "Acknowledged",
      in_progress: "In progress",
      responded: "Responded",
      closed: "Closed",
      rejected: "Rejected",
      open: "Open",
      contained: "Contained",
    } as Record<string, string>,
    columns: {
      type: "Type",
      requester: "Requester",
      channel: "Channel",
      received: "Received",
      ack: "Acknowledge",
      due: "Respond",
      state: "State",
    },
    ackClock: "Acknowledge within 48 hours",
    dueClock: "Respond by",
    acknowledged: (when: string) => `acknowledged ${when}`,
    responded: "responded",
    verifiedRequester: "Identity checked",
    unverifiedRequester: "Identity not checked yet",
    acknowledge: "Acknowledge",
    acknowledgedToast: "Acknowledged",
    notes: "Notes",
    notesHelp: "Notes are personal data too: they go into the requester's own access export.",
    saveNotes: "Save the notes",
    notesSaved: "Notes saved",
    actions: "What was done",
    noActions: "Nothing yet.",
    dryRun: "Erasure: dry run",
    dryRunLead: "Shows what would be erased and what the law makes us keep, without erasing anything.",
    dryRunButton: "Run the dry run",
    held: "Kept, and why",
    willErase: "Would be erased",
    heldUntil: (until: string) => `until ${until}`,
    nothingHeld: "Nothing is held back.",
    nothingErased: "Nothing would be erased.",
    template: "Response",
    templateLead: "A draft to adapt before sending. Have counsel review the wording before first use.",
    templateText: (type: string, received: string) =>
      `Thank you for your ${type.toLowerCase()} request, which we received on ${received}. We are working on it and will reply within the time the law allows. If you have questions, reply to this message.`,
    copyTemplate: "Copy the draft",
    logRequest: "Log a request",
    logTitle: "Log a data request",
    logText: "For a request that came by email, phone or letter. The clocks start from when it was received.",
    channel: "How it came",
    channels: {
      email: "Email",
      phone: "Phone",
      letter: "Letter",
      web: "The website",
      in_person: "In person",
    } as Record<string, string>,
    requesterEmail: "Requester's email address",
    requesterPhone: "Requester's mobile number",
    receivedAt: "Received at",
    logButton: "Log it",
    logged: "Logged",
    incidentNew: "Record an incident",
    incidentTitle: "Record an incident",
    incidentText:
      "Record it as soon as it is noticed: the 6-hour and 72-hour clocks run from when it was detected. Partial facts are fine at first.",
    detectedAt: "Detected at",
    incidentType: "Type",
    systems: "Systems involved",
    systemsHelp: "Comma separated, for example: website, database",
    dataCategories: "Kinds of personal data",
    dataCategoriesHelp: "Comma separated, for example: email, name, marks",
    peopleAffected: "People affected (an estimate)",
    childrenAffected: "Children's data involved",
    recordIncident: "Record it",
    incidentRecorded: "Recorded",
    incidentColumns: {
      detected: "Detected",
      type: "Type",
      systems: "Systems",
      people: "People",
      certin: "CERT-In (6 h)",
      board: "Board (72 h)",
      state: "State",
    },
    certinClock: "Tell CERT-In",
    boardClock: "Tell the Board",
    reported: (when: string) => `told ${when}`,
    markCertin: "CERT-In was told at",
    markBoard: "The Board was told at",
    noticesSent: "Notices sent to people",
    incidentActions: "Actions taken",
    incidentState: "State",
    saveIncident: "Save the incident",
    incidentSaved: "Saved",
    incidentTypes: {
      data_breach: "Data breach",
      data_leak: "Data leak",
      unauthorised_access: "Unauthorised access",
      malicious_code: "Malicious code",
      ransomware: "Ransomware",
      outage: "Outage blocking access",
      other: "Other",
    } as Record<string, string>,
    children: "Children affected",
    processorNew: "Add a processor",
    processorTitle: "Add a processor",
    processorName: "Name",
    processorPurpose: "What they do for us",
    processorCountry: "Country or region where the data is kept",
    processorCategories: "Kinds of personal data",
    processorContract: "Contract or data processing agreement until",
    processorAdd: "Add it",
    processorAdded: "Added",
    processorColumns: {
      name: "Name",
      purpose: "Purpose",
      country: "Where",
      categories: "Data",
      contract: "Agreement until",
    },
    emptyRequestsTitle: "No data request",
    emptyRequestsText: "When someone asks about their data, the request and its clocks show here.",
    emptyIncidentsTitle: "No incident recorded",
    emptyIncidentsText: "Record one as soon as something is noticed: the clocks start at detection.",
    emptyProcessorsTitle: "No processor listed",
    emptyProcessorsText: "List everyone who processes personal data for ExamLeaf.",
  },
  settings: {
    title: "Settings",
    lead: "The site's settings and feature flags: where each value comes from, its history, and who changed it.",
    site: "Site settings",
    flags: "Feature flags",
    columns: { key: "Setting", value: "Value", source: "Source", effective: "From", changedBy: "Changed by" },
    sources: { env: "Environment", db: "Console" } as Record<string, string>,
    envNote: "Set in the server's environment: change it there and restart.",
    change: "Change",
    changeTitle: (key: string) => `Change ${key}`,
    value: "New value",
    effectiveFrom: "Takes effect from",
    effectiveHelp: "Leave empty for at once.",
    saveChange: "Save the change",
    changed: "Saved",
    history: "History",
    noHistory: "No earlier value.",
    historyEntry: (who: string, when: string) => `${who}, ${when}`,
    emptyTitle: "No setting to show",
    emptyText: "Settings appear here once the server lists them.",
    trueValue: "On",
    falseValue: "Off",
    emptyValue: "(empty)",
  },
  apiKeys: {
    title: "API keys",
    lead: "Keys for integrations, one per integration, each with its scopes, an end date and a person who answers for it.",
    columns: {
      name: "Name",
      prefix: "Starts with",
      scopes: "Scopes",
      created: "Made",
      expires: "Ends",
      lastUsed: "Last used",
      sponsor: "Answers for it",
      status: "Status",
    },
    statuses: { active: "Active", revoked: "Revoked", expired: "Ended" } as Record<string, string>,
    create: "Make a key",
    createTitle: "Make an API key",
    createText: "The secret is shown once, when it is made. Store it in the integration's settings straight away.",
    name: "Name",
    nameHelp: "What it is for, for example: Shiprocket sync",
    scopes: "Scopes",
    scopesHelp: "Comma separated, as the integration's documentation lists them",
    expires: "Ends on",
    expiresHelp: "At most 12 months from today.",
    createButton: "Make the key",
    secretTitle: "Copy the secret now",
    secretText: "It is never shown again. If it is lost, revoke the key and make a new one.",
    secretStored: "I have stored it",
    revoke: "Revoke",
    revokeTitle: (name: string) => `Revoke ${name}?`,
    revokeText: "Every request with this key is refused from now on. It cannot be undone.",
    revoked: "Revoked",
    emptyTitle: "No API key yet",
    emptyText: "Make one for each integration that needs to call ExamLeaf.",
  },
  system: {
    title: "System",
    lead: "Health checks, queues, webhooks, email and SMS, backups and maintenance mode.",
    health: "Health",
    healthy: "Passing",
    failing: "Failing",
    queues: "Queues",
    queue: "Queue",
    waiting: "Waiting",
    failedTasks: (count: number) => `${plural(count, "failed task", "failed tasks")}`,
    webhooks: "Recent webhooks",
    webhookColumns: { provider: "From", event: "Event", at: "Received", status: "Status" },
    noWebhooks: "No webhook received lately.",
    email: "Email",
    sms: "SMS",
    sent: "Sent",
    bounced: "Bounced",
    suppressed: "Suppressed",
    backups: "Backups",
    lastBackup: "Last backup",
    backupSize: "Size",
    noBackup: "No backup has run.",
    maintenance: "Maintenance mode",
    maintenanceOn: "On: visitors see the banner and changes are closed. The console stays open.",
    maintenanceOff: "Off: the site is open.",
    banner: "Banner shown to visitors",
    turnOn: "Turn maintenance mode on",
    turnOff: "Turn maintenance mode off",
    maintenanceSaved: "Saved",
    emptyTitle: "Nothing to show",
  },
  account: {
    title: "My account",
    lead: "Where you are signed in, and how to leave.",
    you: "You",
    roles: "Your roles",
    roleUntil: (when: string) => `until ${when}`,
    sessions: "Signed-in devices",
    sessionsLead: "Every browser and app signed in to your account, on the website and here.",
    thisDevice: "this device",
    since: (when: string) => `since ${when}`,
    lastSeen: (when: string) => `last seen ${when}`,
    now: "now",
    signOutDevice: "Sign out",
    signOutDeviceName: (name: string) => `Sign out ${name}`,
    signedOutDevice: "Signed out",
    signOutEverywhere: "Sign out everywhere",
    signOutEverywhereText: "Ends every session of your account, this one too.",
    sessionsFailed: "The list of devices could not be read.",
    addressUnknown: "address unknown",
    aBrowser: "A browser",
    on: (browser: string, system: string) => `${browser} on ${system}`,
    security: "Two-step sign-in and passkeys",
    securityText: "Change them on your ExamLeaf account page.",
    securityLink: "Open the account page",
  },
  soon: {
    title: (module: string) => `${module} comes in the next phase`,
    text: "This module is planned and not built yet. Until it is, the Django admin does this work.",
    /** Where a module's work is done today when the Django admin does not do it. */
    today: {
      support:
        "This module is planned and not built yet. Until it is, the contact form's messages arrive by email at the support address; the Django admin has the orders and accounts they are about.",
    } as Record<string, string>,
    admin: "Open the Django admin",
    eyebrow: "Coming next",
  },
  problem: {
    noAccessTitle: "No access",
    unavailableTitle: "Not available just now",
    badResponseTitle: "Could not be read",
    throttledTitle: "Too many requests",
    failedTitle: "Something went wrong",
  },
  states: {
    active: "Active",
    inactive: "Inactive",
    yes: "Yes",
    no: "No",
  },
};

export type Copy = typeof en;

/** The console's words. One language for now; the person's language picks the object once the others exist. */
export const copy: Copy = en;

/** A code the API sends that no table here names ("sync_failure"): its words, as a fallback ("Sync failure"). */
export function humanize(code: string): string {
  const words = code.replace(/[_-]+/g, " ").trim();
  return words ? words[0].toUpperCase() + words.slice(1).toLowerCase() : code;
}

/** The label of a known code, else its humanized words. */
export function labelOf(table: Record<string, string>, code: string | null | undefined): string {
  if (!code) return copy.common.unknown;
  return table[code] ?? humanize(code);
}
