// Every word the panel shows, in one place (the copied design-system kit in src/components/ui/ keeps its own few words,
// identical to the public site's, so that a shared package later is a move). English now; Assamese and Bengali follow
// as objects of the same shape (`as`, `bn`), chosen by the person's language, with no i18n library: a function where
// a sentence takes a number or a name, a string everywhere else. The API's own words (its `detail`) are shown as they
// come: the backend decides, the panel draws.

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const plural = (count: number, one: string, many: string) =>
  `${count.toLocaleString("en-IN")} ${count === 1 ? one : many}`;

export const en = {
  lang: "en",
  app: {
    name: "ExamLeaf Admin",
    short: "Admin",
    titleTemplate: "%s · ExamLeaf Admin",
    description: "The staff console of ExamLeaf.",
    skip: "Skip to the content",
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    retry: "Try again",
    reload: "Reload",
    copy: "Copy",
    copied: "Copied",
    open: "Open",
    remove: "Remove",
    confirm: "Confirm",
    continue: "Continue",
    yes: "Yes",
    no: "No",
    none: "None",
    unknown: "Not known",
    never: "Never",
    optional: "optional",
    reason: "Reason",
    reasonHelp: "Saved in the audit trail with your name.",
    reasonRequired: "Give a reason: it is saved in the audit trail.",
    details: "Details",
    actions: "Actions",
    loading: "Loading…",
    working: "Working…",
    done: "Done",
    me: "Me",
    anyone: "Anyone",
    all: "All",
    on: "On",
    off: "Off",
    from: "From",
    to: "To",
    search: "Search",
    clear: "Clear",
    apply: "Apply",
    opensElsewhere: "(opens in a new tab)",
    recorded: "Recorded in the audit trail.",
    signOut: "Sign out",
  },
  time: {
    months: MONTHS,
    justNow: "just now",
    minutesAgo: (minutes: number) => `${plural(minutes, "minute", "minutes")} ago`,
    hoursAgo: (hours: number) => `${plural(hours, "hour", "hours")} ago`,
    daysAgo: (days: number) => `${plural(days, "day", "days")} ago`,
    duration: (days: number, hours: number, minutes: number) =>
      days > 0 ? `${days} d ${hours} h` : hours > 0 ? `${hours} h ${minutes} min` : `${minutes} min`,
    left: (duration: string) => `${duration} left`,
    overdue: (duration: string) => `overdue by ${duration}`,
    at: (date: string, time: string) => `${date}, ${time}`,
    until: (when: string) => `until ${when}`,
  },
  errors: {
    unavailable: "The ExamLeaf server cannot be reached just now. Check your connection, then try again.",
    unconfirmed: "The server didn't answer in time, so this may have gone through. Check before you try again.",
    signedOut: "Your session has ended. Sign in again; what you typed is kept on this device.",
    forbidden: "You don't have access to this.",
    permissionDenied: "Your role does not allow this.",
    impersonatingTitle: "Not while you are signed in as a customer",
    impersonating:
      "While this session is signed in to the website as a customer, payments, passwords, email, two-step sign-in, consent, addresses and deletion stay closed. End the impersonation first.",
    linkExpired: "The file's link has expired. Download it again for a fresh one.",
    reauthRequired: "Confirm it's you to do this.",
    reauthCancelled: "Nothing was changed: this needs you to confirm it's you first.",
    approvalRequired: "This needs a second person's approval.",
    mfaSetup: "Staff accounts need two-step sign-in first.",
    notFound: "Not found, or outside the records you look after.",
    conflict: "Someone else changed this while you were editing.",
    conflictHint: "Reload to see their change; what you typed is kept.",
    throttled: "Too many requests. Wait a little, then try again.",
    throttledUntil: (time: string) => `Too many requests. You can try again after ${time}.`,
    server: "Something went wrong on our side. Please try again.",
    badRequest: "Check what you entered.",
    badResponse: "The server's answer was not what this page expects. Nothing was changed by this page.",
    problem: "There is a problem",
    timedOut: "The form timed out. Reload the page and send it again.",
    reference: (digest: string) => `Reference: ${digest}`,
    unavailableTitle: "The server can't be reached right now",
    unavailableText: "Nothing is wrong with the records. Please try again in a minute.",
    pageFailedTitle: "Something went wrong on our side",
    pageFailedText: "This page could not be shown. Please try again in a minute.",
    notFoundTitle: "Not found, or not yours to see",
    notFoundText:
      "The address may be mistyped or the record removed, or it is outside the records you look after: the console does not say which.",
    goHome: "Go to Home",
  },
  auth: {
    signInTitle: "Sign in to ExamLeaf Admin",
    signInLead: "For ExamLeaf staff. Every sign-in is recorded.",
    email: "Email address",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    show: "Show",
    hide: "Hide",
    signIn: "Sign in",
    google: "Continue with Google",
    or: "or",
    unavailableTitle: "Sign-in is not available just now",
    unavailableText: "The ExamLeaf server cannot be reached. Please try again in a minute.",
    twoStepTitle: "Two-step check",
    twoStepLead: "Open your authenticator app and enter the 6-digit code for ExamLeaf.",
    recoveryLead: "Type one of your recovery codes.",
    recoveryCode: "Recovery code",
    useRecovery: "Use a recovery code",
    useApp: "Use the app's code",
    usePasskey: "Use a passkey or security key",
    nothingDueTitle: "No second step is waiting",
    nothingDueText: "The step may have timed out, or it was done already. Sign in again to start over.",
    startAgain: "Start again",
    tooManyTitle: "Too many tries",
    tooMany: (time: string) => `To keep accounts safe, sign-in tries are limited. You can try again after ${time}.`,
    next: (path: string) => `After signing in you'll go back to ${path}`,
    nextLabel: "NEXT",
    idleNotice: "You were signed out after a time without activity. Sign in to go back; what you typed is kept.",
    expiredNotice: "Your session ended. Sign in to go back; what you typed is kept on this device.",
    signedOutNotice: "You are signed out.",
    googleCancelled: "You didn't finish signing in with Google. Nothing was changed.",
    googleFailed: "Google couldn't sign you in. Please try once more.",
    // the backend's refusals of a staff Google sign-in (accounts/adapter.py refuse_google), as ?error=
    googleRefused: {
      staff_google_domain: "Sign in with your work Google account: the ExamLeaf Workspace address.",
      staff_google_no_account: "No staff account has this Google address. Ask the owner or an admin to invite you.",
      staff_google_not_staff: "This account is not a member of staff, so it cannot sign in to the console.",
      staff_google_break_glass:
        "A break-glass account signs in with its password and its own second factor, not Google.",
    } as Record<string, string>,
    inactiveTitle: "This account is switched off",
    inactiveText:
      "A switched-off account cannot sign in to the console. If you think this is a mistake, ask the owner or an admin.",
    noAccessTitle: "This account has no access to the console",
    noAccessText:
      "You are signed in, but the console is for ExamLeaf staff. Sign out, then sign in with your staff account.",
    setupTitle: "Set up two-step sign-in first",
    setupText:
      "Staff accounts need an authenticator app or a passkey before the console opens. Set one up on your ExamLeaf account page, then come back and sign in again.",
    setupLink: "Set it up on the website",
    setupThen: "Once it is set up, sign out here and sign in again.",
    confirmTitle: "Confirm it's you",
    confirmLead: "For your safety, this action needs a fresh check.",
    confirmCode: "Enter the 6-digit code from your authenticator app.",
    confirmPassword: "Type your password instead",
    confirmUseCode: "Use the authenticator code instead",
    confirmPasskey: "Use a passkey instead",
    confirm: "Confirm",
  },
  idle: {
    warnTitle: "You'll be signed out soon",
    warnText: (time: string) =>
      `For safety, the console signs you out after a time without activity. That happens at ${time}.`,
    endTitle: "Your session ends soon",
    endText: (time: string) => `Sessions last a fixed time. This one ends at ${time}; sign in again then.`,
    stay: "Stay signed in",
    signOutNow: "Sign out now",
    keep: "What you typed in a form is kept on this device.",
  },
  shell: {
    menu: "Menu",
    closeMenu: "Close",
    modules: "Modules",
    search: "Search or jump to…",
    inbox: "Inbox",
    /** After the inbox's count, for screen readers: "Inbox 6 open". */
    inboxOpen: "open",
    /** After the person's name on their menu's button: "Anita Baruah, your account". */
    yourAccount: ", your account",
    account: "My account and sessions",
    shortcuts: "Keyboard shortcuts",
    shortcutsSwitch: "Single-key shortcuts",
    signOutEverywhere: "Sign out everywhere",
    signOutEverywhereFailed:
      "Your other sessions could not be ended, so you are still signed in here. Try again in a minute.",
    roles: "Roles",
    erp: "In ERPNext",
    erpOpens: "opens ERPNext",
    soon: "soon",
    test: "Test",
    testLabel: "Test environment",
    testText: "Not the live site: what you see and do here is test data.",
    impersonating: (email: string, until: string) =>
      `You are signed in to the website as ${email} until ${until}. Every action is recorded.`,
    endImpersonation: "End",
    impersonationEnded: "Ended",
    impersonationElsewhere: "It ends by itself then, or from the website's own banner.",
    breakGlassLabel: "Break-glass session",
    breakGlass:
      "A break-glass account: every check passes and nothing is limited. Every action is marked, the owners are told, and each is reviewed within 24 hours.",
    breakGlassReason: (reason: string) => `Reason given: ${reason}`,
    reasonTitle: "Why is a break-glass account needed?",
    reasonText:
      "Before anything else, say what happened that no other account could handle. The reason is kept in the audit log and sent to the owners.",
    reasonButton: "Give the reason",
    reasonGiven: "Reason recorded",
    policiesTitle: "Read and acknowledge",
    policiesText: "Before you go on, read these policies in their current version. Your acknowledgement is recorded.",
    // STAFF_POLICIES' keys (acceptable_use …) as words: "Acceptable use"
    policyName: (key: string) => key.charAt(0).toUpperCase() + key.slice(1).replaceAll("_", " "),
    policyVersion: (version: string) => `version ${version}`,
    policiesAcknowledge: "I have read them and will follow them",
    policiesDone: "Acknowledged",
    shortcutsTitle: "Keyboard shortcuts",
    shortcutsList: [
      ["⌘ K or Ctrl K", "Search or jump to a page"],
      ["/", "Search the list"],
      ["j / k", "Next or previous row"],
      ["Enter", "Open the row"],
      ["x", "Select the row"],
      ["?", "This list"],
      ["Esc", "Close a dialog"],
    ] as [string, string][],
    shortcutsNote: "Single-key shortcuts can be switched off in your account menu.",
  },
  palette: {
    title: "Search or jump to",
    label: "Search the console",
    placeholder: "A page, a customer, a staff member…",
    pages: "Pages",
    recent: "Recent",
    actions: "Actions",
    customers: "Customers",
    people: "Staff",
    nothing: "Nothing matches.",
    searching: "Searching…",
    failed: "Search could not reach the server.",
    hint: "Type at least two letters to search customers and staff.",
    inviteAction: "Invite a staff member",
    incidentAction: "Record an incident",
    requestAction: "Log a data request",
    signOutAction: "Sign out",
    shortcutsAction: "Show keyboard shortcuts",
  },
  nav: {
    groups: {
      work: "Work",
      shop: "Shop",
      learning: "Content and course",
      customers: "Customers and partners",
      privacy: "Legal and privacy",
      reports: "Reports",
      staff: "Staff",
      system: "System",
      erp: "In ERPNext",
    },
    modules: {
      home: "Home",
      inbox: "Inbox",
      approvals: "Approvals",
      audit: "Audit trail",
      orders: "Orders",
      shipping: "Shipping",
      catalogue: "Catalogue",
      marketing: "Marketing",
      content: "Content",
      course: "Course",
      users: "Customers",
      partners: "Partners",
      support: "Support",
      requests: "Data requests",
      incidents: "Incidents",
      processors: "Processors",
      insights: "Forecasts and signals",
      people: "People",
      accessReview: "Access review",
      apiKeys: "API keys",
      settings: "Settings",
      system: "System",
      account: "My account",
      finance: "Finance",
      tax: "Tax",
      inventory: "Inventory",
      purchases: "Purchases",
      crm: "CRM",
    },
  },
  table: {
    columns: "Columns",
    columnsLegend: "Columns to show",
    previous: "Previous page",
    next: "Next page",
    pages: "Pages of the list",
    density: "Rows",
    emptyTitle: "Nothing here yet",
    emptyText: "When there is something, it shows here.",
    noMatchTitle: "The filters match nothing",
    noMatchText: "Change or clear the filters to see more.",
    clearFilters: "Clear the filters",
    region: (label: string) => `${label}, a table`,
  },
  filters: {
    label: "Filters",
    search: "Search",
    searchList: (what: string) => `Search ${what}`,
    any: "Any",
    from: "From",
    to: "To",
    apply: "Apply",
    clear: "Clear the filters",
  },
  views: {
    label: "Saved views",
    standard: "Everything",
    save: "Save as a view",
    saveText: "Its filters, columns and sort are kept under a name, as a tab above the list.",
    update: "Update this view",
    remove: "Delete this view",
    name: "Name of the view",
    share: "Share with",
    onlyMe: "Only me",
    role: (role: string) => `Everyone with the ${role} role`,
    saved: "View saved",
    updated: "View updated",
    removed: "View deleted",
    removeTitle: (name: string) => `Delete the view "${name}"?`,
    removeText: "The filters and columns it keeps are deleted for everyone it is shared with.",
    changed: "The filters or columns differ from this view.",
    shared: "shared",
  },
  jobs: {
    title: "Your background jobs",
    lead: "Exports and bulk actions you started, newest first. A file waits a week; its link is made fresh each time.",
    none: "You have started no background job.",
    kinds: {
      audit_export: "Audit trail export",
      bulk_action: "Bulk action",
      erp_initial_load: "ERPNext initial load",
    } as Record<string, string>,
    states: {
      queued: "Waiting",
      running: "Running",
      done: "Done",
      failed: "Failed",
      cancelled: "Cancelled",
    } as Record<string, string>,
    started: "Started",
    progress: (done: number, total: number) =>
      `${done.toLocaleString("en-IN")} of ${total.toLocaleString("en-IN")} done`,
    finished: (done: number, failed: number) =>
      failed ? `Done: ${done.toLocaleString("en-IN")}, ${plural(failed, "row", "rows")} failed` : "All done",
    failedTitle: "These rows failed",
    jobFailed: "The job stopped before it finished.",
    jobCancelled: "Cancelled: it stopped where it was.",
    queued: "Waiting to start…",
    awaiting: (id: string) => `Waiting for a second person to approve it: change request ${id}.`,
    progressName: "Progress of the job",
    cancel: "Cancel the job",
    cancelled: "Cancelled",
    download: "Download the file",
    gone: "Its file is no longer kept.",
    columns: { job: "Job", state: "State", progress: "Rows", started: "Started" },
  },
  masked: {
    reveal: "Reveal",
    revealWhat: (what: string) => `Reveal the ${what}`,
    revealTitle: (what: string) => `Reveal the ${what}?`,
    revealText: "Revealing personal data is recorded with your reason. It is shown for 60 seconds, then hidden again.",
    revealButton: "Reveal it",
    hiddenIn: (seconds: number) => `Hidden again in ${seconds} s`,
    hide: "Hide now",
    email: "email address",
    phone: "mobile number",
    none: "None on record",
  },
  confirmTyped: {
    instruction: (label: string) => `To confirm, type ${label} below.`,
    field: "Type to confirm",
    mismatch: "What you typed does not match.",
  },
  approval: {
    title: "A second person needs to approve this",
    text: "Nothing has changed yet. A change request was made; an approver has been asked, and you'll see the outcome in your inbox.",
    status: (status: string) => `Its state: ${status}.`,
    checker: "Who may approve it: someone who holds",
    open: "Open the change request",
    number: (id: string) => `Change request ${id}`,
  },
  home: {
    title: "Home",
    lead: "What waits for you today.",
    inbox: "Your inbox",
    inboxEmpty: "Nothing waits for you.",
    inboxCount: (open: number, overdue: number) =>
      overdue
        ? `${plural(open, "item", "items")} open, ${overdue.toLocaleString("en-IN")} overdue`
        : `${plural(open, "item", "items")} open`,
    openInbox: "Open the inbox",
    approvals: "Approvals",
    approvalsForYou: (count: number) => `${plural(count, "request", "requests")} waiting for a decision`,
    approvalsYours: (count: number) => `${plural(count, "request", "requests")} of yours waiting for someone else`,
    approvalsEmpty: "No change request is waiting.",
    openApprovals: "Open approvals",
    clocks: "Clocks",
    clocksLead: "Data requests and incidents, nearest to due first.",
    clocksEmpty: "No clock is running.",
    health: "System health",
    healthOk: "Every check passes.",
    healthFailing: (count: number) => `${plural(count, "check", "checks")} failing`,
    openSystem: "Open System",
    quickLinks: "Your modules",
    more: (count: number) => `more than ${count.toLocaleString("en-IN")}`,
  },
  inbox: {
    title: "Inbox",
    lead: "What waits: items given to you, and those given to nobody that your permissions let you act on.",
    states: { open: "Open", snoozed: "Open and snoozed", done: "Done" } as Record<string, string>,
    stateLabel: "Show",
    kind: "Kind",
    assignee: "Assigned to",
    mine: "Only mine",
    columns: { title: "What", kind: "Kind", due: "Due", assignee: "Assigned to", created: "Arrived" },
    done: "Mark done",
    snooze: "Snooze",
    snoozeUntil: "Snooze until",
    assignToMe: "Assign to me",
    markedDone: "Marked done",
    snoozed: "Snoozed",
    assigned: "Assigned",
    unassigned: "No one",
    you: "You",
    staffMember: (id: number) => `Staff #${id}`,
    overdue: "overdue",
    snoozedUntil: (when: string) => `snoozed until ${when}`,
    emptyTitle: "Nothing waits",
    emptyText: "When something needs you, it arrives here.",
    kinds: {
      approval: "Approval",
      teacher_request: "Teacher access",
      deletion_request: "Account deletion",
      data_request: "Data request",
      incident: "Incident",
      failed_job: "Failed job",
      failed_webhook: "Failed webhook",
      sync_failed: "ERPNext refused a document",
      reconciliation: "ERPNext differences",
    } as Record<string, string>,
  },
  audit: {
    title: "Audit trail",
    lead: "Every staff action and every look at personal data, newest first. It cannot be edited.",
    filters: {
      actionPrefix: "Action starts with",
      actor: "Who (staff id)",
      targetType: "Record type",
      targetId: "Record id",
      outcome: "Outcome",
      changeRequest: "Change request",
      breakGlass: "Break-glass only",
    },
    columns: { ts: "When", actor: "Who", action: "Action", target: "Record", outcome: "Outcome", reason: "Reason" },
    eventTitle: "Audit event",
    onBehalfOf: "On behalf of",
    permission: "Permission used",
    changeRequest: "Change request",
    requestId: "Request id",
    ip: "Address",
    chain: "Chain",
    hash: "Chain hash",
    breakGlass: "Break-glass",
    changes: "What changed",
    details: "Details",
    field: "Field",
    before: "Before",
    after: "After",
    noChanges: "No field changed.",
    outcomes: { success: "Done", denied: "Refused", failed: "Failed" } as Record<string, string>,
    actorTypes: {
      staff: "Staff",
      user: "A customer",
      service: "An API key",
      system: "The system",
      anonymous: "Someone signed out",
    } as Record<string, string>,
    actor: (type: string, id: number | null | undefined) => (id ? `${type} #${id}` : type),
    export: "Export",
    exportTitle: "Export the audit trail",
    exportText:
      "Exports the events the filters show, with their hashes, as JSON lines: at once up to 5,000 rows within your limit, else as a background job (a larger one waits for an admin's approval).",
    exportStart: "Export what the filters show",
    exported: "Downloaded",
    emptyTitle: "No event matches",
    emptyText: "Change the filters, or widen the dates.",
  },
  approvals: {
    title: "Approvals",
    lead: "Changes that need a second person. The approver sees and approves the exact request that will run.",
    states: {
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      expired: "Expired",
      executed: "Done",
      failed: "Failed",
    } as Record<string, string>,
    columns: {
      action: "Change",
      target: "Record",
      amount: "Amount",
      maker: "Asked by",
      expires: "Expires",
      state: "State",
    },
    awaiting: "Waiting for me",
    mine: "Asked by me",
    maker: "Asked by",
    reason: "Their reason",
    rule: "Why it waits",
    checker: "Who may approve",
    amount: "Amount",
    target: "Record",
    expires: "Expires",
    created: "Asked",
    ask: "Ask for a refund",
    askLead:
      "A refund of an order paid online. Within your limit it runs at once; above it, a change request waits for finance.",
    askOrder: "Order number",
    askAmount: "Amount in rupees",
    askAmountHelp: "Leave empty for the whole amount paid. An order not shipped yet is cancelled and refunded in full.",
    askButton: "Ask for the refund",
    asked: "Refund started",
    payload: "The exact request that will run",
    payloadHelp: "This is what runs when the request is approved and carried out, byte for byte.",
    payloadJson: "The request, as JSON",
    resultJson: "The result, as JSON",
    sha: "Its SHA-256",
    decisions: "Decisions",
    noDecisions: "No one has decided yet.",
    decision: { approve: "approved", reject: "rejected" } as Record<string, string>,
    comment: "Comment",
    commentHelp: "Saved with your decision.",
    approve: "Approve",
    reject: "Reject",
    execute: "Carry it out",
    approved: "Approved",
    rejected: "Rejected",
    executed: "Carried out",
    ownRequest: "You asked for this change, so someone else must approve it.",
    notYours: (checker: string) => `It waits for someone who holds ${checker}.`,
    withdraw: "Withdraw it",
    withdrawn: "Withdrawn",
    result: "Result",
    emptyTitle: "No change request here",
    emptyText: "When a change needs a second person, it waits here.",
  },
  people: {
    title: "People",
    lead: "Staff, their roles and scopes, and how they sign in.",
    columns: {
      name: "Name",
      roles: "Roles",
      mfa: "Two-step",
      lastLogin: "Last sign-in",
      status: "Status",
    },
    statuses: {
      active: "Active",
      inactive: "Switched off",
      breakGlass: "Break-glass",
    } as Record<string, string>,
    mfaOn: "On",
    mfaOff: "Not set up",
    invite: "Invite a staff member",
    inviteTitle: "Invite a staff member",
    inviteText: "They get an email with a link that works once, for 72 hours. Privileged roles need an approval.",
    inviteEmail: "Their work email address",
    inviteRole: "Role",
    inviteSend: "Send the invitation",
    invited: "Invitation sent",
    invites: "Invitations",
    invitesLead: "Waiting, accepted and revoked invitations; the address is masked.",
    noInvites: "No invitation.",
    inviteStates: { waiting: "Waiting", accepted: "Accepted", revoked: "Revoked", expired: "Expired" } as Record<
      string,
      string
    >,
    inviteColumns: { email: "Address", role: "Role", sent: "Sent", expires: "Expires", state: "State" },
    revokeInvite: "Revoke",
    revokeInviteTitle: "Revoke this invitation?",
    revokeInviteText: "Its link stops working at once.",
    inviteRevoked: "Invitation revoked",
    roles: "Roles",
    grant: "Grant a role",
    grantButton: "Grant the role",
    role: "Role",
    expires: "Expires",
    expiresHelp: "Leave empty for a role that stays until it is revoked.",
    grantedBy: (who: string) => `granted by ${who}`,
    noExpiry: "no end date",
    revoke: "Revoke",
    revokeRole: (role: string) => `Revoke ${role}`,
    revokeTitle: (role: string) => `Revoke the ${role} role?`,
    revokeText: "It ends at once: the next request they make no longer has it.",
    granted: "Role granted",
    revoked: "Role revoked",
    noRoles: "No role.",
    scopes: "Scopes",
    scopesLead: "A scope narrows what a role reaches: a subject, a board and class, a warehouse or a queue.",
    noScopes: "No scope: their roles reach every record.",
    scopeKind: "Kind",
    scopeValue: "Value",
    addScope: "Add a scope",
    addScopeButton: "Add the scope",
    scopeAdded: "Scope added",
    scopeRemoved: "Scope removed",
    removeScope: (scope: string) => `Remove the scope ${scope}`,
    scopeKinds: {
      subject: "Subject",
      board_class: "Board and class",
      order_status: "Order status",
      warehouse: "Warehouse",
      school: "School",
      ticket_queue: "Ticket queue",
    } as Record<string, string>,
    sessions: "Sign-in",
    endSessions: "End all their sessions",
    endSessionsTitle: "End all their sessions?",
    endSessionsText: "Every browser and app they are signed in on is signed out at once.",
    sessionsEnded: (sessions: number) => `${plural(sessions, "session", "sessions")} ended`,
    resetMfa: "Reset their two-step sign-in",
    resetMfaText: "For a lost phone or key. An admin or another owner approves it first.",
    offboard: "Offboard",
    offboardTitle: "Offboard this person",
    offboardText:
      "Switches the account off, ends every session, revokes their roles, scopes and API keys, expires their requests and unassigns their work, in one step. It cannot be undone from here.",
    offboardButton: "Offboard them",
    offboarded: "Offboarded",
    accessReview: "Access review",
    accessReviewLead:
      "Everyone's roles, scopes, last sign-in and the action permissions they have not used in 90 days. Change what should change from the person's page.",
    reviewColumns: {
      person: "Person",
      roles: "Roles",
      scopes: "Scopes",
      lastLogin: "Last sign-in",
      unused: "Unused permissions",
      flags: "Flags",
    },
    dormant: "Dormant",
    noMfa: "No two-step",
    emptyTitle: "No staff member",
    emptyText: "Invite someone to start.",
    roleNames: {
      OWNER: "Owner",
      ADMIN: "Admin",
      FINANCE: "Finance",
      SALES: "Sales",
      SALES_REP: "Sales representative",
      PACKER: "Packer",
      SUPPORT: "Support",
      CONTENT_EDITOR: "Content editor",
      REVIEWER: "Reviewer",
      MARKETING: "Marketing",
      AUDITOR: "Auditor",
    } as Record<string, string>,
  },
  users: {
    title: "Customers",
    lead: "Students, parents and teachers. Contact details stay masked unless you reveal them with a reason.",
    columns: {
      name: "Name",
      email: "Email",
      phone: "Mobile",
      class: "Class",
      status: "Status",
      joined: "Joined",
      lastSeen: "Last sign-in",
    },
    classLevel: { "10": "Class 10", "12": "Class 12" } as Record<string, string>,
    board: "Board",
    district: "District",
    activeFilter: "Account",
    activeOptions: { true: "Switched on", false: "Suspended or erased" } as Record<string, string>,
    statuses: {
      active: "Active",
      suspended: "Suspended",
      pending_deletion: "Deletion due",
      erased: "Erased",
    } as Record<string, string>,
    flags: {
      child: "Under 18",
      consent_pending: "Consent pending",
      locked: "Locked",
    } as Record<string, string>,
    recordLogged: "Opening this record is recorded in the audit trail.",
    childLogged: "This is a child's account: opening it is recorded as a look at a child's data.",
    contact: "Contact",
    email: "Email address",
    phone: "Mobile number",
    details: "Details",
    joined: "Joined",
    lastSeen: "Last seen",
    verified: "Verified",
    notVerified: "Not verified",
    mfa: "Two-step sign-in",
    mfaNone: "Not set up",
    consent: "Consent",
    consentStates: {
      adult: "An adult",
      declared: "Declared by the student",
      pending: "Waiting for the parent",
      verified: "Confirmed by the parent",
    } as Record<string, string>,
    teacher: "Teacher access",
    teacherStates: { none: "None", requested: "Asked for", verified: "Verified" } as Record<string, string>,
    parentContact: "Parent's contact",
    deletionDue: "Deletion due",
    roles: "Roles",
    orders: "Latest orders",
    noOrders: "No order.",
    orderColumns: { number: "Order", status: "Status", created: "Placed" },
    consents: "Consent records",
    noConsents: "No consent record.",
    sessions: "Signed-in devices",
    noSessions: "Signed in nowhere.",
    sessionLine: (device: string, ip: string) => `${device} · ${ip}`,
    actions: "Actions",
    actionsLead: "Each one is recorded with your name; the customer is told where the law or our policy asks.",
    action: {
      resendVerification: "Send the email confirmation again",
      passwordReset: "Send a password reset link",
      unlock: "Unlock sign-in",
      endSessions: "Sign them out everywhere",
      suspend: "Suspend the account",
      unsuspend: "Lift the suspension",
      resetMfa: "Reset two-step sign-in",
      impersonate: "Sign in as this customer",
    },
    done: {
      resendVerification: "Link sent",
      passwordReset: "Link sent",
      unlock: "Unlocked",
      endSessions: "Signed out",
      suspend: "Suspended",
      unsuspend: "Suspension lifted",
    },
    suspendTitle: "Suspend this account?",
    suspendText: "They are signed out at once, told by email, and cannot sign in until the suspension is lifted.",
    resetMfaTitle: "Reset their two-step sign-in?",
    resetMfaText:
      "They will sign in with their password alone until they set it up again. Prove who they are first, as strongly as when they set it up. A second person approves it.",
    impersonateTitle: "Sign in to the website as this customer",
    impersonateText:
      "You see the website as they do for 15 minutes. Payments, passwords, email, consent, addresses and deletion stay closed, and they can see that you did it. Never a child's account.",
    impersonateTicket: "Ticket",
    impersonateTicketHelp: "The support ticket or the mail it answers.",
    impersonateReasonHelp: "Why: saved with every page you open as them.",
    impersonateButton: "Start",
    impersonateOpen: "Open the website as them",
    impersonateUntil: (time: string) => `Open until ${time}.`,
    impersonateEnd: "End it now",
    impersonateEnded: "Ended",
    danger: "Danger zone",
    emptyTitle: "No customer matches",
    emptyText: "Search by an email address (exactly), a mobile number, or three letters or more of a name.",
  },
  privacy: {
    requestsTitle: "Data requests",
    requestsLead:
      "Requests to see, correct or erase personal data, nominations, grievances and complaints, with the clocks the law sets.",
    incidentsTitle: "Incidents",
    incidentsLead: "The breach register. CERT-In within 6 hours, the Data Protection Board within 72 hours.",
    processorsTitle: "Processors",
    processorsLead: "Who processes personal data for ExamLeaf, for what, where, and under which contract.",
    kinds: {
      access: "Access",
      correction: "Correction",
      erasure: "Erasure",
      nomination: "Nomination",
      grievance: "Grievance",
      complaint: "Complaint",
    } as Record<string, string>,
    statuses: { new: "New", acknowledged: "Acknowledged", closed: "Closed" } as Record<string, string>,
    outcomes: { done: "Done", refused: "Refused", withdrawn: "Withdrawn" } as Record<string, string>,
    columns: {
      kind: "Kind",
      requester: "Requester",
      channel: "Channel",
      received: "Received",
      ack: "Acknowledge",
      due: "Answer",
      status: "Status",
    },
    overdueFilter: "Late",
    overdueOptions: { true: "Past the answer-by time", false: "In time" } as Record<string, string>,
    ackClock: "Acknowledge within 48 hours",
    dueClock: "Answer by",
    acknowledged: (when: string) => `acknowledged ${when}`,
    reported: (when: string) => `told ${when}`,
    summary: "What they asked",
    account: "Account",
    accountLink: (id: number) => `Customer #${id}`,
    noAccount: "Not linked to an account",
    identity: "Identity",
    verifiedRequester: (when: string) => `Checked ${when}`,
    unverifiedRequester: "Not checked yet",
    verify: "Record the identity check",
    verifyNote: "How it was checked",
    verifyNoteHelp: "The method, not the document: for example, a code sent to the account's own address.",
    verifyButton: "Record the check",
    verified: "Identity check recorded",
    acknowledge: "Acknowledge",
    acknowledgedToast: "Acknowledged",
    assignee: "Handled by",
    notes: "The request's working notes",
    notesHelp: "Notes are personal data too: they go into the requester's own access export.",
    saveNotes: "Save the notes",
    notesSaved: "Notes saved",
    erasure: "Erasure",
    erasureLead:
      "First the dry run: what would be erased and what the law makes us keep. Then the erasure itself, which a second person approves.",
    dryRunButton: "Run the dry run",
    erase: "What would be erased",
    keep: "Kept, and why",
    blocks: "What stops it now",
    keepUntil: (until: string) => `until ${until}`,
    nothingKept: "Nothing is kept back.",
    nothingErased: "Nothing would be erased.",
    count: (count: number) => plural(count, "row", "rows"),
    eraseButton: "Erase the account",
    eraseTitle: "Erase this account?",
    eraseText:
      "A change request is made: someone who may approve erasures checks it, and only then is the account erased. What the law keeps stays, as the dry run says.",
    exportTitle: "Send them their data",
    exportText:
      "For an access request with the identity checked: their data goes by email to the account's own address.",
    exportButton: "Email their data",
    response: "The answer",
    responseLead: "The text to send, with the contact block the law asks for. Adapt it, then record it when closing.",
    copyResponse: "Copy the text",
    close: "Close the request",
    closeLead: "Record the outcome and the answer as it was sent.",
    closeOutcome: "Outcome",
    closeResponse: "The answer sent",
    closeButton: "Close it",
    closed: "Closed",
    closedWith: (outcome: string, when: string) => `${outcome}, ${when}`,
    logRequest: "Log a request",
    logTitle: "Log a data request",
    logText:
      "For a request that came by email, phone, letter or in person. The clocks start from when it was received.",
    channel: "How it came",
    channels: {
      email: "Email",
      letter: "Letter",
      phone: "Phone",
      form: "The website's form",
      in_person: "In person",
      board: "Through the Data Protection Board",
    } as Record<string, string>,
    requester: "Requester's email address or mobile number",
    userId: "Customer number",
    userIdHelp: "The account it is about, when known (the number in its address: /users/42/).",
    receivedAt: "Received at",
    logButton: "Log it",
    logged: "Logged",
    incidentNew: "Record an incident",
    incidentTitle: "Record an incident",
    incidentText:
      "Record it as soon as it is noticed: the 6-hour and 72-hour clocks run from when it was detected. Partial facts are fine at first; the owners are told at once.",
    title: "What happened, in a line",
    detectedAt: "Detected at",
    incidentKind: "Kind",
    description: "What is known",
    systems: "Systems involved",
    systemsHelp: "For example: website, database",
    dataCategories: "Kinds of personal data",
    dataCategoriesHelp: "For example: email, name, marks",
    peopleAffected: "People affected (an estimate)",
    childrenAffected: "Children's data involved",
    recordIncident: "Record it",
    incidentRecorded: "Recorded",
    incidentColumns: {
      detected: "Detected",
      title: "Incident",
      kind: "Kind",
      people: "People",
      certin: "CERT-In (6 h)",
      board: "Board (72 h)",
      state: "State",
    },
    incidentStates: { open: "Open", closed: "Closed" } as Record<string, string>,
    openFilter: "State",
    certinClock: "Tell CERT-In",
    boardClock: "Report to the Board",
    certinReportedAt: "CERT-In was told at",
    certinReference: "CERT-In's reference",
    boardNotifiedAt: "The Board was first told at",
    boardReportAt: "The Board's detailed report sent at",
    boardReference: "The Board's reference",
    noticesSent: "Notices sent to people",
    noticesSentAt: "Notices sent at",
    noticeText: "The notice's text",
    incidentActions: "What was done",
    rootCause: "Root cause",
    saveIncident: "Save the incident",
    incidentSaved: "Saved",
    closeIncident: "Close the incident",
    closeIncidentText: "Its clocks stop and it leaves the open register. Record the reports first.",
    incidentClosed: "Closed",
    incidentKinds: {
      data_breach: "Data breach",
      data_leak: "Data leak",
      unauthorised_access: "Unauthorised access",
      malicious_code: "Malicious code",
      application_attack: "Attack on the application",
      denial_of_service: "Denial of service",
      loss_of_access: "Loss of access to data",
      other: "Other",
    } as Record<string, string>,
    children: "Children affected",
    processorNew: "Add a processor",
    processorTitle: "Add a processor",
    processorName: "Name",
    processorPurpose: "What they do for us",
    processorCountry: "Country or region where the data is kept",
    processorCategories: "Kinds of personal data",
    processorSigned: "Agreement signed on",
    processorContract: "Agreement ends on",
    processorAdd: "Add it",
    processorAdded: "Added",
    processorColumns: {
      name: "Name",
      purpose: "Purpose",
      country: "Where",
      categories: "Data",
      contract: "Agreement ends",
      active: "In use",
    },
    emptyRequestsTitle: "No data request",
    emptyRequestsText: "When someone asks about their data, the request and its clocks show here.",
    emptyIncidentsTitle: "No incident recorded",
    emptyIncidentsText: "Record one as soon as something is noticed: the clocks start at detection.",
    emptyProcessorsTitle: "No processor listed",
    emptyProcessorsText: "List everyone who processes personal data for ExamLeaf.",
  },
  settings: {
    title: "Settings",
    lead: "The site's settings and feature flags: where each value comes from, its history, and who changed it.",
    site: "Site settings",
    flags: "Feature flags",
    columns: { key: "Setting", value: "Value", source: "Source", effective: "From", changedBy: "Changed by" },
    sources: { environment: "Environment", database: "Console" } as Record<string, string>,
    environmentValue: (value: string) => `The environment's value: ${value}.`,
    scheduled: (value: string, when: string) => `${value} from ${when}`,
    staffMember: (id: number) => `staff #${id}`,
    change: "Change",
    changeTitle: (key: string) => `Change ${key}`,
    value: "New value",
    backToEnvironment: "Back to the environment's value",
    effectiveFrom: "Takes effect from",
    effectiveHelp: "Leave empty for at once.",
    saveChange: "Save the change",
    changed: "Saved",
    history: "History",
    historyFailed: "The history could not be read.",
    noHistory: "No change recorded.",
    historyEntry: (who: string, when: string) => `${who}, ${when}`,
    emptyTitle: "No setting to show",
    emptyText: "Settings appear here once the server lists them.",
    trueValue: "On",
    falseValue: "Off",
    emptyValue: "(empty)",
  },
  apiKeys: {
    title: "API keys",
    lead: "Keys for integrations, one per integration, each with its scopes, an end date and a person who answers for it.",
    columns: {
      name: "Name",
      prefix: "Starts with",
      scopes: "Scopes",
      created: "Made",
      expires: "Ends",
      lastUsed: "Last used",
      sponsor: "Answers for it",
      status: "Status",
    },
    statuses: { active: "Active", revoked: "Revoked", expired: "Ended" } as Record<string, string>,
    create: "Make a key",
    createTitle: "Make an API key",
    createText: "The secret is shown once, when it is made. Store it in the integration's settings straight away.",
    name: "Name",
    nameHelp: "What it is for, for example: Shiprocket sync",
    scopes: "Permissions",
    scopesHelp: "View permissions only, comma separated, for example: staff.view_system",
    allowedIps: "From these addresses only",
    allowedIpsHelp: "Optional: addresses or networks, comma separated, for example 203.0.113.0/24",
    expires: "Ends on",
    expiresHelp: "At most 12 months from today; empty: 12 months.",
    lastUsedFrom: (ip: string) => `from ${ip}`,
    createButton: "Make the key",
    secretTitle: "Copy the secret now",
    secretText: "It is never shown again. If it is lost, revoke the key and make a new one.",
    secretStored: "I have stored it",
    revoke: "Revoke",
    revokeTitle: (name: string) => `Revoke ${name}?`,
    revokeText: "Every request with this key is refused from now on. It cannot be undone.",
    revoked: "Revoked",
    emptyTitle: "No API key yet",
    emptyText: "Make one for each integration that needs to call ExamLeaf.",
  },
  system: {
    title: "System",
    lead: "Health checks, queues, webhooks, email and SMS, backups, the audit chain and maintenance mode.",
    health: "Health",
    healthy: "Passing",
    failing: "Failing",
    queues: "Queues",
    queue: "Queue",
    waiting: "Waiting",
    eager: "Tasks run at once here (no broker).",
    brokerDown: (error: string) => `The broker cannot be reached: ${error}`,
    failedTasks: (count: number) => `${plural(count, "failed task", "failed tasks")} in 7 days`,
    webhooks: "Webhooks",
    webhooksDay: "Received in the last day",
    webhooksRefused: (count: number) => `${plural(count, "webhook", "webhooks")} refused in 7 days (wrong signature)`,
    noWebhooks: "None in the last day.",
    email: "Email",
    suppressed: "Addresses suppressed",
    suppressedWeek: "Suppressed in 7 days",
    sms: "SMS in the last day",
    noSms: "No SMS in the last day.",
    backups: "Backups",
    backupsOff: "No backup bucket is set up.",
    backupError: (error: string) => `The bucket cannot be read: ${error}`,
    lastBackup: "Last backup",
    backupSize: "Size",
    noBackup: "No backup has run.",
    audit: "Audit chain",
    auditVerified: (when: string) => `Verified intact ${when}`,
    auditBroken: (when: string) => `A break found ${when}: see the inbox`,
    auditNever: "Not verified yet (nightly at 02:00).",
    reconcile: "A stuck online payment",
    reconcileLead: "Ask Razorpay what became of an order's payment (a webhook that never came).",
    reconcileOrder: "Order number",
    reconcileButton: "Ask Razorpay",
    reconciled: (order: string, paid: boolean | null) =>
      paid === null ? `${order}: Razorpay could not say.` : paid ? `${order} is paid.` : `${order} is not paid.`,
    maintenance: "Maintenance mode",
    maintenanceOn: "On: visitors see the banner and changes are closed. The console stays open.",
    maintenanceOff: "Off: the site is open.",
    banner: "Banner shown to visitors",
    turnOn: "Turn maintenance mode on",
    turnOff: "Turn maintenance mode off",
    maintenanceSaved: "Saved",
    emptyTitle: "Nothing to show",
  },
  account: {
    title: "My account",
    lead: "Where you are signed in, and how to leave.",
    you: "You",
    roles: "Your roles",
    roleUntil: (when: string) => `until ${when}`,
    sessions: "Signed-in devices",
    sessionsLead: "Every browser and app signed in to your account, on the website and here.",
    thisDevice: "this device",
    since: (when: string) => `since ${when}`,
    lastSeen: (when: string) => `last seen ${when}`,
    now: "now",
    signOutDevice: "Sign out",
    signOutDeviceName: (name: string) => `Sign out ${name}`,
    signedOutDevice: "Signed out",
    signOutEverywhere: "Sign out everywhere",
    signOutEverywhereText: "Ends every session of your account, this one too.",
    sessionsFailed: "The list of devices could not be read.",
    addressUnknown: "address unknown",
    aBrowser: "A browser",
    on: (browser: string, system: string) => `${browser} on ${system}`,
    security: "Two-step sign-in and passkeys",
    securityText: "Change them on your ExamLeaf account page.",
    securityLink: "Open the account page",
    limits: "Your limits",
    limitsLead: "Above them, what you ask for waits for a second person. The backend sets them by role.",
    limitNames: {
      refund_inr: "Refunds, in rupees",
      offline_inr: "Payments recorded offline, in rupees",
      discount_percent: "Discount off the MRP, per cent",
      export_rows: "Rows exported at once",
      bulk_rows: "Rows of a bulk action",
    } as Record<string, string>,
    noLimit: "No limit",
  },
  notes: {
    side: "Notes and audit trail",
    title: "Notes",
    lead: "For colleagues: what was said, what was promised. Notes are personal data too and go into access exports.",
    none: "No note yet.",
    add: "Add a note",
    body: "Note",
    save: "Save the note",
    saved: "Note saved",
    by: (who: string, when: string) => `${who}, ${when}`,
  },
  soon: {
    title: (module: string) => `${module} comes in the next phase`,
    text: "This module is planned and not built yet. Until it is, the Django admin does this work.",
    /** Where a module's work is done today when the Django admin does not do it. */
    today: {
      insights:
        "This module is planned and not built yet. The nightly forecasts, print runs and signals are computed already; the Django admin shows their runs until then.",
    } as Record<string, string>,
    admin: "Open the Django admin",
    eyebrow: "Coming next",
  },
  problem: {
    noAccessTitle: "No access",
    unavailableTitle: "Not available just now",
    badResponseTitle: "Could not be read",
    throttledTitle: "Too many requests",
    failedTitle: "Something went wrong",
  },
  states: {
    active: "Active",
    inactive: "Inactive",
    yes: "Yes",
    no: "No",
  },
  support: {
    title: "Support",
    lead: "Complaints and questions from customers, each with its number and the deadlines the law sets. The next deadline comes first.",
    logCall: "Log a call or message",
    replies: "Saved replies",
    register: "Grievance register",
    numbers: "The last 30 days",
    received: "Received",
    firstResponse: "First reply, median",
    resolution: "Resolved in, median",
    backlog: "Open now",
    overdue: "Past a deadline now",
    breaches: "Deadlines missed",
    noneYet: "None yet",
    tabsLabel: "Which tickets",
    tabs: {
      due: "Due soonest",
      mine: "Mine",
      unassigned: "Unassigned",
      overdue: "Overdue",
      waiting: "Waiting",
      all: "All",
    } as Record<string, string>,
    columns: {
      ticket: "Ticket",
      requester: "From",
      category: "Category",
      status: "Status",
      clock: "Next deadline",
      assignee: "Assigned to",
      source: "Came by",
      priority: "Priority",
      received: "Received",
      messages: "Messages",
    },
    searchLabel: "Search by number, email or mobile",
    testFilter: "Test orders",
    testOptions: { true: "Only the tickets about test orders" } as Record<string, string>,
    statuses: {
      new: "New",
      open: "Open",
      waiting_customer: "Waiting on the customer",
      waiting_third_party: "Waiting on others",
      resolved: "Resolved",
      closed: "Closed",
      spam: "Spam",
    } as Record<string, string>,
    categories: {
      order: "Order",
      payment: "Payment or refund",
      book_code: "Book code",
      qr_solutions: "QR solutions",
      content_error: "Mistake in the content",
      school_order: "School order",
      privacy_request: "Privacy request",
      grievance: "Grievance",
    } as Record<string, string>,
    notSorted: "Not sorted",
    sources: {
      form: "Website form",
      email: "Email",
      phone: "Phone call",
      whatsapp: "WhatsApp",
      nch: "National Consumer Helpline",
    } as Record<string, string>,
    priorities: { low: "Low", medium: "Medium", high: "High", urgent: "Urgent" } as Record<string, string>,
    languages: { en: "English", as: "Assamese", bn: "Bengali" } as Record<string, string>,
    channels: {
      web: "the website",
      email: "email",
      phone: "phone",
      whatsapp: "WhatsApp",
      sms: "SMS",
      nch: "NCH's portal",
      panel: "the console",
    } as Record<string, string>,
    replyChannels: {
      email: "Email it to them",
      phone: "Said on a call",
      whatsapp: "Sent on WhatsApp",
      nch: "Answered on NCH's portal",
    } as Record<string, string>,
    clockAck: "Acknowledge by",
    clockDue: "Resolve by",
    stoppedOn: (status: string, when: string) => `${status} ${when}`,
    missed: "deadline missed",
    test: "Test order",
    emptyTitle: "No ticket here",
    emptyText: "When a customer writes or calls, their ticket shows here with its next deadline.",
    // a ticket
    opened: "Opening a ticket is recorded in the audit trail.",
    openedChild: "This customer is a child: opening their ticket is recorded as a look at a child's data.",
    take: "Take it",
    taken: "Taken",
    facts: "About it",
    number: "Number",
    source: "Came by",
    docket: "NCH docket",
    receivedAt: "Received",
    requester: "Requester",
    name: "Name",
    email: "Email address",
    phone: "Mobile number",
    account: "Account",
    accountLink: (id: number) => `Customer #${id}`,
    noAccount: "No account",
    category: "Category",
    priority: "Priority",
    language: "Language",
    order: "Order",
    record: "Paper",
    dataRequest: "Data request",
    dataRequestNumber: (id: number) => `DR-${id}`,
    assignee: "Assigned to",
    acknowledged: "Acknowledged",
    notYet: "Not yet",
    ackHeld: "It goes by SMS at 08:00: messages are not sent at night.",
    firstReply: "First reply",
    resolved: "Resolved",
    closed: "Closed",
    reopened: "Reopened",
    reopenedTimes: (count: number) => plural(count, "time", "times"),
    complaintCopy: "Copy of the complaint sent",
    resolutionText: "What was done",
    clocks: "Deadlines",
    clocksLead: "Set by the law from when it was received, in India's time. They never pause, not even while it waits.",
    clockNames: {
      ack: "Acknowledge",
      redress: "Redress",
      nch: "National Consumer Helpline",
      dpdp: "Privacy request",
      it_ack: "Acknowledge (IT Rules)",
      it_resolve: "Resolve (IT Rules)",
    } as Record<string, string>,
    clockMet: (when: string) => `Met: done ${when}`,
    clockMissed: (when: string) => `Missed: done ${when}`,
    conversation: "Conversation",
    noMessages: "No message yet.",
    fromCustomer: "The customer",
    fromSomeone: "Someone else",
    fromSite: "ExamLeaf",
    otherSender: "From another address than the requester's: check who wrote before you answer.",
    messageKinds: { in: "Wrote", out: "Replied", note: "Internal note" } as Record<string, string>,
    via: (channel: string) => `by ${channel}`,
    automatic: "sent by the site",
    mentioned: (names: string) => `Told: ${names}`,
    files: "Files",
    fileSize: (name: string, size: string) => `${name} (${size})`,
    dropped: "Not kept",
    compose: "Write",
    composeLabel: "What to write",
    composeModes: { out: "Reply to the customer", note: "Internal note" } as Record<string, string>,
    replyLabel: "Your reply",
    noteLabel: "Your note",
    replyHelp:
      "An email goes in the customer's thread with the ticket's number. A call or a message sent elsewhere is recorded here.",
    noteHelp: "Only staff see it. Name a colleague to put it in their inbox.",
    channel: "How",
    mentions: "Tell colleagues",
    noColleagues: "No colleague can be named on this ticket.",
    savedReplies: "Saved replies",
    savedRepliesHelp: (language: string) =>
      `Those in ${language} first. Alt and the number puts one in where the cursor is.`,
    insert: (key: number) => `Alt ${key}`,
    noSavedReplies: "No saved reply yet.",
    send: "Send the reply",
    recordReply: "Record the reply",
    saveNote: "Save the note",
    sent: "Reply sent",
    recorded: "Reply recorded",
    noted: "Note saved",
    status: "Status",
    statusLead: "Move it on. Resolving or closing it asks for what its category needs.",
    newStatus: "New status",
    chooseStatus: "Choose",
    resolutionHelp: "Kept with the ticket. The grievance register counts the days it took.",
    orderNumber: "Order number",
    orderHelp: "The order it is about, for example EL-2026-000123.",
    paperCode: "Paper code",
    paperHelp: "The paper the mistake is in, for example PHY-E01.",
    sortFirst: "Sort it first: choose its category under Sort and correct.",
    dataRequestFirst: "Start its data request first, under Actions.",
    changeStatus: "Change the status",
    statusChanged: "Status changed",
    reopen: "Reopen it",
    reopenText: "Back to open, counted as reopened. Its deadlines kept running while it was resolved.",
    reopenedToast: "Reopened",
    noMoves: "Closed: nothing follows. A new message from the customer starts a new ticket.",
    assignTitle: "Who handles it",
    assignTo: "Give it to",
    nobody: "Nobody",
    assign: "Assign",
    assigned: "Assigned",
    acknowledgement: "Acknowledgement",
    acknowledgementLead:
      "Sent by itself with the number when the ticket came: by email, or by SMS when only a mobile number is known.",
    sendAck: "Send the acknowledgement",
    sendAckAgain: "Send it again",
    ackSent: "Sent",
    ackOtherWay: "It was acknowledged another way",
    ackHow: "How it was acknowledged",
    ackHowHelp: "For example: on the call, on WhatsApp, on NCH's portal.",
    ackRecord: "Record it",
    ackRecorded: "Recorded",
    details: "Sort and correct",
    detailsLead: "A new category or source sets its deadlines again from when it was received.",
    subject: "Subject",
    keepContact: "Leave empty to keep the one on record.",
    saveDetails: "Save the changes",
    detailsSaved: "Saved",
    actions: "Actions",
    actionsLead:
      "Each one is written on the ticket and in the audit trail. A refund above your limit waits for finance to approve it.",
    ordersActions: "Act on an order",
    ordersLead: "The requester's orders, newest first.",
    noOrders: "No order of this requester's.",
    refund: "Refund",
    refundCancel: "Not shipped yet: it is cancelled and refunded in full.",
    refundPartial: "Shipped: refund the copies sent back, or an amount.",
    refundLines: "Copies to refund",
    refundLine: (title: string, quantity: number) => `${title} (of ${quantity})`,
    refundAmount: "Or an amount in rupees",
    refundAmountHelp: "Leave empty to refund the copies chosen above.",
    refundChoose: "Choose the copies to refund, or write the amount: nothing was sent.",
    refundButton: "Refund",
    refunded: "Refund made",
    cancelOrder: "Cancel the order",
    cancelTitle: (order: string) => `Cancel ${order}?`,
    cancelText: "An order paid online is cancelled through its refund. The customer is told by email.",
    cancelled: "Order cancelled",
    resendInvoice: "Send the invoice again",
    invoiceSent: "Invoice sent",
    resendConfirmation: "Send the confirmation again",
    confirmationSent: "Confirmation sent",
    extend: "Extend course access",
    extendWhich: "Course access",
    extendDays: "Days to add",
    extendDaysHelp: "From its end, or from today if it has ended: 1 to 365.",
    extendButton: "Extend it",
    extended: "Access extended",
    noExtendable: "No course access with an end date to extend.",
    bookCode: "Look up a book code",
    bookCodeLabel: "The code, as printed",
    bookCodeHelp: "For example 7KQM-3XPA-9TRW. The code itself is never kept.",
    lookUp: "Look it up",
    startDataRequest: "Start a data request",
    dataRequestLead:
      "For a request to see, correct or erase their data: it joins the rights queue with its own deadlines.",
    dataRequestKind: "Kind",
    dataRequestSummary: "What they ask",
    dataRequestSummaryHelp: "Leave empty to use the ticket's subject.",
    dataRequestButton: "Start it",
    dataRequestStarted: "Request started",
    orderStatus: (status: string, total: string) => `${status} · ${total}`,
    thisTicket: "this ticket's",
    // the side
    side: "The customer and the audit trail",
    customer: "The customer",
    openCustomer: "Open the customer's record",
    orders: "Orders",
    paidWith: (method: string) => `paid by ${method}`,
    payment: "Payment",
    refunds: "Refunds",
    shipment: (courier: string, tracking: string) => `${courier} ${tracking}`,
    track: "Track it",
    delivered: (when: string) => `delivered ${when}`,
    invoice: (number: string) => `Invoice ${number}`,
    creditNotes: (numbers: string) => `Credit notes: ${numbers}`,
    course: "Course access",
    noEnd: "no end date",
    until: (when: string) => `until ${when}`,
    ended: (when: string) => `ended ${when}`,
    codes: "Book codes redeemed",
    devices: "Devices",
    deviceKinds: { app: "The app", browser: "A browser" } as Record<string, string>,
    otherTickets: "Their other tickets",
    consents: "Consent records",
    byParent: "by a parent",
    none: "None.",
    // logging a ticket
    newTitle: "Log a call or message",
    newLead:
      "For a complaint that came by phone, WhatsApp, the National Consumer Helpline or email. Its deadlines run from when it was received, and the acknowledgement goes to the address or number given.",
    cameBy: "How it came",
    loggedSources: {
      phone: "Phone call",
      whatsapp: "WhatsApp",
      nch: "National Consumer Helpline",
      email: "Email",
    } as Record<string, string>,
    docketHelp: "As NCH's portal gives it.",
    phoneHelp: "The number they called or wrote from.",
    emailHelp: "Where the acknowledgement and replies go.",
    message: "What they said or wrote",
    messageHelp: "The complaint as recorded: a copy goes with the acknowledgement.",
    receivedAtHelp: "When it came, in India's time.",
    sortLater: "Not sorted yet",
    logButton: "Log it",
    logged: "Ticket logged",
    // saved replies
    repliesLead:
      "Answers to put in with one keystroke, in English, Assamese and Bengali. {name}, {order}, {refund_days} and {number} are filled in for each ticket; {name|there} says what to write when there is nothing.",
    replyColumns: { title: "Title", language: "Language", variables: "Variables", modified: "Changed" },
    replyTitle: "Title",
    replyLanguage: "Language",
    replyBody: "Text",
    addReply: "Add a saved reply",
    addButton: "Add it",
    added: "Reply added",
    edit: "Edit",
    editTitle: (title: string) => `Edit ${title}`,
    saveReply: "Save the reply",
    replySaved: "Saved",
    deleteReply: "Delete",
    deleteName: (title: string) => `Delete ${title}`,
    deletedNotice: (title: string) => `${title} is in the bin.`,
    undo: "Undo",
    restore: "Restore",
    restoreName: (title: string) => `Restore ${title}`,
    restored: "Restored",
    bin: "Deleted in the last 30 days",
    binEmpty: "Nothing in the bin.",
    noVariables: "None",
    repliesEmptyTitle: "No saved reply yet",
    repliesEmptyText: "Add the answers you give most often.",
    // the grievance register
    registerLead:
      "A dated CSV of the complaints received, acknowledged and resolved, with the days taken and the NCH dockets: ticket numbers and categories only, no personal data. Above your export limit it waits for an approver.",
    registerFrom: "Received from",
    registerUntil: "Received until",
    registerHelp: "Both optional: leave them empty for every ticket.",
    registerButton: "Make the file",
    registerStarted: "Export started",
    registerJobs: "Your exports",
    noRegisterJobs: "You have made no export yet.",
  },
};

export type Copy = typeof en;

/** The console's words. One language for now; the person's language picks the object once the others exist. */
export const copy: Copy = en;

/** A code the API sends that no table here names ("sync_failure"): its words, as a fallback ("Sync failure"). */
export function humanize(code: string): string {
  const words = code.replace(/[_-]+/g, " ").trim();
  return words ? words[0].toUpperCase() + words.slice(1).toLowerCase() : code;
}

/** The label of a known code, else its humanized words. */
export function labelOf(table: Record<string, string>, code: string | null | undefined): string {
  if (!code) return copy.common.unknown;
  return table[code] ?? humanize(code);
}
