// Every word the panel shows, in one place (the copied design-system kit in src/components/ui/ keeps its own few words,
// identical to the public site's, so that a shared package later is a move). English now; Assamese and Bengali follow
// as objects of the same shape (`as`, `bn`), chosen by the person's language, with no i18n library: a function where
// a sentence takes a number or a name, a string everywhere else. The API's own words (its `detail`) are shown as they
// come: the backend decides, the panel draws.

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const plural = (count: number, one: string, many: string) =>
  `${count.toLocaleString("en-IN")} ${count === 1 ? one : many}`;

export const en = {
  lang: "en",
  app: {
    name: "ExamLeaf Admin",
    short: "Admin",
    titleTemplate: "%s · ExamLeaf Admin",
    description: "The staff console of ExamLeaf.",
    skip: "Skip to the content",
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    retry: "Try again",
    reload: "Reload",
    copy: "Copy",
    copied: "Copied",
    open: "Open",
    remove: "Remove",
    confirm: "Confirm",
    continue: "Continue",
    yes: "Yes",
    no: "No",
    none: "None",
    unknown: "Not known",
    never: "Never",
    optional: "optional",
    reason: "Reason",
    reasonHelp: "Saved in the audit trail with your name.",
    reasonRequired: "Give a reason: it is saved in the audit trail.",
    details: "Details",
    actions: "Actions",
    loading: "Loading…",
    working: "Working…",
    done: "Done",
    me: "Me",
    anyone: "Anyone",
    all: "All",
    on: "On",
    off: "Off",
    from: "From",
    to: "To",
    search: "Search",
    clear: "Clear",
    apply: "Apply",
    opensElsewhere: "(opens in a new tab)",
    recorded: "Recorded in the audit trail.",
    signOut: "Sign out",
    discard: "Discard",
    unsaved: "Unsaved changes",
    unsavedText: "Save them, or discard them.",
    leaveWarning: "Leave this page? What you typed is not saved.",
  },
  time: {
    months: MONTHS,
    justNow: "just now",
    minutesAgo: (minutes: number) => `${plural(minutes, "minute", "minutes")} ago`,
    hoursAgo: (hours: number) => `${plural(hours, "hour", "hours")} ago`,
    daysAgo: (days: number) => `${plural(days, "day", "days")} ago`,
    duration: (days: number, hours: number, minutes: number) =>
      days > 0 ? `${days} d ${hours} h` : hours > 0 ? `${hours} h ${minutes} min` : `${minutes} min`,
    left: (duration: string) => `${duration} left`,
    overdue: (duration: string) => `overdue by ${duration}`,
    at: (date: string, time: string) => `${date}, ${time}`,
    until: (when: string) => `until ${when}`,
  },
  errors: {
    unavailable: "The ExamLeaf server cannot be reached just now. Check your connection, then try again.",
    unconfirmed: "The server didn't answer in time, so this may have gone through. Check before you try again.",
    signedOut: "Your session has ended. Sign in again; what you typed is kept on this device.",
    forbidden: "You don't have access to this.",
    permissionDenied: "Your role does not allow this.",
    impersonatingTitle: "Not while you are signed in as a customer",
    impersonating:
      "While this session is signed in to the website as a customer, payments, passwords, email, two-step sign-in, consent, addresses and deletion stay closed. End the impersonation first.",
    linkExpired: "The file's link has expired. Download it again for a fresh one.",
    reauthRequired: "Confirm it's you to do this.",
    reauthCancelled: "Nothing was changed: this needs you to confirm it's you first.",
    approvalRequired: "This needs a second person's approval.",
    mfaSetup: "Staff accounts need two-step sign-in first.",
    notFound: "Not found, or outside the records you look after.",
    conflict: "Someone else changed this while you were editing.",
    conflictHint: "Reload to see their change; what you typed is kept.",
    throttled: "Too many requests. Wait a little, then try again.",
    throttledUntil: (time: string) => `Too many requests. You can try again after ${time}.`,
    server: "Something went wrong on our side. Please try again.",
    badRequest: "Check what you entered.",
    badResponse: "The server's answer was not what this page expects. Nothing was changed by this page.",
    problem: "There is a problem",
    timedOut: "The form timed out. Reload the page and send it again.",
    reference: (digest: string) => `Reference: ${digest}`,
    unavailableTitle: "The server can't be reached right now",
    unavailableText: "Nothing is wrong with the records. Please try again in a minute.",
    pageFailedTitle: "Something went wrong on our side",
    pageFailedText: "This page could not be shown. Please try again in a minute.",
    notFoundTitle: "Not found, or not yours to see",
    notFoundText:
      "The address may be mistyped or the record removed, or it is outside the records you look after: the console does not say which.",
    goHome: "Go to Home",
  },
  auth: {
    signInTitle: "Sign in to ExamLeaf Admin",
    signInLead: "For ExamLeaf staff. Every sign-in is recorded.",
    email: "Email address",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    show: "Show",
    hide: "Hide",
    signIn: "Sign in",
    google: "Continue with Google",
    or: "or",
    unavailableTitle: "Sign-in is not available just now",
    unavailableText: "The ExamLeaf server cannot be reached. Please try again in a minute.",
    twoStepTitle: "Two-step check",
    twoStepLead: "Open your authenticator app and enter the 6-digit code for ExamLeaf.",
    recoveryLead: "Type one of your recovery codes.",
    recoveryCode: "Recovery code",
    useRecovery: "Use a recovery code",
    useApp: "Use the app's code",
    usePasskey: "Use a passkey or security key",
    nothingDueTitle: "No second step is waiting",
    nothingDueText: "The step may have timed out, or it was done already. Sign in again to start over.",
    startAgain: "Start again",
    tooManyTitle: "Too many tries",
    tooMany: (time: string) => `To keep accounts safe, sign-in tries are limited. You can try again after ${time}.`,
    next: (path: string) => `After signing in you'll go back to ${path}`,
    nextLabel: "NEXT",
    idleNotice: "You were signed out after a time without activity. Sign in to go back; what you typed is kept.",
    expiredNotice: "Your session ended. Sign in to go back; what you typed is kept on this device.",
    signedOutNotice: "You are signed out.",
    googleCancelled: "You didn't finish signing in with Google. Nothing was changed.",
    googleFailed: "Google couldn't sign you in. Please try once more.",
    // the backend's refusals of a staff Google sign-in (accounts/adapter.py refuse_google), as ?error=
    googleRefused: {
      staff_google_domain: "Sign in with your work Google account: the ExamLeaf Workspace address.",
      staff_google_no_account: "No staff account has this Google address. Ask the owner or an admin to invite you.",
      staff_google_not_staff: "This account is not a member of staff, so it cannot sign in to the console.",
      staff_google_break_glass:
        "A break-glass account signs in with its password and its own second factor, not Google.",
    } as Record<string, string>,
    inactiveTitle: "This account is switched off",
    inactiveText:
      "A switched-off account cannot sign in to the console. If you think this is a mistake, ask the owner or an admin.",
    noAccessTitle: "This account has no access to the console",
    noAccessText:
      "You are signed in, but the console is for ExamLeaf staff. Sign out, then sign in with your staff account.",
    setupTitle: "Set up two-step sign-in first",
    setupText:
      "Staff accounts need an authenticator app or a passkey before the console opens. Set one up on your ExamLeaf account page, then come back and sign in again.",
    setupLink: "Set it up on the website",
    setupThen: "Once it is set up, sign out here and sign in again.",
    confirmTitle: "Confirm it's you",
    confirmLead: "For your safety, this action needs a fresh check.",
    confirmCode: "Enter the 6-digit code from your authenticator app.",
    confirmPassword: "Type your password instead",
    confirmUseCode: "Use the authenticator code instead",
    confirmPasskey: "Use a passkey instead",
    confirm: "Confirm",
  },
  idle: {
    warnTitle: "You'll be signed out soon",
    warnText: (time: string) =>
      `For safety, the console signs you out after a time without activity. That happens at ${time}.`,
    endTitle: "Your session ends soon",
    endText: (time: string) => `Sessions last a fixed time. This one ends at ${time}; sign in again then.`,
    stay: "Stay signed in",
    signOutNow: "Sign out now",
    keep: "What you typed in a form is kept on this device.",
  },
  shell: {
    menu: "Menu",
    closeMenu: "Close",
    modules: "Modules",
    search: "Search or jump to…",
    inbox: "Inbox",
    /** After the inbox's count, for screen readers: "Inbox 6 open". */
    inboxOpen: "open",
    /** After the person's name on their menu's button: "Anita Baruah, your account". */
    yourAccount: ", your account",
    account: "My account and sessions",
    shortcuts: "Keyboard shortcuts",
    shortcutsSwitch: "Single-key shortcuts",
    signOutEverywhere: "Sign out everywhere",
    signOutEverywhereFailed:
      "Your other sessions could not be ended, so you are still signed in here. Try again in a minute.",
    roles: "Roles",
    erp: "In ERPNext",
    erpOpens: "opens ERPNext",
    soon: "soon",
    test: "Test",
    testLabel: "Test environment",
    testText: "Not the live site: what you see and do here is test data.",
    impersonating: (email: string, until: string) =>
      `You are signed in to the website as ${email} until ${until}. Every action is recorded.`,
    endImpersonation: "End",
    impersonationEnded: "Ended",
    impersonationElsewhere: "It ends by itself then, or from the website's own banner.",
    breakGlassLabel: "Break-glass session",
    breakGlass:
      "A break-glass account: every check passes and nothing is limited. Every action is marked, the owners are told, and each is reviewed within 24 hours.",
    breakGlassReason: (reason: string) => `Reason given: ${reason}`,
    reasonTitle: "Why is a break-glass account needed?",
    reasonText:
      "Before anything else, say what happened that no other account could handle. The reason is kept in the audit log and sent to the owners.",
    reasonButton: "Give the reason",
    reasonGiven: "Reason recorded",
    policiesTitle: "Read and acknowledge",
    policiesText: "Before you go on, read these policies in their current version. Your acknowledgement is recorded.",
    // STAFF_POLICIES' keys (acceptable_use …) as words: "Acceptable use"
    policyName: (key: string) => key.charAt(0).toUpperCase() + key.slice(1).replaceAll("_", " "),
    policyVersion: (version: string) => `version ${version}`,
    policiesAcknowledge: "I have read them and will follow them",
    policiesDone: "Acknowledged",
    shortcutsTitle: "Keyboard shortcuts",
    shortcutsList: [
      ["⌘ K or Ctrl K", "Search or jump to a page"],
      ["/", "Search the list"],
      ["j / k", "Next or previous row"],
      ["Enter", "Open the row"],
      ["Space", "Look at the row beside the list"],
      ["x", "Select the row"],
      ["?", "This list"],
      ["Esc", "Close a dialog"],
    ] as [string, string][],
    shortcutsNote: "Single-key shortcuts can be switched off in your account menu.",
  },
  palette: {
    title: "Search or jump to",
    label: "Search the console",
    placeholder: "A page, a customer, a staff member…",
    pages: "Pages",
    recent: "Recent",
    actions: "Actions",
    customers: "Customers",
    people: "Staff",
    nothing: "Nothing matches.",
    searching: "Searching…",
    failed: "Search could not reach the server.",
    hint: "Type at least two letters to search customers and staff.",
    inviteAction: "Invite a staff member",
    incidentAction: "Record an incident",
    requestAction: "Log a data request",
    signOutAction: "Sign out",
    shortcutsAction: "Show keyboard shortcuts",
  },
  nav: {
    groups: {
      work: "Work",
      shop: "Shop",
      learning: "Content and course",
      customers: "Customers and partners",
      privacy: "Legal and privacy",
      reports: "Reports",
      staff: "Staff",
      system: "System",
      erp: "In ERPNext",
    },
    modules: {
      home: "Home",
      inbox: "Inbox",
      approvals: "Approvals",
      audit: "Audit trail",
      orders: "Orders",
      shipping: "Shipping",
      catalogue: "Catalogue",
      marketing: "Marketing",
      content: "Content",
      course: "Course",
      users: "Customers",
      partners: "Partners",
      requests: "Data requests",
      incidents: "Incidents",
      processors: "Processors",
      cockpit: "Compliance cockpit",
      policies: "Policy versions",
      retention: "Retention",
      holds: "Legal holds",
      disclosures: "Disclosures",
      darkPatterns: "Dark-pattern audit",
      insights: "Forecasts and signals",
      people: "People",
      accessReview: "Access review",
      apiKeys: "API keys",
      settings: "Settings",
      system: "System",
      account: "My account",
      tax: "Tax",
      finance: "Finance",
      gstReturns: "GST returns",
      inventory: "Inventory",
      purchases: "Purchases",
      crm: "CRM",
    },
  },
  table: {
    columns: "Columns",
    columnsLegend: "Columns to show",
    previous: "Previous page",
    next: "Next page",
    pages: "Pages of the list",
    density: "Rows",
    emptyTitle: "Nothing here yet",
    emptyText: "When there is something, it shows here.",
    noMatchTitle: "The filters match nothing",
    noMatchText: "Change or clear the filters to see more.",
    clearFilters: "Clear the filters",
    region: (label: string) => `${label}, a table`,
  },
  filters: {
    label: "Filters",
    search: "Search",
    searchList: (what: string) => `Search ${what}`,
    any: "Any",
    from: "From",
    to: "To",
    apply: "Apply",
    clear: "Clear the filters",
  },
  views: {
    label: "Saved views",
    standard: "Everything",
    save: "Save as a view",
    saveText: "Its filters, columns and sort are kept under a name, as a tab above the list.",
    update: "Update this view",
    remove: "Delete this view",
    name: "Name of the view",
    share: "Share with",
    onlyMe: "Only me",
    role: (role: string) => `Everyone with the ${role} role`,
    saved: "View saved",
    updated: "View updated",
    removed: "View deleted",
    removeTitle: (name: string) => `Delete the view "${name}"?`,
    removeText: "The filters and columns it keeps are deleted for everyone it is shared with.",
    changed: "The filters or columns differ from this view.",
    shared: "shared",
  },
  jobs: {
    title: "Your background jobs",
    lead: "Exports and bulk actions you started, newest first. A file waits a week; its link is made fresh each time.",
    none: "You have started no background job.",
    kinds: {
      audit_export: "Audit trail export",
      bulk_action: "Bulk action",
      erp_initial_load: "ERPNext initial load",
      gstr1_export: "GSTR-1 export",
    } as Record<string, string>,
    states: {
      queued: "Waiting",
      running: "Running",
      done: "Done",
      failed: "Failed",
      cancelled: "Cancelled",
    } as Record<string, string>,
    started: "Started",
    progress: (done: number, total: number) =>
      `${done.toLocaleString("en-IN")} of ${total.toLocaleString("en-IN")} done`,
    finished: (done: number, failed: number) =>
      failed ? `Done: ${done.toLocaleString("en-IN")}, ${plural(failed, "row", "rows")} failed` : "All done",
    failedTitle: "These rows failed",
    jobFailed: "The job stopped before it finished.",
    jobCancelled: "Cancelled: it stopped where it was.",
    queued: "Waiting to start…",
    awaiting: (id: string) => `Waiting for a second person to approve it: change request ${id}.`,
    progressName: "Progress of the job",
    cancel: "Cancel the job",
    cancelled: "Cancelled",
    download: "Download the file",
    gone: "Its file is no longer kept.",
    columns: { job: "Job", state: "State", progress: "Rows", started: "Started" },
  },
  masked: {
    reveal: "Reveal",
    revealWhat: (what: string) => `Reveal the ${what}`,
    revealTitle: (what: string) => `Reveal the ${what}?`,
    revealText: "Revealing personal data is recorded with your reason. It is shown for 60 seconds, then hidden again.",
    revealButton: "Reveal it",
    hiddenIn: (seconds: number) => `Hidden again in ${seconds} s`,
    hide: "Hide now",
    email: "email address",
    phone: "mobile number",
    none: "None on record",
  },
  confirmTyped: {
    instruction: (label: string) => `To confirm, type ${label} below.`,
    field: "Type to confirm",
    mismatch: "What you typed does not match.",
  },
  approval: {
    title: "A second person needs to approve this",
    text: "Nothing has changed yet. A change request was made; an approver has been asked, and you'll see the outcome in your inbox.",
    status: (status: string) => `Its state: ${status}.`,
    checker: "Who may approve it: someone who holds",
    open: "Open the change request",
    number: (id: string) => `Change request ${id}`,
  },
  home: {
    title: "Home",
    lead: "What waits for you today.",
    inbox: "Your inbox",
    inboxEmpty: "Nothing waits for you.",
    inboxCount: (open: number, overdue: number) =>
      overdue
        ? `${plural(open, "item", "items")} open, ${overdue.toLocaleString("en-IN")} overdue`
        : `${plural(open, "item", "items")} open`,
    openInbox: "Open the inbox",
    approvals: "Approvals",
    approvalsForYou: (count: number) => `${plural(count, "request", "requests")} waiting for a decision`,
    approvalsYours: (count: number) => `${plural(count, "request", "requests")} of yours waiting for someone else`,
    approvalsEmpty: "No change request is waiting.",
    openApprovals: "Open approvals",
    clocks: "Clocks",
    clocksLead: "Data requests and incidents, nearest to due first.",
    clocksEmpty: "No clock is running.",
    health: "System health",
    healthOk: "Every check passes.",
    healthFailing: (count: number) => `${plural(count, "check", "checks")} failing`,
    openSystem: "Open System",
    quickLinks: "Your modules",
    more: (count: number) => `more than ${count.toLocaleString("en-IN")}`,
  },
  inbox: {
    title: "Inbox",
    lead: "What waits: items given to you, and those given to nobody that your permissions let you act on.",
    states: { open: "Open", snoozed: "Open and snoozed", done: "Done" } as Record<string, string>,
    stateLabel: "Show",
    kind: "Kind",
    assignee: "Assigned to",
    mine: "Only mine",
    columns: { title: "What", kind: "Kind", due: "Due", assignee: "Assigned to", created: "Arrived" },
    done: "Mark done",
    snooze: "Snooze",
    snoozeUntil: "Snooze until",
    assignToMe: "Assign to me",
    markedDone: "Marked done",
    snoozed: "Snoozed",
    assigned: "Assigned",
    unassigned: "No one",
    you: "You",
    staffMember: (id: number) => `Staff #${id}`,
    overdue: "overdue",
    snoozedUntil: (when: string) => `snoozed until ${when}`,
    emptyTitle: "Nothing waits",
    emptyText: "When something needs you, it arrives here.",
    kinds: {
      approval: "Approval",
      teacher_request: "Teacher access",
      deletion_request: "Account deletion",
      data_request: "Data request",
      incident: "Incident",
      failed_job: "Failed job",
      failed_webhook: "Failed webhook",
      sync_failed: "ERPNext refused a document",
      reconciliation: "ERPNext differences",
      tax_threshold: "Tax threshold",
      credit_note_missing: "Credit note missing",
      processor_task: "Processor task",
      compliance: "Compliance",
    } as Record<string, string>,
  },
  audit: {
    title: "Audit trail",
    lead: "Every staff action and every look at personal data, newest first. It cannot be edited.",
    filters: {
      actionPrefix: "Action starts with",
      actor: "Who (staff id)",
      targetType: "Record type",
      targetId: "Record id",
      outcome: "Outcome",
      changeRequest: "Change request",
      breakGlass: "Break-glass only",
    },
    columns: { ts: "When", actor: "Who", action: "Action", target: "Record", outcome: "Outcome", reason: "Reason" },
    eventTitle: "Audit event",
    onBehalfOf: "On behalf of",
    permission: "Permission used",
    changeRequest: "Change request",
    requestId: "Request id",
    ip: "Address",
    chain: "Chain",
    hash: "Chain hash",
    breakGlass: "Break-glass",
    changes: "What changed",
    details: "Details",
    field: "Field",
    before: "Before",
    after: "After",
    noChanges: "No field changed.",
    outcomes: { success: "Done", denied: "Refused", failed: "Failed" } as Record<string, string>,
    actorTypes: {
      staff: "Staff",
      user: "A customer",
      service: "An API key",
      system: "The system",
      anonymous: "Someone signed out",
    } as Record<string, string>,
    actor: (type: string, id: number | null | undefined) => (id ? `${type} #${id}` : type),
    export: "Export",
    exportTitle: "Export the audit trail",
    exportText:
      "Exports the events the filters show, with their hashes, as JSON lines: at once up to 5,000 rows within your limit, else as a background job (a larger one waits for an admin's approval).",
    exportStart: "Export what the filters show",
    exported: "Downloaded",
    emptyTitle: "No event matches",
    emptyText: "Change the filters, or widen the dates.",
  },
  approvals: {
    title: "Approvals",
    lead: "Changes that need a second person. The approver sees and approves the exact request that will run.",
    states: {
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      expired: "Expired",
      executed: "Done",
      failed: "Failed",
    } as Record<string, string>,
    columns: {
      action: "Change",
      target: "Record",
      amount: "Amount",
      maker: "Asked by",
      expires: "Expires",
      state: "State",
    },
    awaiting: "Waiting for me",
    mine: "Asked by me",
    maker: "Asked by",
    reason: "Their reason",
    rule: "Why it waits",
    checker: "Who may approve",
    amount: "Amount",
    target: "Record",
    expires: "Expires",
    created: "Asked",
    ask: "Ask for a refund",
    askLead:
      "A refund of an order paid online. Within your limit it runs at once; above it, a change request waits for finance.",
    askOrder: "Order number",
    askAmount: "Amount in rupees",
    askAmountHelp: "Leave empty for the whole amount paid. An order not shipped yet is cancelled and refunded in full.",
    askButton: "Ask for the refund",
    asked: "Refund started",
    payload: "The exact request that will run",
    payloadHelp: "This is what runs when the request is approved and carried out, byte for byte.",
    payloadJson: "The request, as JSON",
    resultJson: "The result, as JSON",
    sha: "Its SHA-256",
    decisions: "Decisions",
    noDecisions: "No one has decided yet.",
    decision: { approve: "approved", reject: "rejected" } as Record<string, string>,
    comment: "Comment",
    commentHelp: "Saved with your decision.",
    approve: "Approve",
    reject: "Reject",
    execute: "Carry it out",
    approved: "Approved",
    rejected: "Rejected",
    executed: "Carried out",
    ownRequest: "You asked for this change, so someone else must approve it.",
    notYours: (checker: string) => `It waits for someone who holds ${checker}.`,
    withdraw: "Withdraw it",
    withdrawn: "Withdrawn",
    result: "Result",
    emptyTitle: "No change request here",
    emptyText: "When a change needs a second person, it waits here.",
  },
  people: {
    title: "People",
    lead: "Staff, their roles and scopes, and how they sign in.",
    columns: {
      name: "Name",
      roles: "Roles",
      mfa: "Two-step",
      lastLogin: "Last sign-in",
      status: "Status",
    },
    statuses: {
      active: "Active",
      inactive: "Switched off",
      breakGlass: "Break-glass",
    } as Record<string, string>,
    mfaOn: "On",
    mfaOff: "Not set up",
    invite: "Invite a staff member",
    inviteTitle: "Invite a staff member",
    inviteText: "They get an email with a link that works once, for 72 hours. Privileged roles need an approval.",
    inviteEmail: "Their work email address",
    inviteRole: "Role",
    inviteSend: "Send the invitation",
    invited: "Invitation sent",
    invites: "Invitations",
    invitesLead: "Waiting, accepted and revoked invitations; the address is masked.",
    noInvites: "No invitation.",
    inviteStates: { waiting: "Waiting", accepted: "Accepted", revoked: "Revoked", expired: "Expired" } as Record<
      string,
      string
    >,
    inviteColumns: { email: "Address", role: "Role", sent: "Sent", expires: "Expires", state: "State" },
    revokeInvite: "Revoke",
    revokeInviteTitle: "Revoke this invitation?",
    revokeInviteText: "Its link stops working at once.",
    inviteRevoked: "Invitation revoked",
    roles: "Roles",
    grant: "Grant a role",
    grantButton: "Grant the role",
    role: "Role",
    expires: "Expires",
    expiresHelp: "Leave empty for a role that stays until it is revoked.",
    grantedBy: (who: string) => `granted by ${who}`,
    noExpiry: "no end date",
    revoke: "Revoke",
    revokeRole: (role: string) => `Revoke ${role}`,
    revokeTitle: (role: string) => `Revoke the ${role} role?`,
    revokeText: "It ends at once: the next request they make no longer has it.",
    granted: "Role granted",
    revoked: "Role revoked",
    noRoles: "No role.",
    scopes: "Scopes",
    scopesLead: "A scope narrows what a role reaches: a subject, a board and class, a warehouse or a queue.",
    noScopes: "No scope: their roles reach every record.",
    scopeKind: "Kind",
    scopeValue: "Value",
    addScope: "Add a scope",
    addScopeButton: "Add the scope",
    scopeAdded: "Scope added",
    scopeRemoved: "Scope removed",
    removeScope: (scope: string) => `Remove the scope ${scope}`,
    scopeKinds: {
      subject: "Subject",
      board_class: "Board and class",
      order_status: "Order status",
      warehouse: "Warehouse",
      school: "School",
      ticket_queue: "Ticket queue",
    } as Record<string, string>,
    sessions: "Sign-in",
    endSessions: "End all their sessions",
    endSessionsTitle: "End all their sessions?",
    endSessionsText: "Every browser and app they are signed in on is signed out at once.",
    sessionsEnded: (sessions: number) => `${plural(sessions, "session", "sessions")} ended`,
    resetMfa: "Reset their two-step sign-in",
    resetMfaText: "For a lost phone or key. An admin or another owner approves it first.",
    offboard: "Offboard",
    offboardTitle: "Offboard this person",
    offboardText:
      "Switches the account off, ends every session, revokes their roles, scopes and API keys, expires their requests and unassigns their work, in one step. It cannot be undone from here.",
    offboardButton: "Offboard them",
    offboarded: "Offboarded",
    accessReview: "Access review",
    accessReviewLead:
      "Everyone's roles, scopes, last sign-in and the action permissions they have not used in 90 days. Change what should change from the person's page.",
    reviewColumns: {
      person: "Person",
      roles: "Roles",
      scopes: "Scopes",
      lastLogin: "Last sign-in",
      unused: "Unused permissions",
      flags: "Flags",
    },
    dormant: "Dormant",
    noMfa: "No two-step",
    emptyTitle: "No staff member",
    emptyText: "Invite someone to start.",
    roleNames: {
      OWNER: "Owner",
      ADMIN: "Admin",
      FINANCE: "Finance",
      SALES: "Sales",
      SALES_REP: "Sales representative",
      PACKER: "Packer",
      SUPPORT: "Support",
      CONTENT_EDITOR: "Content editor",
      REVIEWER: "Reviewer",
      MARKETING: "Marketing",
      AUDITOR: "Auditor",
    } as Record<string, string>,
  },
  users: {
    title: "Customers",
    lead: "Students, parents and teachers. Contact details stay masked unless you reveal them with a reason.",
    columns: {
      name: "Name",
      email: "Email",
      phone: "Mobile",
      class: "Class",
      status: "Status",
      joined: "Joined",
      lastSeen: "Last sign-in",
    },
    classLevel: { "10": "Class 10", "12": "Class 12" } as Record<string, string>,
    board: "Board",
    district: "District",
    activeFilter: "Account",
    activeOptions: { true: "Switched on", false: "Suspended or erased" } as Record<string, string>,
    statuses: {
      active: "Active",
      suspended: "Suspended",
      pending_deletion: "Deletion due",
      erased: "Erased",
    } as Record<string, string>,
    flags: {
      child: "Under 18",
      consent_pending: "Consent pending",
      locked: "Locked",
    } as Record<string, string>,
    recordLogged: "Opening this record is recorded in the audit trail.",
    childLogged: "This is a child's account: opening it is recorded as a look at a child's data.",
    contact: "Contact",
    email: "Email address",
    phone: "Mobile number",
    details: "Details",
    joined: "Joined",
    lastSeen: "Last seen",
    verified: "Verified",
    notVerified: "Not verified",
    mfa: "Two-step sign-in",
    mfaNone: "Not set up",
    consent: "Consent",
    consentStates: {
      adult: "An adult",
      declared: "Declared by the student",
      pending: "Waiting for the parent",
      verified: "Confirmed by the parent",
    } as Record<string, string>,
    teacher: "Teacher access",
    teacherStates: { none: "None", requested: "Asked for", verified: "Verified" } as Record<string, string>,
    parentContact: "Parent's contact",
    deletionDue: "Deletion due",
    roles: "Roles",
    orders: "Latest orders",
    noOrders: "No order.",
    orderColumns: { number: "Order", status: "Status", created: "Placed" },
    consents: "Consent records",
    noConsents: "No consent record.",
    sessions: "Signed-in devices",
    noSessions: "Signed in nowhere.",
    sessionLine: (device: string, ip: string) => `${device} · ${ip}`,
    actions: "Actions",
    actionsLead: "Each one is recorded with your name; the customer is told where the law or our policy asks.",
    action: {
      resendVerification: "Send the email confirmation again",
      passwordReset: "Send a password reset link",
      unlock: "Unlock sign-in",
      endSessions: "Sign them out everywhere",
      suspend: "Suspend the account",
      unsuspend: "Lift the suspension",
      resetMfa: "Reset two-step sign-in",
      impersonate: "Sign in as this customer",
    },
    done: {
      resendVerification: "Link sent",
      passwordReset: "Link sent",
      unlock: "Unlocked",
      endSessions: "Signed out",
      suspend: "Suspended",
      unsuspend: "Suspension lifted",
    },
    suspendTitle: "Suspend this account?",
    suspendText: "They are signed out at once, told by email, and cannot sign in until the suspension is lifted.",
    resetMfaTitle: "Reset their two-step sign-in?",
    resetMfaText:
      "They will sign in with their password alone until they set it up again. Prove who they are first, as strongly as when they set it up. A second person approves it.",
    impersonateTitle: "Sign in to the website as this customer",
    impersonateText:
      "You see the website as they do for 15 minutes. Payments, passwords, email, consent, addresses and deletion stay closed, and they can see that you did it. Never a child's account.",
    impersonateTicket: "Ticket",
    impersonateTicketHelp: "The support ticket or the mail it answers.",
    impersonateReasonHelp: "Why: saved with every page you open as them.",
    impersonateButton: "Start",
    impersonateOpen: "Open the website as them",
    impersonateUntil: (time: string) => `Open until ${time}.`,
    impersonateEnd: "End it now",
    impersonateEnded: "Ended",
    danger: "Danger zone",
    emptyTitle: "No customer matches",
    emptyText: "Search by an email address (exactly), a mobile number, or three letters or more of a name.",
  },
  privacy: {
    requestsTitle: "Data requests",
    requestsLead:
      "Requests to see, correct or erase personal data, nominations, grievances and complaints, with the clocks the law sets.",
    incidentsTitle: "Incidents",
    incidentsLead: "The breach register. CERT-In within 6 hours, the Data Protection Board within 72 hours.",
    processorsTitle: "Processors",
    processorsLead: "Who processes personal data for ExamLeaf, for what, where, and under which contract.",
    kinds: {
      access: "Access",
      correction: "Correction",
      erasure: "Erasure",
      nomination: "Nomination",
      grievance: "Grievance",
      complaint: "Complaint",
    } as Record<string, string>,
    statuses: { new: "New", acknowledged: "Acknowledged", closed: "Closed" } as Record<string, string>,
    outcomes: { done: "Done", refused: "Refused", withdrawn: "Withdrawn" } as Record<string, string>,
    columns: {
      kind: "Kind",
      requester: "Requester",
      channel: "Channel",
      received: "Received",
      ack: "Acknowledge",
      due: "Answer",
      status: "Status",
    },
    overdueFilter: "Late",
    overdueOptions: { true: "Past the answer-by time", false: "In time" } as Record<string, string>,
    ackClock: "Acknowledge within 48 hours",
    dueClock: "Answer by",
    acknowledged: (when: string) => `acknowledged ${when}`,
    reported: (when: string) => `told ${when}`,
    summary: "What they asked",
    account: "Account",
    accountLink: (id: number) => `Customer #${id}`,
    noAccount: "Not linked to an account",
    identity: "Identity",
    verifiedRequester: (when: string) => `Checked ${when}`,
    unverifiedRequester: "Not checked yet",
    verify: "Record the identity check",
    verifyNote: "How it was checked",
    verifyNoteHelp: "The method, not the document: for example, a code sent to the account's own address.",
    verifyButton: "Record the check",
    verified: "Identity check recorded",
    acknowledge: "Acknowledge",
    acknowledgedToast: "Acknowledged",
    assignee: "Handled by",
    notes: "The request's working notes",
    notesHelp: "Notes are personal data too: they go into the requester's own access export.",
    saveNotes: "Save the notes",
    notesSaved: "Notes saved",
    erasure: "Erasure",
    erasureLead:
      "First the dry run: what would be erased and what the law makes us keep. Then the erasure itself, which a second person approves.",
    dryRunButton: "Run the dry run",
    erase: "What would be erased",
    keep: "Kept, and why",
    blocks: "What stops it now",
    nothingKept: "Nothing is kept back.",
    nothingErased: "Nothing would be erased.",
    count: (count: number) => plural(count, "row", "rows"),
    eraseButton: "Erase the account",
    eraseTitle: "Erase this account?",
    eraseText:
      "A change request is made: someone who may approve erasures checks it, and only then is the account erased. What the law keeps stays, as the dry run says.",
    exportTitle: "Send them their data",
    exportText:
      "For an access request with the identity checked: their data goes by email to the account's own address.",
    exportButton: "Email their data",
    response: "The answer",
    responseLead: "The text to send, with the contact block the law asks for. Adapt it, then record it when closing.",
    copyResponse: "Copy the text",
    close: "Close the request",
    closeLead: "Record the outcome and the answer as it was sent.",
    closeOutcome: "Outcome",
    closeResponse: "The answer sent",
    closeButton: "Close it",
    closed: "Closed",
    closedWith: (outcome: string, when: string) => `${outcome}, ${when}`,
    logRequest: "Log a request",
    logTitle: "Log a data request",
    logText:
      "For a request that came by email, phone, letter or in person. The clocks start from when it was received.",
    channel: "How it came",
    channels: {
      email: "Email",
      letter: "Letter",
      phone: "Phone",
      form: "The website's form",
      in_person: "In person",
      board: "Through the Data Protection Board",
    } as Record<string, string>,
    requester: "Requester's email address or mobile number",
    userId: "Customer number",
    userIdHelp: "The account it is about, when known (the number in its address: /users/42/).",
    receivedAt: "Received at",
    logButton: "Log it",
    logged: "Logged",
    incidentNew: "Record an incident",
    incidentTitle: "Record an incident",
    incidentText:
      "Record it as soon as it is noticed: the 6-hour and 72-hour clocks run from when it was detected. Partial facts are fine at first; the owners are told at once.",
    title: "What happened, in a line",
    detectedAt: "Detected at",
    incidentKind: "Kind",
    description: "What is known",
    systems: "Systems involved",
    systemsHelp: "For example: website, database",
    dataCategories: "Kinds of personal data",
    dataCategoriesHelp: "For example: email, name, marks",
    peopleAffected: "People affected (an estimate)",
    childrenAffected: "Children's data involved",
    recordIncident: "Record it",
    incidentRecorded: "Recorded",
    incidentColumns: {
      detected: "Detected",
      title: "Incident",
      kind: "Kind",
      people: "People",
      certin: "CERT-In (6 h)",
      board: "Board (72 h)",
      state: "State",
    },
    incidentStates: { open: "Open", closed: "Closed" } as Record<string, string>,
    openFilter: "State",
    certinClock: "Tell CERT-In",
    boardClock: "Report to the Board",
    certinReportedAt: "CERT-In was told at",
    certinReference: "CERT-In's reference",
    boardNotifiedAt: "The Board was first told at",
    boardReportAt: "The Board's detailed report sent at",
    boardReference: "The Board's reference",
    noticesSent: "Notices sent to people",
    noticesSentAt: "Notices sent at",
    noticeText: "The notice's text",
    incidentActions: "What was done",
    rootCause: "Root cause",
    saveIncident: "Save the incident",
    incidentSaved: "Saved",
    closeIncident: "Close the incident",
    closeIncidentText: "Its clocks stop and it leaves the open register. Record the reports first.",
    incidentClosed: "Closed",
    incidentKinds: {
      data_breach: "Data breach",
      data_leak: "Data leak",
      unauthorised_access: "Unauthorised access",
      malicious_code: "Malicious code",
      application_attack: "Attack on the application",
      denial_of_service: "Denial of service",
      loss_of_access: "Loss of access to data",
      other: "Other",
    } as Record<string, string>,
    children: "Children affected",
    processorNew: "Add a processor",
    processorTitle: "Add a processor",
    processorName: "Name",
    processorPurpose: "What they do for us",
    processorCountry: "Country or region where the data is kept",
    processorCategories: "Kinds of personal data",
    processorSigned: "Agreement signed on",
    processorContract: "Agreement ends on",
    processorAdd: "Add it",
    processorAdded: "Added",
    processorColumns: {
      name: "Name",
      purpose: "Purpose",
      country: "Where",
      categories: "Data",
      contract: "Agreement ends",
      active: "In use",
    },
    emptyRequestsTitle: "No data request",
    emptyRequestsText: "When someone asks about their data, the request and its clocks show here.",
    emptyIncidentsTitle: "No incident recorded",
    emptyIncidentsText: "Record one as soon as something is noticed: the clocks start at detection.",
    emptyProcessorsTitle: "No processor listed",
    emptyProcessorsText: "List everyone who processes personal data for ExamLeaf.",
  },
  settings: {
    title: "Settings",
    lead: "The site's settings and feature flags: where each value comes from, its history, and who changed it.",
    site: "Site settings",
    flags: "Feature flags",
    columns: { key: "Setting", value: "Value", source: "Source", effective: "From", changedBy: "Changed by" },
    sources: { environment: "Environment", database: "Console" } as Record<string, string>,
    environmentValue: (value: string) => `The environment's value: ${value}.`,
    scheduled: (value: string, when: string) => `${value} from ${when}`,
    staffMember: (id: number) => `staff #${id}`,
    change: "Change",
    changeTitle: (key: string) => `Change ${key}`,
    value: "New value",
    backToEnvironment: "Back to the environment's value",
    effectiveFrom: "Takes effect from",
    effectiveHelp: "Leave empty for at once.",
    saveChange: "Save the change",
    changed: "Saved",
    history: "History",
    historyFailed: "The history could not be read.",
    noHistory: "No change recorded.",
    historyEntry: (who: string, when: string) => `${who}, ${when}`,
    emptyTitle: "No setting to show",
    emptyText: "Settings appear here once the server lists them.",
    trueValue: "On",
    falseValue: "Off",
    emptyValue: "(empty)",
  },
  apiKeys: {
    title: "API keys",
    lead: "Keys for integrations, one per integration, each with its scopes, an end date and a person who answers for it.",
    columns: {
      name: "Name",
      prefix: "Starts with",
      scopes: "Scopes",
      created: "Made",
      expires: "Ends",
      lastUsed: "Last used",
      sponsor: "Answers for it",
      status: "Status",
    },
    statuses: { active: "Active", revoked: "Revoked", expired: "Ended" } as Record<string, string>,
    create: "Make a key",
    createTitle: "Make an API key",
    createText: "The secret is shown once, when it is made. Store it in the integration's settings straight away.",
    name: "Name",
    nameHelp: "What it is for, for example: Shiprocket sync",
    scopes: "Permissions",
    scopesHelp: "View permissions only, comma separated, for example: staff.view_system",
    allowedIps: "From these addresses only",
    allowedIpsHelp: "Optional: addresses or networks, comma separated, for example 203.0.113.0/24",
    expires: "Ends on",
    expiresHelp: "At most 12 months from today; empty: 12 months.",
    lastUsedFrom: (ip: string) => `from ${ip}`,
    createButton: "Make the key",
    secretTitle: "Copy the secret now",
    secretText: "It is never shown again. If it is lost, revoke the key and make a new one.",
    secretStored: "I have stored it",
    revoke: "Revoke",
    revokeTitle: (name: string) => `Revoke ${name}?`,
    revokeText: "Every request with this key is refused from now on. It cannot be undone.",
    revoked: "Revoked",
    emptyTitle: "No API key yet",
    emptyText: "Make one for each integration that needs to call ExamLeaf.",
  },
  system: {
    title: "System",
    lead: "Health checks, queues, webhooks, email and SMS, backups, the audit chain and maintenance mode.",
    health: "Health",
    healthy: "Passing",
    failing: "Failing",
    queues: "Queues",
    queue: "Queue",
    waiting: "Waiting",
    eager: "Tasks run at once here (no broker).",
    brokerDown: (error: string) => `The broker cannot be reached: ${error}`,
    failedTasks: (count: number) => `${plural(count, "failed task", "failed tasks")} in 7 days`,
    webhooks: "Webhooks",
    webhooksDay: "Received in the last day",
    webhooksRefused: (count: number) => `${plural(count, "webhook", "webhooks")} refused in 7 days (wrong signature)`,
    noWebhooks: "None in the last day.",
    email: "Email",
    suppressed: "Addresses suppressed",
    suppressedWeek: "Suppressed in 7 days",
    sms: "SMS in the last day",
    noSms: "No SMS in the last day.",
    backups: "Backups",
    backupsOff: "No backup bucket is set up.",
    backupError: (error: string) => `The bucket cannot be read: ${error}`,
    lastBackup: "Last backup",
    backupSize: "Size",
    noBackup: "No backup has run.",
    audit: "Audit chain",
    auditVerified: (when: string) => `Verified intact ${when}`,
    auditBroken: (when: string) => `A break found ${when}: see the inbox`,
    auditNever: "Not verified yet (nightly at 02:00).",
    reconcile: "A stuck online payment",
    reconcileLead: "Ask Razorpay what became of an order's payment (a webhook that never came).",
    reconcileOrder: "Order number",
    reconcileButton: "Ask Razorpay",
    reconciled: (order: string, paid: boolean | null) =>
      paid === null ? `${order}: Razorpay could not say.` : paid ? `${order} is paid.` : `${order} is not paid.`,
    maintenance: "Maintenance mode",
    maintenanceOn: "On: visitors see the banner and changes are closed. The console stays open.",
    maintenanceOff: "Off: the site is open.",
    banner: "Banner shown to visitors",
    turnOn: "Turn maintenance mode on",
    turnOff: "Turn maintenance mode off",
    maintenanceSaved: "Saved",
    emptyTitle: "Nothing to show",
  },
  account: {
    title: "My account",
    lead: "Where you are signed in, and how to leave.",
    you: "You",
    roles: "Your roles",
    roleUntil: (when: string) => `until ${when}`,
    sessions: "Signed-in devices",
    sessionsLead: "Every browser and app signed in to your account, on the website and here.",
    thisDevice: "this device",
    since: (when: string) => `since ${when}`,
    lastSeen: (when: string) => `last seen ${when}`,
    now: "now",
    signOutDevice: "Sign out",
    signOutDeviceName: (name: string) => `Sign out ${name}`,
    signedOutDevice: "Signed out",
    signOutEverywhere: "Sign out everywhere",
    signOutEverywhereText: "Ends every session of your account, this one too.",
    sessionsFailed: "The list of devices could not be read.",
    addressUnknown: "address unknown",
    aBrowser: "A browser",
    on: (browser: string, system: string) => `${browser} on ${system}`,
    security: "Two-step sign-in and passkeys",
    securityText: "Change them on your ExamLeaf account page.",
    securityLink: "Open the account page",
    limits: "Your limits",
    limitsLead: "Above them, what you ask for waits for a second person. The backend sets them by role.",
    limitNames: {
      refund_inr: "Refunds, in rupees",
      offline_inr: "Payments recorded offline, in rupees",
      discount_percent: "Discount off the MRP, per cent",
      export_rows: "Rows exported at once",
      bulk_rows: "Rows of a bulk action",
    } as Record<string, string>,
    noLimit: "No limit",
  },
  notes: {
    side: "Notes and audit trail",
    title: "Notes",
    lead: "For colleagues: what was said, what was promised. Notes are personal data too and go into access exports.",
    none: "No note yet.",
    add: "Add a note",
    body: "Note",
    save: "Save the note",
    saved: "Note saved",
    by: (who: string, when: string) => `${who}, ${when}`,
  },
  soon: {
    title: (module: string) => `${module} comes in the next phase`,
    text: "This module is planned and not built yet. Until it is, the Django admin does this work.",
    /** Where a module's work is done today when the Django admin does not do it. */
    today: {
      insights:
        "This module is planned and not built yet. The nightly forecasts, print runs and signals are computed already; the Django admin shows their runs until then.",
    } as Record<string, string>,
    admin: "Open the Django admin",
    eyebrow: "Coming next",
  },
  problem: {
    noAccessTitle: "No access",
    unavailableTitle: "Not available just now",
    badResponseTitle: "Could not be read",
    throttledTitle: "Too many requests",
    failedTitle: "Something went wrong",
  },
  states: {
    active: "Active",
    inactive: "Inactive",
    yes: "Yes",
    no: "No",
  },
  tax: {
    title: "Tax",
    lead: "What is due this month, how the year's turnover stands against GST's thresholds, and the documents issued.",
    tabs: {
      overview: "Overview",
      hsn: "HSN and SAC codes",
      documents: "Documents",
      series: "Series",
      gstr1: "GSTR-1",
    },
    tabsLabel: "Tax",
    // the calendar
    due: "Due this month",
    dueLead: "The law's own dates: an extension comes by notification, so check the GST portal near a date.",
    qrmp: "Quarterly returns (QRMP)",
    monthly: "Monthly returns",
    qrmpNote: "Settings switch QRMP on or off (SHOP_GST_QRMP).",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    covers: (what: string) => `For ${what}`,
    past: "Past",
    notRequired: "Not required",
    nothingDue: "Nothing falls due this month.",
    monthOf: (month: string) => `Due in ${month}`,
    // the thresholds
    thresholds: "Thresholds",
    thresholdsLead:
      "The financial year's turnover so far against the lines GST draws, as the last night's look found it.",
    asOf: (night: string, year: string) => `As of the night of ${night}, financial year ${year}.`,
    notYet: "The monitor has not looked yet: it looks every night at 01:45.",
    thresholdColumns: { line: "Line", value: "So far", limit: "Line at", state: "State" },
    crossed: "Crossed",
    notCrossed: "Not crossed",
    documentsCount: (count: number) => plural(count, "document", "documents"),
    previousTurnover: (year: string) => `Turnover of FY ${year}`,
    hsnDigits: "HSN digits on documents",
    returns: "Returns",
    crossedThisYear: "Crossed this year",
    // the series
    seriesThisYear: "Series this year",
    seriesLead:
      "Table 13 of GSTR-1: each series' first and last number, how many, how many cancelled. A number is never given twice.",
    openSeries: "Open table 13",
    seriesColumns: {
      series: "Series",
      nature: "Nature",
      first: "From",
      last: "To",
      total: "Issued",
      cancelled: "Cancelled",
      next: "Next serial",
    },
    seriesEmpty: "No document of the real series in this period.",
    seriesFrom: (year: string, prefixes: string) =>
      `From FY ${year} each type has a series of its own: ${prefixes}. Until then EL holds every invoice and CN the credit notes.`,
    year: "Financial year",
    month: "Month",
    wholeYear: "The whole year",
    // the master
    hsnTitle: "HSN and SAC codes",
    hsnLead:
      "The master the GST on every order comes from: each code's rate on the day of the order, never typed on a product.",
    addCode: "Add a code",
    addCodeLead: "A code new to the master, with its first rate and the notification that sets it.",
    hsnColumns: {
      code: "Code",
      kind: "Kind",
      description: "Description",
      today: "Rate today",
      next: "Next change",
      products: "Products",
    },
    kinds: { hsn: "HSN (goods)", sac: "SAC (services)" } as Record<string, string>,
    taxability: { taxable: "Taxable", nil: "Nil-rated", exempt: "Exempt", non_gst: "Non-GST" } as Record<
      string,
      string
    >,
    rate: (rate: string) => `${rate} %`,
    rateOn: (rate: string, taxability: string, from: string) => `${rate} % (${taxability}) from ${from}`,
    noRate: "No rate today",
    noChange: "None set",
    hsnEmptyTitle: "The master is empty",
    hsnEmptyText: "Its codes are seeded when the server is migrated: ask an administrator.",
    search: "Search the codes",
    problems: "Products that disagree",
    problemsLead: "Their GST rate or code is not what the master gives for today: correct the product or the master.",
    problemsNone: "Every product on sale agrees with the master today.",
    problemColumns: { product: "Product", code: "Code", rate: "Rate here", problem: "Why" },
    // one code
    unit: "Unit (UQC)",
    description: "Description",
    kind: "Kind",
    today: "Today",
    nextChange: "Next change",
    rates: "Rates",
    ratesLead: "The code's history, oldest first. A rate runs until its end, or until the next one starts.",
    rateColumns: {
      from: "From",
      until: "Until",
      rate: "Rate",
      taxability: "Taxability",
      notification: "Notification",
      serial: "Serial",
      note: "Note",
    },
    openEnded: "now",
    productsOn: "Products on this code",
    productsOnEmpty: "No product points to this code.",
    agrees: "Agrees",
    disagrees: "Disagrees",
    newRate: "A new dated rate",
    newRateLead:
      "When a notification changes the rate: it starts after the latest one, and orders from that day are taxed at it. Older documents keep theirs.",
    fields: {
      code: "Code",
      kind: "Kind",
      description: "Description",
      uqc: "Unit (UQC)",
      uqcHelp: "NOS for books, NA for services: as the CA confirms.",
      rate: "Rate (%)",
      taxability: "Taxability",
      taxabilityHelp: "A taxable rate is above 0; nil-rated, exempt and non-GST supplies are at 0.",
      effective_from: "From",
      effective_to: "Until",
      effectiveToHelp: "Leave it empty: the rate runs until the next one starts.",
      notification: "Notification",
      notificationHelp: "As CBIC numbers it: 10/2025-Central Tax (Rate).",
      serial: "Serial number",
      note: "Note",
      noteHelp: "Where it was read; what the CA should confirm.",
    },
    saveRate: "Add the rate",
    rateAdded: "Rate added",
    saveCode: "Add the code",
    codeAdded: "Code added",
    // documents
    documentsTitle: "Documents",
    documentsLead:
      "The storefront's invoices and credit notes in their series, newest first. A cancelled one keeps its number.",
    documentColumns: {
      number: "Number",
      type: "Type",
      date: "Date",
      order: "Order",
      place: "Place of supply",
      total: "Total",
      taxable: "Taxable value",
      gst: "GST",
      state: "State",
    },
    documentKinds: { invoice: "Invoices", credit_note: "Credit notes" } as Record<string, string>,
    documentKind: "Documents",
    types: {
      tax_invoice: "Tax invoice",
      bill_of_supply: "Bill of supply",
      invoice_cum_bill_of_supply: "Invoice-cum-bill of supply",
    } as Record<string, string>,
    creditNote: "Credit note",
    seriesFilter: "Series",
    cancelledFilter: "Cancelled",
    cancelledOptions: { true: "Cancelled", false: "Not cancelled" } as Record<string, string>,
    testFilter: "Which series",
    testOptions: { false: "The real series", true: "The test series (not tax documents)" } as Record<string, string>,
    searchDocuments: "Search by number or order",
    documentsEmptyTitle: "No document yet",
    documentsEmptyText: "An invoice is made when an order is paid (cash on delivery: when it ships).",
    issued: "Issued",
    cancelled: "Cancelled",
    test: "Test",
    // one document
    against: "Against",
    order: "Order",
    date: "Date",
    place: "Place of supply",
    total: "Total",
    taxable: "Taxable value",
    exempt: "Exempt and nil-rated value",
    gst: "GST",
    cancelledAt: "Cancelled",
    cancelReason: "Why",
    pdf: "Download the PDF",
    pdfNote: "The PDF names the buyer: opening it is recorded.",
    noPdf: "Its PDF is being made.",
    checks: "What Rule 46 asks that it misses",
    lines: "Lines",
    lineColumns: {
      item: "Item",
      code: "HSN/SAC",
      quantity: "Qty",
      rate: "Rate",
      amount: "Amount",
      taxable: "Taxable",
      gst: "GST",
    },
    partOf: (bundle: string) => `part of ${bundle}`,
    charges: "Shipping",
    chargesLead: "It follows the goods it carries: shared over them by their value and taxed with each.",
    chargeLine: (label: string, rate: string) => `${label} at ${rate} %`,
    roundOff: "Round off",
    creditNotes: "Credit notes",
    noCreditNotes: "None against it.",
    cancel: "Cancel the document",
    cancelTitle: "Cancel this document?",
    cancelText:
      "It keeps its number, table 13 counts it cancelled and it leaves the returns; its PDF is marked cancelled. The order and its refunds are not changed. Cancel an invoice's credit notes first. A document already in a filed GSTR-1 is corrected by a credit note instead.",
    cancelButton: "Cancel it",
    cancelRow: "Cancel the document",
    cancelRowText: "It keeps its number. This cannot be undone.",
    cancelledToast: "Document cancelled",
    reasonHelp: "Kept with the document and in the audit trail.",
    // GSTR-1
    gstr1Title: "GSTR-1",
    gstr1Lead:
      "The month's (or the quarter's) GSTR-1 files for the accountant, in the GST Offline Tool's CSV templates, zipped.",
    gstr1Run: "Run the export",
    gstr1Period: "Period",
    gstr1Month: "The month",
    gstr1Quarter: "The quarter ending with this month",
    gstr1QuarterHelp: "Under QRMP, GSTR-1 is quarterly: choose June, September, December or March.",
    gstr1DryRun: "Only count the documents",
    dryRun: "Count only",
    gstr1Started: "Export started",
    gstr1Files:
      "b2cl, b2cs, cdnur, exemp, hsn-b2b, hsn-b2c and docs in the Offline Tool's templates, and the credit notes' register. The test series is never in them.",
    gstr1Recent: "Your recent exports",
    gstr1None: "You have run no GSTR-1 export.",
    period: (from: string, to: string) => `${from} to ${to}`,
  },
  legal: {
    // the cockpit (/privacy/)
    cockpitTitle: "Legal and privacy",
    cockpitLead:
      "Every clock the rules start, with the record behind it; the consents by the notice's version; the dark-pattern self-audit; the legal calendar.",
    clocks: "Clocks running",
    clocksLead: "The late first, then by when each is due. Each opens its record.",
    noClocks: "No clock is running.",
    clockColumns: { what: "What", rule: "The rule", due: "Due" },
    clockKinds: {
      data_request_ack: "Data requests to acknowledge",
      data_request_answer: "Data requests to answer",
      incident_cert_in: "Incidents to report to CERT-In",
      incident_board: "Incidents to report to the Board",
      complaint_ack: "Complaints to acknowledge",
      complaint_redress: "Complaints to redress",
      complaint_nch: "NCH complaints to answer",
      parent_consent: "Parents' consents awaited",
      deletion_parent: "Children's deletions waiting for the parent",
      dark_pattern_audit: "The dark-pattern self-audit",
    } as Record<string, string>,
    counted: (open: number, overdue: number) =>
      Number(overdue) > 0
        ? `${open.toLocaleString("en-IN")} open, ${overdue.toLocaleString("en-IN")} late`
        : `${open.toLocaleString("en-IN")} open`,
    countsLabel: "Clocks by kind",
    awaited: "Awaited: the law sets no end",
    supportMissing: "The complaints' clocks show here once the support app is installed.",
    parentConfirm: "Record the parent's confirmation",
    parentConfirmTitle: "Record the parent's confirmation?",
    parentConfirmText:
      "For a parent or guardian who confirmed the child's deletion by phone or letter. The account is erased at the next nightly run once it is due.",
    evidence: "Where the evidence is",
    evidenceHelp: "A ticket's number or a letter's date: never the document itself.",
    parentConfirmed: "Confirmation recorded",
    tasks: (count: number) =>
      `${plural(count, "task", "tasks")} for the processors and the compliance duties in the inbox`,
    calendar: "The legal calendar",
    calendarLead: "The dates the rules start, and the duties that come round.",
    calendarStates: {
      upcoming: "Coming",
      in_force: "In force",
      done: "Done",
      overdue: "Late",
    } as Record<string, string>,
    consents: "Consents by the privacy notice's version",
    consentsLead: "How many gave and withdrew their consent under each version of the privacy notice.",
    consentColumns: { version: "Version", given: "Given", withdrawn: "Withdrawn" },
    consentVersion: (version: string, number: number | null) => (number ? `Version ${number} (${version})` : version),
    inForce: "in force",
    noConsents: "No consent recorded yet.",
    registers: "The registers",
    registersLead: "The other pages of this module.",
    // the dark-pattern self-audit
    darkTitle: "Dark-pattern self-audit",
    darkLead:
      "Once a year, each of the 13 patterns the 2023 guidelines name: what was found and what was fixed, then the certificate, shown on the website from its day.",
    darkYear: (year: number) => `The self-audit for ${year}`,
    darkStates: {
      missing: "Not started",
      draft: "In progress",
      completed: "Completed",
    } as Record<string, string>,
    darkDue: (year: number, day: string) => `Due by ${day}: the certificate for ${year} on the website.`,
    darkShown: (year: number) => `The certificate for ${year} is on the website now.`,
    darkNoneShown: "No certificate is on the website yet.",
    darkOpen: "Open the self-audit",
    darkYears: "Years",
    darkStart: (year: number) => `Start the self-audit for ${year}`,
    darkStarted: "Started",
    darkMissingText: "No self-audit for this year yet.",
    darkNoAudits: "No self-audit yet.",
    darkPattern: "Pattern",
    finding: "What was found",
    findingHelp: "Where it could appear on the website or the app, and what the check showed.",
    fix: "What was fixed or ruled out",
    certificateText: "The certificate's text",
    certificateHelp: "As signed: shown on the website from its day.",
    effectiveFrom: "Shown on the website from",
    effectiveHelp: "Empty: from the day it is completed.",
    saveAudit: "Save the self-audit",
    auditSaved: "Saved",
    complete: "Complete and sign",
    completeTitle: (year: number) => `Complete the self-audit for ${year}?`,
    completeText:
      "It is kept as it is from now on, and its certificate is shown on the website from its day. Save the last changes first.",
    completed: "Completed",
    completedOn: (when: string, who: string) => `Completed ${when} by ${who}.`,
    shownFrom: (day: string) => `Shown on the website from ${day}.`,
    signedCopy: "The signed copy",
    signedCopyNone: "No signed copy is kept yet.",
    download: "Download the signed copy",
    upload: "Keep the signed copy",
    uploadLabel: "The signed certificate (PDF, PNG or JPEG, 5 MB at most)",
    uploaded: "Copy kept",
    // legal holds
    holdsTitle: "Legal holds",
    holdsLead:
      "A hold keeps an account or a record from the erasure and the retention clean-up until its day or its release: a dispute, a chargeback, a legal claim, an investigation.",
    holdColumns: { hold: "Hold", reason: "Reason", until: "Until", made: "Made", state: "State" },
    holdReasons: {
      dispute: "A dispute",
      chargeback: "A chargeback",
      claim: "A legal claim",
      investigation: "An investigation",
      other: "Another reason",
    } as Record<string, string>,
    holdStates: { active: "In force", released: "Released", ended: "Ended" } as Record<string, string>,
    activeFilter: "State",
    activeOptions: { true: "In force", false: "Released or ended" } as Record<string, string>,
    targetFilter: "Kind of record",
    targets: {
      "": "An account",
      "shop.order": "An order",
      "shop.invoice": "An invoice",
      "shop.creditnote": "A credit note",
      "shop.payment": "A payment",
      "shop.refund": "A refund",
      "staff.datarequest": "A data request",
    } as Record<string, string>,
    userFilter: "Customer number",
    untilReleased: "Until released",
    holdNumber: (id: number) => `Hold ${id}`,
    holdNew: "Add a hold",
    holdNewLead:
      "On an account, or on one record. It holds from now; the erasure's dry run and the nightly clean-up name it.",
    holdKind: "What it holds",
    holdUser: "The customer's number",
    holdUserHelp: "The number in the customer's address: /users/42/.",
    holdTarget: "The record's number",
    holdTargetHelp: "An order's, an invoice's or a credit note's number (EL-2026-000123), or the record's id.",
    holdReason: "Why",
    holdNote: "Note",
    holdNoteHelp: "What it is about: a case number, the other side. No personal details.",
    holdUntil: "Holds until",
    holdUntilHelp: "The last day it holds. Empty: until someone releases it.",
    holdCreate: "Add the hold",
    holdCreated: "Hold added",
    holdAccount: (id: number) => `Customer #${id}`,
    holdMadeBy: (when: string, who: string) => `${when}, by ${who}`,
    holdReleased: (when: string, who: string) => `Released ${when} by ${who}`,
    release: "Release the hold",
    releaseText: "The record is no longer kept for it: the erasure and the clean-up may go ahead.",
    releaseTitle: "Release this hold?",
    released: "Released",
    holdsEmptyTitle: "No legal hold",
    holdsEmptyText: "A hold keeps an account or a record while a dispute or a claim runs.",
    // retention
    retentionTitle: "Retention",
    retentionLead:
      "How long each kind of record is kept: the law's minimum today and when it changes, what this site keeps, and what deletes it.",
    retentionColumns: { records: "Records", minimum: "The law's minimum", keep: "What we keep", by: "Deleted by" },
    changesOn: (day: string, next: string) => `From ${day}: ${next}.`,
    trimmed: (days: number) => `Trimmed after ${plural(days, "day", "days")}.`,
    // policy versions
    policiesTitle: "Policy versions",
    policiesLead:
      "The legal pages, each version numbered with the day it is in force from and a line on what it changed. Consents name the version they were given under.",
    policyColumns: {
      page: "Page",
      version: "In force",
      summary: "What it changed",
      scheduled: "Next",
      fill: "To fill in",
    },
    policyVersion: (number: number) => `Version ${number}`,
    policyFrom: (number: number, day: string) => `Version ${number}, from ${day}`,
    placeholders: (count: number) => plural(count, "placeholder", "placeholders"),
    noneScheduled: "None",
    scheduledLine: (number: number, day: string) => `Version ${number} comes into force on ${day}.`,
    cancelScheduled: "Cancel it",
    cancelScheduledTitle: "Cancel the version waiting for its day?",
    cancelScheduledText: "It is never put in force. The version in force stays as it is.",
    scheduleCancelled: "Cancelled",
    inForceFacts: "In force",
    updated: "Last changed",
    versions: "Versions",
    versionsLead: "Newest first. Each opens its changes against the one before.",
    versionLine: (day: string) => `in force from ${day}`,
    versionUpcoming: (day: string) => `comes into force on ${day}`,
    versionPublished: (when: string, who: string) => `published ${when} by ${who}`,
    showChanges: "Show the changes",
    changes: (number: number, previous: number | null) =>
      previous ? `Version ${number} against version ${previous}` : `Version ${number}, the first`,
    changesCount: (added: number, removed: number) =>
      `${plural(added, "line", "lines")} added, ${plural(removed, "line", "lines")} removed`,
    titleChanged: "The title changed too.",
    added: "Added:",
    removed: "Removed:",
    noChanges: "No line changed.",
    publish: "Publish a new version",
    publishLead:
      "In force today, or from a later day (it waits until then). Each version is numbered and kept; the website shows its number and day.",
    publishTitle: "Title",
    publishSummary: "What this version changes, in a line",
    publishSummaryHelp: "Shown with the version on the website's list of versions.",
    publishFrom: "In force from",
    publishFromHelp: "Today or a later day: a version is never backdated.",
    publishText: "The text, in Markdown",
    publishButton: "Publish the version",
    published: "Published",
    // disclosures
    disclosuresTitle: "Disclosures",
    disclosuresLead:
      "What the E-Commerce Rules and the DPDP Rules ask the website to say: who we are, customer care, the Grievance Officer, how to make a request about one's data. Saved together, with one reason.",
    disclosuresForm: "The disclosures",
    source: { environment: "From the environment", database: "Set here" } as Record<string, string>,
    publicField: "On the website",
    privateField: "Never on the website",
    environmentValue: (value: string) => `The environment's value: ${value}`,
    choices: {
      not_joined: "Not joined",
      applied: "Applied",
      member: "A member",
      refunds: "Refunds and cancellations",
      shipping: "Shipping and delivery",
      terms: "Terms and conditions",
    } as Record<string, string>,
    unsaved: (count: number) => `${plural(count, "change", "changes")} not saved`,
    saveChanges: "Save the changes",
    discard: "Undo the changes",
    disclosuresSaved: "Saved",
    history: "History",
    historyLead: "The last 100 changes to the disclosures, newest first.",
    historyLine: (who: string, when: string) => `${who}, ${when}`,
    noHistory: "Nothing changed here yet: every value is the environment's.",
    emptyValue: "(empty)",
    leaveWarning: "The changes are not saved.",
    // a customer's nominee
    nominee: "Nominee",
    nomineeLead: "Who acts for them in case of their death or incapacity (DPDP s.14). Opening it is recorded.",
    noNominee: "No nominee recorded.",
    nomineeName: "Name",
    nomineeRelation: "Relation",
    nomineeContact: "Contact",
    nomineeContactWhat: "nominee's contact",
    nomineeRecorded: "Recorded",
    nomineeVerified: "Proved at a claim",
    notVerified: "Not yet",
    // the erasure's dry run
    keptLine: "Kept",
  },
  orders: {
    title: "Orders",
    lead: "Every order: online, cash on delivery and staff orders. Customers stay masked; a search for a person is recorded.",
    nav: {
      label: "Orders",
      all: "All orders",
      packing: "Packing queue",
      returns: "Returns",
      quotes: "Quotes",
      new: "New order",
    },
    tabs: {
      label: "Show",
      all: "All",
      to_pack: "To pack",
      shipped: "Shipped",
      returns: "Returns",
      cancelled: "Cancelled",
      drafts: "Drafts",
    } as Record<string, string>,
    columns: {
      number: "Order",
      placed: "Placed",
      customer: "Customer",
      items: "Books",
      total: "Total",
      status: "Status",
      payment: "Payment",
      courier: "Courier",
      tags: "Tags",
    },
    filters: {
      search: "Search orders",
      status: "Status",
      method: "Payment",
      risk: "COD risk",
      hold: "Hold",
      mode: "Mode",
      courier: "Courier",
      tag: "Tag",
      parcel: "Parcel",
      from: "Placed from",
      to: "Placed to",
    },
    holdOptions: { true: "On hold", false: "Not on hold" } as Record<string, string>,
    modeOptions: { true: "Live orders", false: "Test orders" } as Record<string, string>,
    modeAny: "Live, or all on a test site",
    noParcel: "No parcel",
    statuses: {
      pending: "Awaiting payment",
      paid: "Paid",
      packed: "Packed",
      shipped: "Sent",
      delivered: "Delivered",
      cancelled: "Cancelled",
      refunded: "Refunded",
    } as Record<string, string>,
    methods: { razorpay: "Online", cod: "Cash on delivery", offline: "Bank transfer or UPI" } as Record<string, string>,
    risks: { low: "Low risk", medium: "Medium risk", high: "High risk" } as Record<string, string>,
    parcels: {
      booked: "Booked",
      pickup_problem: "Pickup problem",
      in_transit: "In transit",
      out_for_delivery: "Out for delivery",
      delivered: "Delivered",
      delivery_failed: "Delivery failed",
      returning: "Coming back",
      returned: "Back with us",
      lost_or_damaged: "Lost or damaged",
      cancelled: "Cancelled",
      partial: "Partly delivered",
    } as Record<string, string>,
    badges: {
      cod: "COD",
      held: "On hold",
      test: "Test",
      staff: "Staff order",
      returns: "Return",
      child: "Under 18",
    },
    emptyTitle: "No orders yet",
    emptyText: "Orders placed on the website and made by staff show here.",
    guest: "A guest",
    // the list's bulk bar
    select: {
      row: (number: string) => `Select order ${number}`,
      page: "Select every order on this page",
      selected: (count: number) => `${plural(count, "order", "orders")} selected`,
      clear: "Clear the selection",
    },
    bulk: {
      label: "With the selected orders",
      pack: "Mark packed",
      packing: (count: number, seconds: number) =>
        `Marking ${plural(count, "order", "orders")} packed in ${seconds} s.`,
      undo: "Undo",
      undone: "Not marked",
      packed: "Marked packed",
      print: "Print",
      printTitle: "Print the selected orders",
      printText: "One PDF of their documents, made in the background.",
      printWhat: "What to print",
      documents: {
        packing_slip: "Packing slips (A4)",
        label: "Labels for parcels sent by hand (4×6)",
        invoices: "Invoices",
      } as Record<string, string>,
      printStart: "Make the PDF",
      cancel: "Cancel orders",
      cancelTitle: (count: number) => `Cancel ${plural(count, "order", "orders")}?`,
      cancelText:
        "Each is cancelled before it leaves: its copies go back into stock and the customer is told. One paid online goes through its refund's approval. Orders already sent are refused, one by one.",
      cancelMax: "At most 250 orders are cancelled at once: choose fewer.",
      cancelReasonHelp: "Told to each customer, and kept in the audit trail.",
      cancelStart: "Cancel them",
      export: "Export",
      exportTitle: "Export the list",
      exportText:
        "The list's filters (not a search) as a CSV file: a line per book with the GST split. Made in the background; above your limit an approver passes it first.",
      exportStart: "Export",
      progress: "Progress",
      started: "Started",
    },
    peek: {
      title: (number: string) => `Order ${number}`,
      open: "Open the order",
      loading: "Reading the order…",
      hint: "Press Space on a row to look at the order here.",
    },
    // the record
    eyebrow: "Order",
    recordLogged: "A child's order: opening it is recorded as a look at a child's data.",
    testOrder: "A test order: made with test keys. It stays out of the lists, counts and the packing queue.",
    sections: {
      lines: "Books",
      payments: "Payments",
      refunds: "Refunds",
      documents: "Invoice and credit notes",
      parcels: "Parcels",
      customer: "Customer",
      risk: "Cash-on-delivery risk",
      hold: "Hold",
      tags: "Tags",
      returns: "Returns",
      erp: "In ERPNext",
      timeline: "Timeline",
      actions: "Actions",
    },
    actionsLead: "Each is recorded with your name. The customer is told where the order's messages say so.",
    lineColumns: {
      title: "Book",
      isbn: "ISBN",
      hsn: "HSN",
      gst: "GST",
      copies: "Copies",
      price: "Price",
      discount: "Discount",
      invoiced: "Invoiced",
      refunded: "Refunded",
    },
    totals: {
      subtotal: "Books",
      discount: "Discounts",
      shipping: "Shipping",
      total: "Total",
      coupon: "Coupon",
      createdBy: "Made by",
      quote: "From quotation",
      placed: "Placed",
      created: "Created",
    },
    paymentColumns: {
      method: "How",
      amount: "Amount",
      status: "State",
      reference: "Reference",
      date: "Date",
      left: "Left to refund",
    },
    paymentStatuses: {
      created: "Started",
      authorized: "Authorised",
      captured: "Received",
      failed: "Failed",
      refunded: "Refunded",
    } as Record<string, string>,
    older: "Older than 6 months",
    refundMethods: {
      source: "To where it came from",
      bank: "By bank or UPI transfer",
      none: "No money: the invoice credited",
    } as Record<string, string>,
    refundStatuses: { pending: "Waiting", processed: "Made", failed: "Failed" } as Record<string, string>,
    refundColumns: {
      amount: "Amount",
      method: "How",
      status: "State",
      to: "To",
      reference: "Reference",
      note: "Credit note",
      asked: "Asked",
    },
    noRefunds: "No refund.",
    noPayments: "No payment yet.",
    markPaid: "Mark paid",
    markPaidTitle: "Mark the transfer made?",
    markPaidText:
      "The refund is marked made, the customer is told with the reference, and the credit note follows. Do this once the bank shows the transfer.",
    utr: "UTR or UPI reference",
    utrHelp: "As the bank statement shows it.",
    paid: "Marked paid",
    showPayee: "Show the account",
    showPayeeTitle: "Show the customer's account?",
    showPayeeText: "Revealing it is recorded with your reason. Use it for this transfer only.",
    payeeShown: (account: string) => `Pay to: ${account}`,
    documents: {
      invoice: "Invoice",
      credit_note: "Credit note",
      notReady: "Being made",
      none: "No invoice yet.",
      regenerate: "Make missing documents",
      regenerated: "Being made",
      resend: "Email the invoice again",
      resent: "Invoice sent",
    } as Record<string, string>,
    parcelColumns: { courier: "Courier", tracking: "Tracking", state: "State", last: "Last scan", sent: "Sent" },
    noParcels: "Nothing sent yet.",
    download: "Download",
    customer: {
      name: "Name",
      email: "Email",
      phone: "Mobile",
      address: "Delivery address",
      account: "Open the customer",
      guest: "A guest: no account.",
    },
    risk: {
      bucket: "Score",
      reasons: "Why",
      none: "Not scored: only cash-on-delivery orders are.",
    },
    hold: {
      none: "Not on hold.",
      by: (who: string, when: string) => `Held by ${who} on ${when}.`,
      hold: "Hold it",
      holdTitle: "Hold this order?",
      holdText: "It leaves the packing queue until someone releases it.",
      held: "Order held",
      release: "Release it",
      released: "Released",
    },
    tags: {
      none: "No tags.",
      add: "Add a tag",
      tag: "Tag",
      help: "A word or two: school, awaiting reprint. Ten at most.",
      added: "Tag added",
      remove: (tag: string) => `Remove the tag ${tag}`,
      removed: "Tag removed",
    },
    moves: {
      pack: "Mark packed",
      ship: "Send by hand",
      deliver: "Mark delivered",
      release: "Release the hold",
      payment_link: "Send the payment link",
      offline_payment: "Record a payment",
    } as Record<string, string>,
    done: {
      pack: "Marked packed",
      ship: "Marked sent",
      deliver: "Marked delivered",
      release: "Released",
    } as Record<string, string>,
    ship: {
      title: "Send by hand",
      text: "For India Post or a courier without our booking: the customer gets the tracking number.",
      courier: "Courier",
      tracking: "Tracking number",
      url: "Tracking address",
      urlHelp: "Optional: the courier's page for this parcel.",
      submit: "Mark sent",
    },
    notify: {
      title: "Send a message again",
      text: "The email again, and the SMS where the customer asked for them, if it is still true. An SMS at night waits for 08:00.",
      kind: "Message",
      submit: "Send it again",
      sent: "Message sent",
      kinds: {
        placed: "Order placed",
        paid: "Payment received",
        packed: "Packed",
        shipped: "Sent",
        delivered: "Delivered",
        cancelled: "Cancelled",
        refunded: "Refunded",
      } as Record<string, string>,
    },
    link: {
      send: "Send the payment link",
      sent: "Link sent",
      cancel: "Cancel the payment link",
      cancelled: "Link cancelled",
      cancelTitle: "Cancel the payment link?",
      cancelText: "The customer can no longer pay with it. The next link sent is a new one.",
    },
    offline: {
      title: "Record a payment received",
      text: "A transfer or UPI payment to our account. Above your limit FINANCE approves it first.",
      reference: "UTR or UPI reference",
      submit: "Record the payment",
      recorded: "Payment recorded",
    },
    timelineKinds: {
      status: "Status",
      payment: "Payment",
      refund: "Refund",
      parcel: "Parcel",
      scan: "Scan",
      message: "Message",
      note: "Note",
      hold: "Hold",
      return: "Return",
      audit: "Audit",
      erp: "ERPNext",
    } as Record<string, string>,
    noTimeline: "Nothing recorded yet.",
    noErp: "Not in ERPNext yet.",
    danger: "Cancel, refund or take back",
    cancel: {
      action: "Cancel the order",
      text: "Before it leaves: its copies go back into stock and the customer is told. Paid online, it is refunded through the refund's approval.",
      returnedText:
        "The cash-on-delivery parcel came back: the order is cancelled and its invoice credited. No money moves.",
      title: "Cancel this order?",
      reason: "Reason",
      reasonHelp: "Told to the customer, and kept in the audit trail.",
      asked: "The customer asked for it",
      restock: "Put the copies back into stock",
      restockHelp: "Leave it unticked when the parcel came back damaged.",
      submit: "Cancel the order",
      keep: "Keep it",
      done: "Order cancelled",
    },
    refund: {
      action: "Refund",
      text: "Some books or all of it, with or without the shipping. Above your limit FINANCE approves it first.",
      title: "Refund",
      lines: "Copies to refund",
      copies: (title: string) => `Copies of ${title} to refund`,
      left: (count: number) => `${count} left`,
      shipping: "Shipping to refund",
      shippingHelp: (left: string) => `Up to ${left}.`,
      restock: "Put the copies back into stock",
      method: "How the money goes back",
      methods: {
        source: "To where it came from, through Razorpay",
        bank: "By bank transfer or UPI",
      } as Record<string, string>,
      days: {
        source: "5 to 7 working days for the money to reach the customer.",
        optimum: "Instant where the customer's bank allows it, for a fee.",
        bank: "Our transfer, within 3 working days; then the customer's bank.",
      },
      rules:
        "Razorpay refunds an online payment to the card, UPI or bank it came from. A refund by bank or UPI is for cash on delivery and transfers, and for an online payment only when the customer agrees to it.",
      speed: "Speed",
      speeds: { normal: "Normal", optimum: "Instant (a fee)" } as Record<string, string>,
      payee: "The customer's account",
      payeeKind: "Pay to",
      payeeKinds: { upi: "A UPI ID", account: "A bank account" } as Record<string, string>,
      upi: "UPI ID",
      account: "Account number",
      ifsc: "IFSC",
      holder: "Account holder's name",
      agreed: "The customer agreed to a refund by bank or UPI",
      cancels: "Not sent yet: the order is cancelled and the payment refunded in full.",
      amount: (amount: string) => `About ${amount}: the server's own sum is in its answer.`,
      nothing: "Choose copies or shipping to refund, or leave both empty to refund what is left of the payment.",
      reason: "Reason",
      reasonHelp: "Told to the customer, and kept with the refund.",
      submit: "Ask for the refund",
      done: "Refund started",
      none: "Nothing is left to refund on this order.",
    },
    returnAsk: {
      action: "Ask for a return",
      text: "On the customer's behalf, for a delivered order: they are told how to send the books back once approved.",
      title: "Ask for a return",
      copies: (title: string) => `Copies of ${title} to send back`,
      reason: "Reason",
      note: "What the customer said",
      submit: "Ask for the return",
      done: "Return asked",
    },
    returnReasons: {
      damaged: "Damaged in transit",
      misprint: "Misprinted or pages missing",
      wrong_item: "Not the book ordered",
      late: "Delivered late",
      not_as_described: "Not as described",
      other: "Another reason",
    } as Record<string, string>,
    // packer mode
    packing: {
      title: "Packing queue",
      lead: "Paid orders and cash-on-delivery orders to pack, oldest first. Held orders wait for a release.",
      collect: (amount: string) => `Collect ${amount}`,
      weight: (grams: number) => `About ${grams.toLocaleString("en-IN")} g packed`,
      noWeight: "Weigh it: a book has no weight on record.",
      to: "To",
      pick: "Pick",
      copies: (count: number) => `× ${count}`,
      slip: "Packing slip",
      label: "Label",
      choose: (number: string) => `Add order ${number} to the pick list`,
      pickList: (count: number) => `Print the pick list (${plural(count, "order", "orders")})`,
      pickListAll: "Print the pick list of this page",
      pickListMade: "Pick list ready",
      emptyTitle: "Nothing to pack",
      emptyText: "Every paid order is packed. Held orders show in the orders list.",
    },
    // returns
    returns: {
      title: "Returns",
      lead: "Books customers send back: decide within two working days, then receive and inspect what comes back.",
      columns: {
        number: "Return",
        order: "Order",
        status: "State",
        reason: "Reason",
        books: "Books",
        by: "Asked by",
        asked: "Asked",
      },
      byCustomer: "The customer",
      byStaff: "Staff",
      filters: { status: "State", open: "Open", reason: "Reason", order: "Order number" },
      openOptions: { true: "Open", false: "Closed" } as Record<string, string>,
      statuses: {
        requested: "Asked for",
        approved: "Approved",
        declined: "Declined",
        label_sent: "Label sent",
        received: "Received",
        restocked: "Back in stock",
        damaged: "Damaged",
        refunded: "Refunded",
      } as Record<string, string>,
      emptyTitle: "No returns",
      emptyText: "Returns customers ask for on the website, and those staff ask for, show here.",
      eyebrow: "Return",
      facts: {
        order: "Order",
        reason: "Reason",
        by: "Asked by",
        asked: "Asked",
        decision: "Decision",
        label: "Return label",
        received: "Received",
        inspected: "Inspected",
        refund: "Refund",
      },
      note: "What the customer said",
      noNote: "Nothing more.",
      lines: "Books",
      photos: "Photographs",
      photo: (index: number) => `Photograph ${index + 1}`,
      noPhotos: "No photograph.",
      addPhoto: "Add a photograph",
      photoHelp: "JPEG, PNG or WebP, 5 MB at most; five at most.",
      photoAdded: "Photograph added",
      next: "Next step",
      nothingNext: "Nothing more to do.",
      approve: "Approve",
      approved: "Approved",
      decline: "Decline",
      declineTitle: "Decline this return?",
      declineText: "The customer is told, with your reason.",
      declineNote: "Why",
      declined: "Declined",
      label: "Send the return label",
      labelText: "The courier and the number the customer hands the parcel over with.",
      labelCourier: "Courier",
      labelAwb: "AWB or tracking number",
      labelSent: "Label sent",
      receive: "Mark received",
      received: "Received",
      inspect: "Inspect",
      inspectText: "Back into stock, or damaged (the copies stay out).",
      restocked: "Back in stock",
      damaged: "Damaged",
      inspectedRestocked: "Put back",
      inspectedDamaged: "Marked damaged",
      inspected: "Inspected",
      refund: "Refund it",
      refundText: "Its books, through the order's refund (its approval above your limit).",
    },
    // a staff order
    create: {
      title: "New order",
      lead: "A phone, WhatsApp, email or school order at today's prices with the offers. The customer pays through a link or a transfer.",
      channel: "How it came",
      channels: { phone: "By phone", whatsapp: "On WhatsApp", school: "For a school", email: "By email" } as Record<
        string,
        string
      >,
      customer: "Customer",
      email: "Email address",
      emailHelp: "The order, the payment link and the invoice go there.",
      address: "Delivery address",
      name: "Name",
      phone: "Mobile number",
      line1: "Address",
      line2: "Landmark (optional)",
      city: "Town or city",
      district: "District",
      state: "State",
      pin: "PIN code",
      books: "Books",
      search: "Find a book",
      searchHelp: "Two letters or more of its title, or its ISBN.",
      searching: "Looking…",
      noMatch: "No book on sale matches.",
      add: (title: string) => `Add ${title}`,
      addShort: "Add",
      chooseState: "Choose the state",
      remove: (title: string) => `Remove ${title}`,
      copies: (title: string) => `Copies of ${title}`,
      noBooks: "No book yet: find one above.",
      price: (amount: string, available: number) => `${amount} each · ${available.toLocaleString("en-IN")} in stock`,
      discount: "Discount, in rupees",
      discountHelp: "Off the books after the offers.",
      shipping: "Shipping, in rupees",
      shippingHelp: "Leave it empty for the shipping rates'.",
      sendLink: "Email a payment link now",
      finish: "The payment link and the reason",
      note: "Note for colleagues (optional)",
      reason: "Reason",
      reasonHelp: "Why, for the approver and the audit trail.",
      preview: "What it comes to",
      previewing: "Working it out…",
      previewAsk: "Add a book and the state to see what it comes to.",
      offers: "Offers",
      yourDiscount: (percent: string) => `Your discount (${percent}% of the books)`,
      atOnce: (limit: string) => `Within your limit of ${limit}%: the order is made at once.`,
      atOnceNoLimit: "You have no discount limit: the order is made at once.",
      waits: "A second person approves it first:",
      submit: "Make the order",
      ask: "Ask for approval",
      made: "Order made",
    },
    states: {
      AN: "Andaman and Nicobar Islands",
      AP: "Andhra Pradesh",
      AR: "Arunachal Pradesh",
      AS: "Assam",
      BR: "Bihar",
      CH: "Chandigarh",
      CT: "Chhattisgarh",
      DH: "Dadra and Nagar Haveli and Daman and Diu",
      DL: "Delhi",
      GA: "Goa",
      GJ: "Gujarat",
      HP: "Himachal Pradesh",
      HR: "Haryana",
      JH: "Jharkhand",
      JK: "Jammu and Kashmir",
      KA: "Karnataka",
      KL: "Kerala",
      LA: "Ladakh",
      LD: "Lakshadweep",
      MH: "Maharashtra",
      ML: "Meghalaya",
      MN: "Manipur",
      MP: "Madhya Pradesh",
      MZ: "Mizoram",
      NL: "Nagaland",
      OR: "Odisha",
      PB: "Punjab",
      PY: "Puducherry",
      RJ: "Rajasthan",
      SK: "Sikkim",
      TG: "Telangana",
      TN: "Tamil Nadu",
      TR: "Tripura",
      UP: "Uttar Pradesh",
      UT: "Uttarakhand",
      WB: "West Bengal",
    } as Record<string, string>,
    // quotes
    quotes: {
      title: "Quotes",
      lead: "Quotation requests from schools and booksellers. A quote becomes a staff order once.",
      columns: {
        number: "Quote",
        school: "School",
        contact: "Contact",
        copies: "Copies",
        status: "State",
        valid: "Valid until",
        order: "Order",
      },
      statuses: { new: "New", quoted: "Quotation made", ordered: "Ordered", closed: "Closed" } as Record<
        string,
        string
      >,
      emptyTitle: "No quotation requests",
      emptyText: "Requests from the website's form show here.",
      eyebrow: "Quote",
      facts: {
        school: "School",
        contact: "Contact",
        email: "Email",
        phone: "Mobile",
        gstin: "GSTIN",
        pin: "Delivery PIN code",
        discount: "Discount",
        shipping: "Shipping",
        quoted: "Quotation made",
        valid: "Valid until",
        order: "Order",
      },
      items: "Books asked for",
      itemColumns: { title: "Book", copies: "Copies" },
      note: "Their note",
      quotation: "Download the quotation",
      noQuotation: "No quotation PDF yet.",
      convert: "Make the order",
      convertText:
        "A staff order of its books at today's prices, with its discount and shipping, to this address. Once: the quote keeps its order.",
      convertSubmit: "Make the order",
      convertReason: "The school accepted the quotation.",
      converted: "Order made",
      waiting: (id: string) => `Its order waits for approval: change request ${id}.`,
      ordered: (number: string) => `Ordered: ${number}.`,
    },
  },
};

export type Copy = typeof en;

/** The console's words. One language for now; the person's language picks the object once the others exist. */
export const copy: Copy = en;

/** A code the API sends that no table here names ("sync_failure"): its words, as a fallback ("Sync failure"). */
export function humanize(code: string): string {
  const words = code.replace(/[_-]+/g, " ").trim();
  return words ? words[0].toUpperCase() + words.slice(1).toLowerCase() : code;
}

/** The label of a known code, else its humanized words. */
export function labelOf(table: Record<string, string>, code: string | null | undefined): string {
  if (!code) return copy.common.unknown;
  return table[code] ?? humanize(code);
}
