# Generated by Django 6.1.2 on 2026-10-08 04:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import learn.models
import model_utils.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_login_phone'),
        ('content', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='learner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('minutes_per_day', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)])),
                ('reminders', models.BooleanField(default=False, verbose_name='daily reminder in the app')),
            ],
        ),
        migrations.CreateModel(
            name='BookCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('batch', models.CharField(help_text='The print run, e.g. PHY-2027-1.', max_length=40)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('redeemed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('redeemed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='Empty: all.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.subject')),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=1, default=0, help_text='From format.json: import_chapter_insights.', max_digits=4, verbose_name='Board marks')),
                ('frequency', models.PositiveSmallIntegerField(default=0, help_text='Questions the Board asked on it (production/<subject>/pyq/).', verbose_name='previous-year questions')),
                ('must_do', models.TextField(blank=True, help_text='Markdown.', verbose_name='must-do note')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='content.subject')),
            ],
            options={
                'ordering': ['subject', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('concept', 'concept'), ('trick', 'trick'), ('shortcut', 'shortcut'), ('formula', 'formula'), ('pattern', 'question pattern'), ('mistake', 'common mistake'), ('pyq', 'previous-year question')], default='concept', max_length=10)),
                ('source', models.FileField(blank=True, help_text='Vertical (9:16) is best; processed into HLS for phones after saving.', upload_to=learn.models.source_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'm4v', 'webm', 'mkv']), learn.models.max_upload], verbose_name='video')),
                ('processing', django_fsm.FSMField(choices=[('uploaded', 'uploaded'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='uploaded', editable=False, max_length=50)),
                ('processing_error', models.TextField(blank=True, editable=False, help_text="The end of ffmpeg's messages.")),
                ('hls_path', models.CharField(blank=True, editable=False, max_length=300, verbose_name='HLS master playlist')),
                ('poster', models.CharField(blank=True, editable=False, max_length=300)),
                ('duration', models.PositiveIntegerField(default=0, editable=False, verbose_name='seconds')),
                ('notes', models.TextField(blank=True, help_text='Markdown.', verbose_name='transcript or notes')),
                ('is_free_preview', models.BooleanField(default=False, help_text='The first clip of a revision is free anyway (LEARN_FREE_PREVIEW).', verbose_name='free preview')),
                ('questions', models.ManyToManyField(blank=True, related_name='+', to='content.question')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='FCM sends to it.', max_length=512, unique=True, verbose_name='Firebase installation ID')),
                ('platform', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source', models.CharField(choices=[('book_code', 'book code'), ('purchase', 'purchase'), ('grant', 'staff grant')], default='grant', editable=False, max_length=10)),
                ('reference', models.CharField(blank=True, editable=False, help_text='The order or the book code.', max_length=40)),
                ('valid_until', models.DateField(blank=True, help_text='The last day; empty: no end.', null=True)),
                ('note', models.CharField(blank=True, help_text='Why it was granted (staff).', max_length=200)),
                ('subject', models.ForeignKey(blank=True, help_text='Empty: all.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('front', models.TextField(help_text='Markdown.')),
                ('back', models.TextField(help_text='Markdown.')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_cards', to='learn.chapter')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known', models.BooleanField()),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_reviews', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learn.flashcard')),
            ],
            options={
                'ordering': ['created', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_watched', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learn.clip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mcq', 'multiple choice'), ('true_false', 'true or false'), ('fill_blank', 'fill in the blank')], max_length=10)),
                ('text', models.TextField(help_text='Markdown.', verbose_name='question')),
                ('options', models.JSONField(blank=True, default=list, help_text='Multiple choice: the options, ["(i) …", …].')),
                ('answer', models.CharField(help_text="Multiple choice: the right option's number (1 for the first); true or false: true or false; fill in the blank: the accepted answers, separated by |.", max_length=200)),
                ('explanation', models.TextField(blank=True, help_text='Markdown.')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_items', to='learn.chapter')),
                ('source', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.question')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['chapter', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learn.quizitem')),
            ],
            options={
                'ordering': ['created', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('target_minutes', models.PositiveSmallIntegerField(default=12, help_text='10 to 15.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], db_index=True, default='draft', max_length=10)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='learn.chapter')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='clip',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='learn.revision'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('subject', 'number'), name='unique_learn_chapter'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('user', 'clip'), name='one_progress_per_clip'),
        ),
    ]
