# Generated by Django 6.1.2 on 2026-10-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='chosen',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
