# Generated by Django 6.1.2 on 2026-10-08 04:38

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('learn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('batch', models.CharField(help_text='The print run, e.g. PHY-2027-1.', max_length=40)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('redeemed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('redeemed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='Empty: all.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.subject')),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source', models.CharField(choices=[('book_code', 'book code'), ('purchase', 'purchase'), ('grant', 'staff grant')], default='grant', editable=False, max_length=10)),
                ('reference', models.CharField(blank=True, editable=False, help_text='The order or the book code.', max_length=40)),
                ('valid_until', models.DateField(blank=True, help_text='The last day; empty: no end.', null=True)),
                ('note', models.CharField(blank=True, help_text='Why it was granted (staff).', max_length=200)),
                ('subject', models.ForeignKey(blank=True, help_text='Empty: all.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
