# Generated by Django 6.1.2 on 2026-10-09 20:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Max, Min, Q


def number_quiz_items(apps, schema_editor):
    """A chapter's quiz items numbered 1, 2, 3 … in the order the app showed them (by id): their new `order`."""
    QuizItem = apps.get_model("learn", "QuizItem")
    changed, place, chapter = [], 0, None
    for item in QuizItem.objects.order_by("chapter_id", "pk").iterator():
        place = place + 1 if item.chapter_id == chapter else 1
        chapter, item.order = item.chapter_id, place
        changed.append(item)
    QuizItem.objects.bulk_update(changed, ["order"], batch_size=500)


def batches_from_codes(apps, schema_editor):
    """A CodeBatch for each print run the codes name (BookCode.batch): its codes counted, its subject when they share
    one. Made before the panel, their dispatch went unrecorded: they count as dispatched since their codes were made,
    so the leak rule (insights) reads no redemption of them as one."""
    BookCode, CodeBatch = apps.get_model("learn", "BookCode"), apps.get_model("learn", "CodeBatch")
    rows = BookCode.objects.values("batch").annotate(
        n=Count("pk"),
        first=Min("created"),
        subjects=Count("subject", distinct=True),
        every=Count("pk", filter=Q(subject__isnull=True)),
        subject=Max("subject"),
    )
    known = set(CodeBatch.objects.values_list("label", flat=True))
    CodeBatch.objects.bulk_create(
        CodeBatch(
            label=row["batch"][:40],
            # one subject, or every subject (ALL); a batch mixing them is shown as every subject
            subject_id=row["subject"] if row["subjects"] == 1 and not row["every"] else None,
            printed=row["n"],
            created=row["first"],
            generated_at=row["first"],
            dispatched_at=row["first"],
            note="Made before the panel: its dispatch date was not recorded.",
        )
        for row in rows.order_by("batch")
        if row["batch"] and row["batch"] not in known
    )


def start_history(apps, schema_editor):
    """The history of the quiz items and the entitlements starts with each row as it is ("+")."""
    now = django.utils.timezone.now()
    for name in ("QuizItem", "Entitlement"):
        model, historical = apps.get_model("learn", name), apps.get_model("learn", f"Historical{name}")
        fields = [field.attname for field in model._meta.concrete_fields]
        historical.objects.bulk_create(
            (
                historical(
                    **{field: getattr(row, field) for field in fields},
                    history_date=now,
                    history_type="+",
                    history_change_reason="the history starts here (Phase B)",
                )
                for row in model.objects.order_by("pk").iterator()
            ),
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_phase_b_content'),
        ('learn', '0002_quizattempt_chosen'),
        ('shop', '0022_merge_0021_phase_b_orders_0021_phase_b_tax'),
        ('staff', '0018_phase_b_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='PHY-2027-1.', max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9-]{0,39}\\Z', "A print run's label: letters, digits and hyphens.")])),
                ('printed', models.PositiveIntegerField(default=0, help_text='Codes made for the print run.')),
                ('note', models.TextField(blank=True, help_text='The printer, the run, the delivery.', verbose_name="the print run's note")),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_at', models.DateTimeField(blank=True, help_text='Empty while its job makes the codes.', null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='The books left: redemptions start here.', null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'code batches',
                'ordering': ['-created', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEntitlement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source', models.CharField(choices=[('book_code', 'book code'), ('purchase', 'purchase'), ('grant', 'staff grant')], default='grant', editable=False, max_length=10)),
                ('reference', models.CharField(blank=True, editable=False, help_text='The order or the book code.', max_length=40)),
                ('valid_until', models.DateField(blank=True, help_text='The last day; empty: no end.', null=True)),
                ('note', models.CharField(blank=True, help_text='Why it was granted (staff).', max_length=200)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, help_text='Revoked by staff, with why.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical entitlement',
                'verbose_name_plural': 'historical entitlements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalQuizItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mcq', 'multiple choice'), ('true_false', 'true or false'), ('fill_blank', 'fill in the blank')], max_length=10)),
                ('text', models.TextField(help_text='Markdown.', verbose_name='question')),
                ('options', models.JSONField(blank=True, default=list, help_text='Multiple choice: the options, ["(i) …", …].')),
                ('answer', models.CharField(help_text="Multiple choice: the right option's number (1 for the first); true or false: true or false; fill in the blank: the accepted answers, separated by |.", max_length=200)),
                ('explanation', models.TextField(blank=True, help_text='Markdown.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text="Its place in the chapter's quiz.")),
                ('topic', models.CharField(blank=True, help_text="Within the chapter: Coulomb's law.", max_length=120)),
                ('marks', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='', max_length=10)),
                ('bloom', models.CharField(blank=True, choices=[('remember', 'remember'), ('understand', 'understand'), ('apply', 'apply'), ('analyse', 'analyse'), ('evaluate', 'evaluate'), ('create', 'create')], default='', max_length=10, verbose_name='Bloom level')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='In the bin: purged 30 days later.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical quiz item',
                'verbose_name_plural': 'historical quiz items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='quizitem',
            options={'ordering': ['chapter', 'order', 'pk']},
        ),
        migrations.AddField(
            model_name='bookcode',
            name='voided_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Void: never redeemed.', null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='In the bin: purged 30 days later.', null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='revoked_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Revoked by staff, with why.', null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='In the bin: purged 30 days later.', null=True),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='bloom',
            field=models.CharField(blank=True, choices=[('remember', 'remember'), ('understand', 'understand'), ('apply', 'apply'), ('analyse', 'analyse'), ('evaluate', 'evaluate'), ('create', 'create')], default='', max_length=10, verbose_name='Bloom level'),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='In the bin: purged 30 days later.', null=True),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='marks',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text="Its place in the chapter's quiz."),
        ),
        migrations.AddField(
            model_name='quizitem',
            name='topic',
            field=models.CharField(blank=True, help_text="Within the chapter: Coulomb's law.", max_length=120),
        ),
        migrations.AddField(
            model_name='revision',
            name='publish_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Approved: published by the task at this time.', null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='reviewer',
            field=models.ForeignKey(blank=True, editable=False, help_text='Who approved it (never who submitted it).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revision',
            name='submitted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='submitted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='revision',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('review', 'in review'), ('approved', 'approved')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AddIndex(
            model_name='bookcode',
            index=models.Index(fields=['batch', 'redeemed_at'], name='learn_bookcode_batch'),
        ),
        migrations.AddField(
            model_name='codebatch',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codebatch',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.job'),
        ),
        migrations.AddField(
            model_name='codebatch',
            name='product',
            field=models.ForeignKey(blank=True, help_text="The book the codes are printed in: its sales are the batch's in the codes report.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.product'),
        ),
        migrations.AddField(
            model_name='codebatch',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Empty: all.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.subject'),
        ),
        migrations.AddField(
            model_name='historicalentitlement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalentitlement',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Empty: all.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.subject'),
        ),
        migrations.AddField(
            model_name='historicalentitlement',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquizitem',
            name='chapter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='learn.chapter'),
        ),
        migrations.AddField(
            model_name='historicalquizitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquizitem',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.question'),
        ),
        migrations.RunPython(number_quiz_items, migrations.RunPython.noop),
        migrations.RunPython(batches_from_codes, migrations.RunPython.noop),
        migrations.RunPython(start_history, migrations.RunPython.noop),
    ]
