# Generated by Django 6.1.2 on 2026-10-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_audit_append_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='kind',
            field=models.CharField(choices=[('approval', 'approval'), ('teacher_request', 'teacher access request'), ('deletion_request', 'account deletion'), ('data_request', 'data request'), ('incident', 'incident'), ('failed_job', 'failed job'), ('failed_webhook', 'failed webhook'), ('sync_failed', 'ERPNext refused a document (a dead letter)'), ('reconciliation', 'ERPNext reconciliation differences')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('audit_export', 'audit log export'), ('bulk_action', 'bulk action'), ('erp_initial_load', 'ERPNext initial load')], max_length=20),
        ),
    ]
