# Generated by Django 6.1.2 on 2026-10-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_shipping_and_insights_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='kind',
            field=models.CharField(choices=[('approval', 'approval'), ('teacher_request', 'teacher access request'), ('deletion_request', 'account deletion'), ('data_request', 'data request'), ('incident', 'incident'), ('failed_job', 'failed job'), ('failed_webhook', 'failed webhook'), ('sync_failed', 'ERPNext refused a document (a dead letter)'), ('reconciliation', 'ERPNext reconciliation differences'), ('shipping_exception', 'parcel exception'), ('dead_letter', 'integration task given up'), ('failed_event', 'provider event not processed'), ('integration_down', 'integration unavailable')], db_index=True, max_length=20),
        ),
    ]
