# Generated by Django 6.1.2 on 2026-10-09 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_impersonation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(help_text='app_label.model, e.g. shop.order', max_length=60)),
                ('target_id', models.CharField(max_length=64)),
                ('body', models.TextField(max_length=5000)),
                ('pinned', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-created', '-pk'],
                'default_permissions': ('view', 'add'),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='staff_note_target')],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=40)),
                ('version', models.CharField(max_length=40)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at', '-pk'],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('user', 'policy', 'version'), name='one_acknowledgement_per_version')],
            },
        ),
    ]
