# Generated by Django 6.1.2 on 2026-10-09 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_notes_and_policy_acknowledgements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('refund_order', 'Refund orders (above your limit a second person approves)'), ('approve_refund', "Approve refunds above the maker's limit"), ('record_offline_payment', 'Record payments received offline (above a value a second person approves)'), ('approve_payment', 'Approve offline payments above the limit'), ('approve_discount', 'Approve prices and coupons beyond the discount limit'), ('pack_order', 'Pack orders, hand them to the courier and mark them delivered'), ('publish_paper', 'Publish and unpublish papers'), ('reveal_contact', "Reveal a customer's masked details, with a reason (logged)"), ('suspend_user', 'Suspend and reactivate customer accounts'), ('unlock_user', "Lift a customer's log-in lock-out"), ('resend_verification', "Send a parent's consent link again"), ('end_user_sessions', 'Sign a customer out of every device'), ('initiate_password_reset', 'Email a customer a link to set a new password'), ('reset_user_mfa', 'Reset a second factor (a second person approves)'), ('impersonate_user', 'Log in as a customer for 15 minutes, with a reason'), ('export_personal_data', 'Send a person their data for an access request'), ('handle_data_request', 'Handle data requests: access, correction, erasure, grievances'), ('approve_erasure', 'Approve an erasure started by staff'), ('manage_incident', 'Keep the breach register: incidents and their reports'), ('view_staff', 'See staff, their roles, scopes and the access review'), ('assign_role', 'Invite staff; give and take away roles and scopes'), ('approve_role_change', 'Approve privileged roles and staff second-factor resets'), ('manage_api_keys', 'Create and revoke API keys'), ('break_glass', 'Approve your own request when nobody else can (a reason; the owners are told)'), ('view_auditlog', 'Read the audit log (each read is logged)'), ('export_auditlog', 'Export the audit log'), ('approve_export', 'Approve large exports and bulk actions'), ('manage_settings', "Change the site's settings: shop open, cash on delivery, consent mode"), ('manage_flags', 'Switch feature flags'), ('toggle_maintenance', 'Switch maintenance mode and its banner'), ('view_system', 'See the system: health, queues, webhooks, mail and SMS, backups'), ('replay_webhook', 'Replay webhooks and dead letters; ask Razorpay again what became of a payment'), ('view_inbox', 'Use the inbox of things that wait'), ('view_parcels', 'See parcels, their timelines and exceptions, and the pickup addresses'), ('book_parcel', 'Book parcels: quotes, labels, pickups, manifests, cancellations'), ('act_on_exception', 'Act on failed deliveries and resolve parcel exceptions'), ('view_cod', "See cash-on-delivery remittances and the courier's charges"), ('reconcile_cod', "Match cash-on-delivery remittances with the bank's credits"), ('manage_pickup_locations', 'Add and change the pickup addresses'), ('view_insights', 'See the insights: forecasts, print runs, item analysis, cohorts, fraud signals'), ('acknowledge_signal', 'Acknowledge fraud signals (looked at and handled)'), ('manage_connections', 'Test and switch the connections: credentials, webhook tokens, circuits, test and live (the owners are told)'), ('manage_system', "Record restore drills and act on the system's pages")]},
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='kind',
            field=models.CharField(choices=[('approval', 'approval'), ('teacher_request', 'teacher access request'), ('deletion_request', 'account deletion'), ('data_request', 'data request'), ('incident', 'incident'), ('failed_job', 'failed job'), ('failed_webhook', 'failed webhook'), ('sync_failed', 'ERPNext refused a document (a dead letter)'), ('reconciliation', 'ERPNext reconciliation differences'), ('shipping_exception', 'parcel exception'), ('dead_letter', 'integration task given up'), ('failed_event', 'provider event not processed'), ('integration_down', 'integration unavailable'), ('role_expired', 'a temporary role ended'), ('offboarding', 'offboarding: accounts to close by hand'), ('webhook_silent', "a provider's webhooks fell silent"), ('template_idle', 'a message template unused for months'), ('template_certify', "a message template's yearly self-certification"), ('backup_stale', 'no recent backup'), ('dependencies_stale', 'the dependency report is old'), ('scripts_changed', "the checkout's or console's scripts changed")], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RestoreDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField()),
                ('engine', models.CharField(choices=[('platform', "the platform's PostgreSQL"), ('erpnext', "ERPNext's MariaDB and files"), ('both', 'both engines')], max_length=10)),
                ('backup', models.CharField(help_text="The backup restored: its object's name in the bucket.", max_length=200)),
                ('result', models.CharField(choices=[('passed', 'it worked'), ('partial', 'it worked in part'), ('failed', 'it failed')], max_length=10)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_on', '-pk'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='ScriptInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('checkout', "the storefront's checkout"), ('console', "the console's sign-in")], max_length=10)),
                ('src', models.URLField(blank=True, help_text='Empty: an inline script.', max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['page', '-last_seen', 'pk'],
                'default_permissions': ('view',),
                'constraints': [models.UniqueConstraint(fields=('page', 'src', 'sha256'), name='one_script_per_content')],
            },
        ),
        migrations.CreateModel(
            name='StaffOffboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When its last step was done.', null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='OffboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('auto', 'done by the panel'), ('manual', 'ticked by an owner')], max_length=6)),
                ('state', models.CharField(choices=[('done', 'done'), ('todo', 'to do'), ('not_needed', 'not needed')], default='todo', max_length=10)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='staff.staffoffboarding')),
            ],
            options={
                'ordering': ['offboarding', 'position', 'pk'],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('offboarding', 'key'), name='one_offboarding_step_per_key')],
            },
        ),
    ]
