# Generated by Django 6.1.2 on 2026-10-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_notes_and_policy_acknowledgements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('refund_order', 'Refund orders (above your limit a second person approves)'), ('approve_refund', "Approve refunds above the maker's limit"), ('record_offline_payment', 'Record payments received offline (above a value a second person approves)'), ('approve_payment', 'Approve offline payments above the limit'), ('approve_discount', 'Approve prices and coupons beyond the discount limit'), ('pack_order', 'Pack orders, hand them to the courier and mark them delivered'), ('publish_paper', 'Publish and unpublish papers'), ('reveal_contact', "Reveal a customer's masked details, with a reason (logged)"), ('suspend_user', 'Suspend and reactivate customer accounts'), ('unlock_user', "Lift a customer's log-in lock-out"), ('resend_verification', "Send a parent's consent link again"), ('end_user_sessions', 'Sign a customer out of every device'), ('initiate_password_reset', 'Email a customer a link to set a new password'), ('reset_user_mfa', 'Reset a second factor (a second person approves)'), ('impersonate_user', 'Log in as a customer for 15 minutes, with a reason'), ('export_personal_data', 'Send a person their data for an access request'), ('handle_data_request', 'Handle data requests: access, correction, erasure, grievances'), ('approve_erasure', 'Approve an erasure started by staff'), ('manage_incident', 'Keep the breach register: incidents and their reports'), ('view_staff', 'See staff, their roles, scopes and the access review'), ('assign_role', 'Invite staff; give and take away roles and scopes'), ('approve_role_change', 'Approve privileged roles and staff second-factor resets'), ('manage_api_keys', 'Create and revoke API keys'), ('break_glass', 'Approve your own request when nobody else can (a reason; the owners are told)'), ('view_auditlog', 'Read the audit log (each read is logged)'), ('export_auditlog', 'Export the audit log'), ('approve_export', 'Approve large exports and bulk actions'), ('manage_settings', "Change the site's settings: shop open, cash on delivery, consent mode"), ('manage_flags', 'Switch feature flags'), ('toggle_maintenance', 'Switch maintenance mode and its banner'), ('view_system', 'See the system: health, queues, webhooks, mail and SMS, backups'), ('replay_webhook', "Ask Razorpay again what became of an order's payment"), ('view_inbox', 'Use the inbox of things that wait'), ('view_parcels', 'See parcels, their timelines and exceptions, and the pickup addresses'), ('book_parcel', 'Book parcels: quotes, labels, pickups, manifests, cancellations'), ('act_on_exception', 'Act on failed deliveries and resolve parcel exceptions'), ('view_cod', "See cash-on-delivery remittances and the courier's charges"), ('reconcile_cod', "Match cash-on-delivery remittances with the bank's credits"), ('manage_pickup_locations', 'Add and change the pickup addresses'), ('view_insights', 'See the insights: forecasts, print runs, item analysis, cohorts, fraud signals'), ('acknowledge_signal', 'Acknowledge fraud signals (looked at and handled)'), ('handle_ticket', 'Handle support tickets: reply, assign, change, move on, close, acknowledge'), ('export_grievances', 'Export the grievance register (a dated CSV, no personal data)')]},
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='kind',
            field=models.CharField(choices=[('approval', 'approval'), ('teacher_request', 'teacher access request'), ('deletion_request', 'account deletion'), ('data_request', 'data request'), ('incident', 'incident'), ('failed_job', 'failed job'), ('failed_webhook', 'failed webhook'), ('sync_failed', 'ERPNext refused a document (a dead letter)'), ('reconciliation', 'ERPNext reconciliation differences'), ('shipping_exception', 'parcel exception'), ('dead_letter', 'integration task given up'), ('failed_event', 'provider event not processed'), ('integration_down', 'integration unavailable'), ('ticket_due', "a ticket's legal clock three quarters gone"), ('ticket_breach', 'a ticket past its legal clock'), ('ticket_mention', "named in a ticket's note")], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('audit_export', 'audit log export'), ('bulk_action', 'bulk action'), ('erp_initial_load', 'ERPNext initial load'), ('grievance_export', 'grievance register export')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffscope',
            name='kind',
            field=models.CharField(choices=[('subject', 'subject (PHY, CHE, MAT, BIO)'), ('board_class', 'board and class (ASSEB:12)'), ('order_status', 'order status'), ('warehouse', 'warehouse'), ('school', 'school'), ('ticket_queue', 'work queue (an inbox kind)'), ('ticket_category', 'ticket category (support: order, content_error …)')], max_length=20),
        ),
    ]
