# Generated by Django 6.1.2 on 2026-10-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_phase_b_legal'),
        ('staff', '0007_phase_b_tax'),
    ]

    operations = [
    ]
