# Generated by Django 6.1.2 on 2026-10-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_phase_b_orders'),
        ('staff', '0009_phase_b_merge_tax_legal'),
    ]

    operations = [
    ]
