# Generated by Django 6.1.2 on 2026-10-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_phase_b_staff'),
        ('staff', '0011_phase_b_merge_orders'),
    ]

    operations = [
    ]
