# Generated by Django 6.1.2 on 2026-10-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_phase_b_catalogue'),
        ('staff', '0020_phase_b_merge_reports'),
    ]

    operations = [
    ]
