# Generated by Django 6.1.2 on 2026-10-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_phase_b_course'),
        ('staff', '0022_phase_b_merge_catalogue'),
    ]

    operations = [
    ]
