# Generated by Django 6.1.2 on 2026-10-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_phase_b_customers'),
        ('staff', '0024_phase_b_merge_course'),
    ]

    operations = [
    ]
