# Generated by Django 6.1.2 on 2026-10-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-date', '-id'], 'permissions': [('export_attempt', 'Can export attempts')]},
        ),
    ]
