# Generated by Django 6.1.2 on 2026-10-09 03:49

import django.db.models.deletion
import django.utils.timezone
import integrations.models
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('provider', models.CharField(choices=integrations.models.provider_choices, max_length=30)),
                ('mode', models.CharField(choices=[('test', 'test'), ('live', 'live')], default='test', max_length=4)),
                ('label', models.CharField(blank=True, help_text="E.g. the API user's name at the provider.", max_length=80)),
                ('enabled', models.BooleanField(default=False, help_text='Off: nothing calls the provider, its webhooks are refused.')),
                ('credentials', models.TextField(blank=True, editable=False)),
                ('credentials_updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rotate_by', models.DateField(blank=True, help_text='Our policy: 90 days after the credentials were set.', null=True)),
                ('token', models.TextField(blank=True, editable=False)),
                ('token_expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('webhook_token', models.TextField(blank=True, editable=False)),
                ('previous_webhook_token', models.TextField(blank=True, editable=False)),
                ('webhook_rotated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='What the credentials may do, as the provider grants it: ["orders", ...].')),
                ('where_else_configured', models.TextField(blank=True, help_text='Other places that hold the same key.')),
                ('last_success_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error', models.CharField(blank=True, editable=False, max_length=500)),
                ('last_test_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_test_ok', models.BooleanField(editable=False, null=True)),
                ('last_test_message', models.CharField(blank=True, editable=False, max_length=300)),
                ('circuit_state', models.CharField(choices=[('closed', 'closed: calls go through'), ('open', 'open: calls wait'), ('half_open', 'half open: one trial call')], default='closed', editable=False, max_length=10)),
                ('failure_count', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('failure_window_started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('opened_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='unavailable since')),
                ('trial_started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('held_open', models.BooleanField(default=False, editable=False, help_text='Opened by staff: no trial until reset.')),
                ('credentials_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'mode'],
            },
        ),
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=integrations.models.provider_choices, max_length=30)),
                ('body', models.TextField(blank=True)),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256 of the body')),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('accepted', 'accepted'), ('duplicate', 'duplicate (nothing new)'), ('rejected', 'rejected (wrong or missing token)'), ('failed', 'failed')], db_index=True, default='accepted', max_length=10)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_events', to='integrations.integrationaccount')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=60)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(help_text='Without its query string.', max_length=300)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, help_text='Empty: no answer (network).', null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('provider_request_id', models.CharField(blank=True, max_length=100)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('excerpt', models.TextField(blank=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='integrations.integrationaccount')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('operation', models.CharField(max_length=60)),
                ('task_name', models.CharField(max_length=200)),
                ('task_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('args', models.JSONField(blank=True, default=dict, help_text='{"args": [...], "kwargs": {...}}, redacted.')),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('last_error', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('open', 'waiting for staff'), ('replayed', 'replayed'), ('discarded', 'discarded')], db_index=True, default='open', max_length=10)),
                ('discard_reason', models.CharField(blank=True, max_length=300)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='integrations.integrationaccount')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='integrationaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'mode'), name='one_integration_account_per_mode'),
        ),
        migrations.AddConstraint(
            model_name='integrationaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('provider',), name='one_enabled_integration_account'),
        ),
        migrations.AddConstraint(
            model_name='inboundevent',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'rejected'), _negated=True), fields=('provider', 'sha256'), name='one_inbound_event_per_body'),
        ),
        migrations.AddIndex(
            model_name='integrationcall',
            index=models.Index(fields=['account', '-created'], name='integration_call_account'),
        ),
    ]
