# Generated by Django 6.1.2 on 2026-10-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundevent',
            name='event_id',
            field=models.CharField(blank=True, help_text="The provider's own id of what it reports (MSG91: its request ids and statuses, hashed); a repeat under the same id is a duplicate whatever its body.", max_length=100, verbose_name="provider's event id"),
        ),
        migrations.AddConstraint(
            model_name='inboundevent',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('state', 'rejected'), _negated=True), models.Q(('event_id', ''), _negated=True)), fields=('provider', 'event_id'), name='one_inbound_event_per_id'),
        ),
    ]
