# Generated by Django 6.1.2 on 2026-10-09 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('shop', '0020_cart_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=60, unique=True)),
                ('modified_after', models.CharField(blank=True, help_text='Empty: from the start.', max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=140)),
                ('rows_read', models.PositiveIntegerField(default=0, help_text='In all, since the cursor was made.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'pull cursor',
                'ordering': ['doctype'],
            },
        ),
        migrations.CreateModel(
            name='ErpReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('state', models.CharField(choices=[('running', 'running'), ('done', 'done'), ('failed', 'failed')], default='running', max_length=10)),
                ('platform_totals', models.JSONField(blank=True, default=dict)),
                ('erp_totals', models.JSONField(blank=True, default=dict, verbose_name="ERPNext's totals")),
                ('differences_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'reconciliation run',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ErpLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examleaf_ref', models.CharField(max_length=140, unique=True, verbose_name='reference')),
                ('model', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=64)),
                ('doctype', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=140, verbose_name='ERPNext name')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'link',
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['model', 'object_id'], name='erp_link_object')],
            },
        ),
        migrations.CreateModel(
            name='ErpMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=140, verbose_name='ERPNext name')),
                ('examleaf_ref', models.CharField(blank=True, max_length=140, verbose_name='reference')),
                ('status', models.CharField(blank=True, max_length=40)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('modified', models.CharField(blank=True, help_text="ERPNext's, as it gave it.", max_length=32)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'B2B mirror',
                'ordering': ['doctype', '-modified'],
                'constraints': [models.UniqueConstraint(fields=('doctype', 'name'), name='erp_one_mirror_per_document')],
            },
        ),
        migrations.CreateModel(
            name='ErpReconciliationDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invoices', 'invoices'), ('credit_notes', 'credit notes'), ('payments', 'payments and refunds'), ('settlements', 'settlements'), ('deliveries', 'delivery notes'), ('stock', 'stock invariant'), ('missing', 'document not in ERPNext')], max_length=15)),
                ('key', models.CharField(max_length=140)),
                ('platform_value', models.CharField(blank=True, max_length=60)),
                ('erp_value', models.CharField(blank=True, max_length=60, verbose_name="ERPNext's value")),
                ('note', models.CharField(blank=True, help_text="Staff's, when resolved.", max_length=300)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differences', to='erp.erpreconciliationrun')),
            ],
            options={
                'verbose_name': 'reconciliation difference',
                'ordering': ['run', 'kind', 'key'],
                'permissions': [('resolve_difference', "Resolve the reconciliation's differences")],
            },
        ),
        migrations.CreateModel(
            name='ErpOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(help_text='order, product or settlement.', max_length=20)),
                ('aggregate_id', models.CharField(help_text="The order's number, the product's id, the settlement's.", max_length=64)),
                ('sequence', models.PositiveIntegerField(help_text="The row's place in its aggregate.")),
                ('event', models.CharField(max_length=40)),
                ('examleaf_ref', models.CharField(db_index=True, max_length=140, verbose_name='reference')),
                ('model', models.CharField(blank=True, help_text='The platform object it is about: shop.invoice …', max_length=40)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('sending', 'sending'), ('sent', 'sent'), ('failed', 'failed, to be tried again'), ('dead', 'dead letter (its aggregate waits)'), ('discarded', 'discarded by staff')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='next try')),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True, verbose_name="ERPNext's answer")),
                ('failure', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.integrationfailure')),
            ],
            options={
                'verbose_name': 'outbox row',
                'ordering': ['-pk'],
                'permissions': [('view_sync', 'See the ERPNext sync'), ('replay_sync', "Replay or discard the ERPNext sync's dead letters"), ('run_initial_load', 'Run the initial load into ERPNext')],
                'indexes': [models.Index(fields=['state', 'next_at'], name='erp_outbox_due'), models.Index(fields=['aggregate_type', 'aggregate_id', 'sequence'], name='erp_outbox_aggregate')],
                'constraints': [models.UniqueConstraint(fields=('aggregate_type', 'aggregate_id', 'sequence'), name='erp_outbox_sequence')],
            },
        ),
        migrations.CreateModel(
            name='ErpStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=140)),
                ('warehouse', models.CharField(max_length=140)),
                ('actual', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reserved', models.DecimalField(decimal_places=3, default=0, help_text="By ERPNext's own orders.", max_digits=12)),
                ('projected', models.DecimalField(decimal_places=3, max_digits=12)),
                ('batches', models.JSONField(blank=True, default=list)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_stock', to='shop.product')),
            ],
            options={
                'verbose_name': 'stock snapshot',
                'ordering': ['item_code', 'warehouse'],
                'constraints': [models.UniqueConstraint(fields=('item_code', 'warehouse'), name='erp_one_snapshot_per_bin')],
            },
        ),
    ]
