# Generated by Django 6.1.2 on 2026-10-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_admin_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('phone_hash', models.CharField(db_index=True, max_length=64, verbose_name='number (hashed)')),
                ('phone_last4', models.CharField(max_length=4, verbose_name='last 4 digits')),
                ('status', models.CharField(choices=[('sent', 'sent'), ('failed', 'refused by the provider'), ('capped', 'not sent: daily cap reached')], max_length=10)),
                ('provider_id', models.CharField(blank=True, max_length=100, verbose_name="provider's request id")),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS log',
                'ordering': ['-created'],
            },
        ),
    ]
