# Generated by Django 6.1.2 on 2026-10-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_sms_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('bounce', 'hard bounce'), ('invalid', 'invalid address'), ('complaint', 'complaint (marked as spam)')], max_length=10)),
                ('esp', models.CharField(max_length=20, verbose_name='reported by')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
