# Generated by Django 6.1.2 on 2026-10-08 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_admin_theme_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('failed', 'refused by the provider'), ('capped', 'not sent: a limit was reached')], max_length=10),
        ),
    ]
