# Generated by Django 6.1.2 on 2026-10-09 16:30; the seed of the template registry added by hand.

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

ORDER = {"name": "var1", "type": "alphanumeric", "max_length": 30, "about": "the order number"}
# ops.sms's kinds and their variables (its docstring): the registry starts with the templates the environment names
SEEDS = {
    "otp": ("transactional", [{"name": "otp", "type": "numeric", "max_length": 6, "about": "the one-time code"}]),
    "order_placed": ("service", [ORDER]),
    "order_shipped": (
        "service",
        [ORDER, {"name": "var2", "type": "alphanumeric", "max_length": 30, "about": "the courier and tracking number"}],
    ),
    "order_delivered": ("service", [ORDER]),
    "parent_consent": (
        "service",
        [
            {"name": "var1", "type": "alphanumeric", "max_length": 30, "about": "the student's first name"},
            {"name": "var2", "type": "alphanumeric", "max_length": 30, "about": "the consent link's token"},
        ],
    ),
    "order_arriving": (
        "service",
        [ORDER, {"name": "var2", "type": "numeric", "max_length": 10, "about": "the cash to keep ready"}],
    ),
    "order_not_delivered": (
        "service",
        [ORDER, {"name": "var2", "type": "alphanumeric", "max_length": 30, "about": "the order link's token"}],
    ),
}


def seed_templates(apps, schema_editor):
    """The SMS templates the environment names (MSG91_TEMPLATE_<KIND>), as approved rows of the registry: from now on
    the registry's id is the one sent (ops.sms.template_id), the environment's only where no row is."""
    MessageTemplate = apps.get_model("ops", "MessageTemplate")
    for kind, msg91_id in getattr(settings, "MSG91_TEMPLATES", {}).items():
        if not msg91_id or kind not in SEEDS:
            continue
        category, variables = SEEDS[kind]
        MessageTemplate.objects.get_or_create(
            event=kind,
            channel="sms",
            language="en",
            defaults={
                "msg91_id": msg91_id,
                "category": category,
                "variables": variables,
                "approval_state": "approved",
                "notes": f"From MSG91_TEMPLATE_{kind.upper()} when the registry was made.",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_sms_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('event', models.CharField(choices=[('sent', 'sent'), ('delivered', 'delivered'), ('bounced', 'bounced for good'), ('complained', 'complained (marked as spam)')], max_length=10)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-day', 'event'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text="What it is sent for: otp, order_placed … (ops.sms's kinds).", max_length=40)),
                ('channel', models.CharField(choices=[('email', 'email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('as', 'Assamese'), ('bn', 'Bengali')], default='en', max_length=2)),
                ('text', models.TextField(blank=True, help_text="As registered: DLT's {#var#} placeholders.", max_length=2000)),
                ('subject', models.CharField(blank=True, help_text="An email's subject.", max_length=200)),
                ('variables', models.JSONField(blank=True, default=list, help_text='[{"name", "type", "max_length", "about"}]')),
                ('dlt_template_id', models.CharField(blank=True, max_length=30, verbose_name='DLT template id')),
                ('pe_id', models.CharField(blank=True, max_length=30, verbose_name='principal entity id')),
                ('header', models.CharField(blank=True, help_text='The registered sender id, e.g. EXMLEF.', max_length=11)),
                ('header_suffix', models.CharField(blank=True, choices=[('P', 'P (promotional)'), ('S', 'S (service)'), ('T', 'T (transactional)'), ('G', 'G (government)')], max_length=1)),
                ('msg91_id', models.CharField(blank=True, max_length=60, verbose_name='MSG91 template id')),
                ('whatsapp_name', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp template name')),
                ('category', models.CharField(choices=[('transactional', 'transactional (one-time codes)'), ('service', 'service (about something bought)'), ('promotional', 'promotional'), ('utility', 'utility (WhatsApp)'), ('authentication', 'authentication (WhatsApp)')], max_length=15)),
                ('approval_state', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted for approval'), ('approved', 'approved'), ('rejected', 'rejected'), ('paused', 'paused'), ('deactivated', 'deactivated')], default='draft', max_length=12)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('self_certified_on', models.DateField(blank=True, help_text="DLT's yearly self-certification.", null=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event', 'channel', 'language'],
                'default_permissions': ('view', 'add', 'change'),
            },
        ),
        migrations.AddField(
            model_name='smslog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="report's time"),
        ),
        migrations.AddField(
            model_name='smslog',
            name='delivery',
            field=models.CharField(blank=True, choices=[('delivered', 'delivered'), ('pending', 'with the operator'), ('failed', 'not delivered'), ('rejected', 'rejected (DLT, DND or a blocked number)')], max_length=10, verbose_name='delivery report'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='delivery_reason',
            field=models.CharField(blank=True, help_text="MSG91's words: why it failed.", max_length=200),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['provider_id'], name='ops_smslog_provider_id'),
        ),
        migrations.AddConstraint(
            model_name='emailstat',
            constraint=models.UniqueConstraint(fields=('day', 'event'), name='one_email_stat_per_day'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('event', 'channel', 'language'), name='one_template_per_message'),
        ),
        migrations.RunPython(seed_templates, migrations.RunPython.noop),
    ]
