# Generated by Django 6.1.2 on 2026-10-08 07:42

from django.db import migrations, models


def first_easy_papers(apps, schema_editor):
    """Each book's first Easy paper (E-01) becomes its open sample; staff may choose another in the admin."""
    Paper = apps.get_model("content", "Paper")
    firsts = {}
    for paper in Paper.objects.filter(tier="E").order_by("book_id", "number", "code"):
        firsts.setdefault(paper.book_id, paper.pk)
    Paper.objects.filter(pk__in=firsts.values()).update(is_sample=True)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaper',
            name='is_sample',
            field=models.BooleanField(default=False, help_text='Its solutions open without an account, even when the others need one: the paper the home, book and product pages offer as a sample. One per book.', verbose_name='open sample'),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_sample',
            field=models.BooleanField(default=False, help_text='Its solutions open without an account, even when the others need one: the paper the home, book and product pages offer as a sample. One per book.', verbose_name='open sample'),
        ),
        migrations.RunPython(first_easy_papers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.UniqueConstraint(condition=models.Q(('is_sample', True)), fields=('book',), name='one_sample_per_book', violation_error_message='Another paper of this book is its open sample: untick that one first.'),
        ),
    ]
