# Generated by Django 6.1.2 on 2026-10-09 16:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_paper_is_sample'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('target_id', models.PositiveBigIntegerField()),
                ('step', models.PositiveSmallIntegerField(blank=True, help_text='The marking step, 1 for the first.', null=True)),
                ('printing', models.CharField(blank=True, help_text='The print run it was read in: PHY-2027-1.', max_length=40)),
                ('category', models.CharField(choices=[('wrong_answer', 'a wrong answer or step'), ('typo', 'a typing or spelling mistake'), ('marks', 'the marks or the marking scheme'), ('unclear', 'hard to follow'), ('display', 'maths or a picture does not show'), ('other', 'something else'), ('item_analysis', 'flagged by the item analysis')], max_length=15)),
                ('note', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, help_text='Left to hear of the fix; cleared once told (or rejected).', max_length=254)),
                ('teacher_verified', models.BooleanField(default=False, help_text='Reported by a verified teacher.')),
                ('state', models.CharField(choices=[('reported', 'reported'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('fixed_online', 'fixed online'), ('fixed_in_printing', 'fixed in printing')], db_index=True, default='reported', max_length=20)),
                ('fixed_in', models.CharField(blank=True, help_text='The printing that carries the fix.', max_length=40)),
                ('fixed_at', models.DateTimeField(blank=True, help_text='When it was fixed online.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When it was confirmed or rejected.', null=True)),
                ('staff_note', models.TextField(blank=True)),
                ('reporter_told_at', models.DateTimeField(blank=True, null=True)),
                ('public', models.BooleanField(default=False, help_text='On the errata of its book and printing.')),
                ('spam', models.BooleanField(db_index=True, default=False)),
                ('spam_reason', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['created', 'pk'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='LegalDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(help_text="The book's edition when it was sent.", max_length=60)),
                ('library', models.CharField(choices=[('national_library', 'National Library, Kolkata'), ('connemara', 'Connemara Public Library, Chennai'), ('asiatic_society', 'Central Library (Asiatic Society), Mumbai'), ('delhi_public_library', 'Delhi Public Library, Delhi')], max_length=25)),
                ('sent_on', models.DateField()),
                ('proof', models.CharField(help_text='How it went and its reference: Speed Post EA123456789IN.', max_length=300)),
                ('proof_file', models.FileField(blank=True, help_text='A scan or photo.', upload_to='content/legal-deposits/')),
                ('erp_delivery_note', models.CharField(blank=True, help_text="ERPNext's delivery note, once made.", max_length=60)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-sent_on', '-pk'],
                'default_permissions': ('view', 'add'),
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('target_id', models.PositiveBigIntegerField()),
                ('label', models.CharField(help_text='What it is, by code: "PHY-E01 2(c), solution".', max_length=200)),
                ('stage', models.CharField(choices=[('check', 'a second person checks it'), ('publish', 'approved: to publish')], default='check', max_length=10)),
                ('state', models.CharField(choices=[('in_progress', 'in progress'), ('approved', 'approved'), ('needs_changes', 'needs changes'), ('cancelled', 'cancelled')], db_index=True, default='in_progress', max_length=15)),
                ('draft', models.JSONField(default=dict, help_text='The changed fields as submitted: {field: value}.')),
                ('previous', models.JSONField(blank=True, default=dict, help_text='The live values its publish replaced.')),
                ('comments', models.JSONField(blank=True, default=list, help_text='[{author, text, at, field}]')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created', '-pk'],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('print', 'printed book'), ('ebook', 'e-book')], default='print', max_length=5),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='One per format, checked when set (content/isbn.py): a new one for a substantial change of the text, never for an unchanged reprint.', max_length=13, verbose_name='ISBN-13'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_on',
            field=models.DateField(blank=True, help_text="The day this edition was published: the legal deposit's clock (CONTENT_LEGAL_DEPOSIT_DAYS) starts.", null=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='format',
            field=models.CharField(choices=[('print', 'printed book'), ('ebook', 'e-book')], default='print', max_length=5),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='isbn',
            field=models.CharField(blank=True, help_text='One per format, checked when set (content/isbn.py): a new one for a substantial change of the text, never for an unchanged reprint.', max_length=13, verbose_name='ISBN-13'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='published_on',
            field=models.DateField(blank=True, help_text="The day this edition was published: the legal deposit's clock (CONTENT_LEGAL_DEPOSIT_DAYS) starts.", null=True),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='draft',
            field=models.JSONField(blank=True, default=dict, help_text='The changed fields to review: {field: value}.'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='draft_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Off: no longer in the books repository (kept, hidden, with its history).'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Its last publish from the panel.', null=True),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='published_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('in_review', 'in review'), ('published', 'published')], db_index=True, default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalsolution',
            name='draft',
            field=models.JSONField(blank=True, default=dict, help_text='The changed fields to review: {field: value}.'),
        ),
        migrations.AddField(
            model_name='historicalsolution',
            name='draft_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsolution',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Its last publish from the panel.', null=True),
        ),
        migrations.AddField(
            model_name='historicalsolution',
            name='published_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsolution',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('in_review', 'in review'), ('published', 'published')], db_index=True, default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='draft',
            field=models.JSONField(blank=True, default=dict, help_text='The changed fields to review: {field: value}.'),
        ),
        migrations.AddField(
            model_name='question',
            name='draft_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Off: no longer in the books repository (kept, hidden, with its history).'),
        ),
        migrations.AddField(
            model_name='question',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Its last publish from the panel.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('in_review', 'in review'), ('published', 'published')], db_index=True, default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='solution',
            name='draft',
            field=models.JSONField(blank=True, default=dict, help_text='The changed fields to review: {field: value}.'),
        ),
        migrations.AddField(
            model_name='solution',
            name='draft_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solution',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Its last publish from the panel.', null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solution',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('in_review', 'in review'), ('published', 'published')], db_index=True, default='published', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn', ''), _negated=True), fields=('isbn',), name='unique_book_isbn', violation_error_message='Another book has this ISBN: each format and edition has its own.'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.paper'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.question'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.subject'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='target_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='legaldeposit',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_deposits', to='content.book'),
        ),
        migrations.AddField(
            model_name='legaldeposit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='edited_by',
            field=models.ForeignKey(blank=True, help_text="The draft's last editor when it was submitted: never its checker.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.paper'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.subject'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='target_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['state', 'created'], name='content_report_queue'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['target_type', 'target_id'], name='content_report_target'),
        ),
        migrations.AddConstraint(
            model_name='errorreport',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'item_analysis'), ('state__in', ['reported', 'confirmed'])), fields=('target_type', 'target_id'), name='one_open_item_flag'),
        ),
        migrations.AddConstraint(
            model_name='legaldeposit',
            constraint=models.UniqueConstraint(fields=('book', 'edition', 'library'), name='one_deposit_per_library', violation_error_message='This library has this edition already.'),
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['target_type', 'target_id'], name='content_review_target'),
        ),
        migrations.AddConstraint(
            model_name='reviewtask',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'in_progress'), models.Q(('published_at', None), ('state', 'approved')), _connector='OR'), fields=('target_type', 'target_id'), name='one_open_review'),
        ),
    ]
