# Generated by Django 6.1.2 on 2026-10-07 21:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import djmoney.models.fields
import djmoney.money
import localflavor.in_.models
import model_utils.fields
import phonenumber_field.modelfields
import shop.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(help_text='Stored in capitals; customers may type any case.', max_length=30, unique=True)),
                ('kind', models.CharField(choices=[('percent', 'per cent off'), ('fixed', 'rupees off')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('min_order', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', help_text='Value of the books, before shipping.', max_digits=10, verbose_name='minimum order')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='All customers together. Empty: no limit.', null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, default=1, help_text='Per account and per email address. Empty: no limit.', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('states', models.JSONField(blank=True, default=list, help_text='None ticked: every state no other rate names.')),
                ('fee_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('fee', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='fee')),
                ('free_above_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3, null=True)),
                ('free_above', djmoney.models.fields.MoneyField(blank=True, currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', help_text='Books worth this much or more ship free.', max_digits=10, null=True, verbose_name='free from')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=120, verbose_name='full name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', validators=[shop.models.validate_indian_mobile], verbose_name='mobile number')),
                ('line1', models.CharField(max_length=200, verbose_name='house and street')),
                ('line2', models.CharField(blank=True, max_length=200, verbose_name='area or landmark')),
                ('city', models.CharField(max_length=80, verbose_name='city, town or village')),
                ('district', models.CharField(max_length=80)),
                ('state', localflavor.in_.models.INStateField(default='AS', max_length=2)),
                ('pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9]\\d{5}$', 'Enter the 6-digit PIN code.')], verbose_name='PIN code')),
                ('is_default', models.BooleanField(default=False, verbose_name='use by default')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'ordering': ['-is_default', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.coupon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(db_index=True, editable=False, max_length=20, null=True)),
                ('email', models.EmailField(help_text="The account's address, or the guest's.", max_length=254)),
                ('subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('subtotal', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='books')),
                ('discount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('discount', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='discount')),
                ('shipping_fee_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('shipping_fee', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='shipping')),
                ('total_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('total', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='total')),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('payment_method', models.CharField(choices=[('razorpay', 'online (UPI, card, net banking)'), ('cod', 'cash on delivery')], default='razorpay', max_length=10)),
                ('status', django_fsm.FSMField(choices=[('pending', 'awaiting payment'), ('paid', 'paid'), ('packed', 'packed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('refunded', 'refunded')], db_index=True, default='pending', max_length=50, protected=True)),
                ('placed_at', models.DateTimeField(blank=True, db_index=True, help_text='Paid online, or placed with cash on delivery.', null=True)),
                ('stock_reserved', models.BooleanField(default=False, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('coupon', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.coupon')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order',
                'verbose_name_plural': 'historical orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(help_text="The account's address, or the guest's.", max_length=254)),
                ('shipping_address', models.JSONField(help_text='A copy of the address as it was when ordering.')),
                ('subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('subtotal', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='books')),
                ('discount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('discount', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='discount')),
                ('shipping_fee_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('shipping_fee', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='shipping')),
                ('total_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('total', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='total')),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('payment_method', models.CharField(choices=[('razorpay', 'online (UPI, card, net banking)'), ('cod', 'cash on delivery')], default='razorpay', max_length=10)),
                ('status', django_fsm.FSMField(choices=[('pending', 'awaiting payment'), ('paid', 'paid'), ('packed', 'packed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('refunded', 'refunded')], db_index=True, default='pending', max_length=50, protected=True)),
                ('placed_at', models.DateTimeField(blank=True, db_index=True, help_text='Paid online, or placed with cash on delivery.', null=True)),
                ('stock_reserved', models.BooleanField(default=False, editable=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('method', models.CharField(choices=[('razorpay', 'online (UPI, card, net banking)'), ('cod', 'cash on delivery')], max_length=10)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='amount')),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=128)),
                ('status', django_fsm.FSMField(choices=[('created', 'created'), ('authorized', 'authorized'), ('captured', 'captured'), ('failed', 'failed'), ('refunded', 'refunded')], default='created', max_length=50, protected=True)),
                ('error', models.CharField(blank=True, help_text='Why the last attempt failed (from Razorpay).', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.order')),
            ],
            options={
                'verbose_name': 'historical payment',
                'verbose_name_plural': 'historical payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('method', models.CharField(choices=[('razorpay', 'online (UPI, card, net banking)'), ('cod', 'cash on delivery')], max_length=10)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='amount')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=128)),
                ('status', django_fsm.FSMField(choices=[('created', 'created'), ('authorized', 'authorized'), ('captured', 'captured'), ('failed', 'failed'), ('refunded', 'refunded')], default='created', max_length=50, protected=True)),
                ('error', models.CharField(blank=True, help_text='Why the last attempt failed (from Razorpay).', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='last webhook')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shop.order')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('sample-papers', 'Sample Papers'), ('solutions', 'Solutions'), ('bundle', 'Bundle')], max_length=20)),
                ('isbn', models.CharField(blank=True, max_length=17, verbose_name='ISBN')),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Markdown.')),
                ('cover', models.ImageField(blank=True, upload_to='products/')),
                ('mrp_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('mrp', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='MRP')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='selling price')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, help_text='Printed books are exempt: 0.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(28)], verbose_name='GST rate (%)')),
                ('hsn_code', models.CharField(default='4901', max_length=8, verbose_name='HSN code')),
                ('weight_grams', models.PositiveIntegerField(default=0, verbose_name='weight (g)')),
                ('stock', models.PositiveIntegerField(default=0, help_text="Copies in hand. A bundle sells its books' copies.")),
                ('is_active', models.BooleanField(default=True, verbose_name='on sale')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='page title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='meta description')),
                ('book', models.ForeignKey(blank=True, help_text="The papers it holds: “what's inside” and the sample paper link on the product page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='content.book')),
                ('subject', models.ForeignKey(blank=True, help_text='Gives the board and the class.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='content.subject')),
            ],
            options={
                'ordering': ['subject', 'kind', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(max_length=8, verbose_name='HSN')),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='GST %')),
                ('mrp_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('mrp', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='MRP')),
                ('unit_price_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('unit_price', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='price')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shop.product')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='amount')),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'requested'), ('processed', 'processed'), ('failed', 'failed')], default='pending', max_length=10)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The staff member; empty when the customer cancelled or the site refunded by itself.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='shop.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='shop.payment')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('courier', models.CharField(max_length=80)),
                ('tracking_number', models.CharField(max_length=80)),
                ('tracking_url', models.URLField(blank=True)),
                ('shipped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shop.order')),
            ],
            options={
                'ordering': ['-shipped_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('financial_year', models.CharField(max_length=7)),
                ('serial', models.PositiveIntegerField()),
                ('pdf', models.FileField(blank=True, upload_to='invoices/')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='shop.order')),
            ],
            options={
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('financial_year', 'serial'), name='unique_invoice_serial')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.product')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('cart', 'product'), name='unique_cart_product')],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='shop.product')),
                ('product', models.ForeignKey(limit_choices_to=models.Q(('kind', 'bundle'), _negated=True), on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shop.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bundle', 'product'), name='unique_bundle_item')],
            },
        ),
    ]
