# Generated by Django 6.1.2 on 2026-10-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='financial_year',
            field=models.CharField(help_text='T before it: the test series.', max_length=8),
        ),
    ]
