# Generated by Django 6.1.2 on 2026-10-07 22:57

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from importlib import import_module

from django.db import migrations, models

# the role groups get the credit notes' permissions (accounts/roles.py), as in 0002_roles
shop_roles = import_module("shop.migrations.0002_roles").shop_roles


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_invoice_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('digest', models.CharField(max_length=64, unique=True, verbose_name='SHA-256 of the body')),
                ('name', models.CharField(max_length=40)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('financial_year', models.CharField(help_text='T before it: the test series.', max_length=8)),
                ('serial', models.PositiveIntegerField()),
                ('pdf', models.FileField(blank=True, upload_to='credit-notes/')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='shop.invoice')),
                ('refund', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='shop.refund')),
            ],
            options={
                'ordering': ['created'],
                'constraints': [models.UniqueConstraint(fields=('financial_year', 'serial'), name='unique_credit_note_serial')],
            },
        ),
        migrations.RunPython(shop_roles, migrations.RunPython.noop),
    ]
