# Generated by Django 6.1.2 on 2026-10-08 01:32
# Orders and payments made before this release count as test mode (the shop had not gone live). If it had taken live
# payments already, mark those live by hand (RUNBOOK.md, "Test mode and live mode").

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_payment_payload_allowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='livemode',
            field=models.BooleanField(default=False, editable=False, help_text="Made with live Razorpay keys (its payment's mode).", verbose_name='live mode'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='livemode',
            field=models.BooleanField(default=False, editable=False, help_text='Made with live Razorpay keys (the key of its order).', verbose_name='live mode'),
        ),
        migrations.AddField(
            model_name='order',
            name='livemode',
            field=models.BooleanField(default=False, editable=False, help_text="Made with live Razorpay keys (its payment's mode).", verbose_name='live mode'),
        ),
        migrations.AddField(
            model_name='payment',
            name='livemode',
            field=models.BooleanField(default=False, editable=False, help_text='Made with live Razorpay keys (the key of its order).', verbose_name='live mode'),
        ),
    ]
