# Generated by Django 6.1.2 on 2026-10-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'permissions': [('export_order', 'Can export orders')]},
        ),
    ]
