# Generated by Django 6.1.2 on 2026-10-08 03:44

import pictures.migrations
import pictures.models
import pictures.validators
import shop.models
from django.db import migrations, models


def record_sizes(apps, schema_editor):
    """Each picture's width and height, which django-pictures reads from the new fields (without them every page would
    open the files). A picture whose file is gone is dropped: loading it would fail every page that shows it."""
    from PIL import Image

    storage = shop.models.public_storage()
    for model, field, width, height in [
        ("Product", "cover", "cover_width", "cover_height"),
        ("ProductImage", "image", "width", "height"),
    ]:
        rows = apps.get_model("shop", model).objects.exclude(**{field: ""})
        for pk, name in list(rows.values_list("pk", field)):
            try:
                with storage.open(name) as file, Image.open(file) as image:
                    size = image.size
            except OSError:  # missing, or not a picture
                if model == "Product":
                    rows.filter(pk=pk).update(cover="")
                else:
                    rows.filter(pk=pk).delete()
            else:
                rows.filter(pk=pk).update(**{width: size[0], height: size[1]})


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_export_order_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.RunPython(record_sizes, migrations.RunPython.noop),
        pictures.migrations.AlterPictureField(  # queues the AVIF/WebP sizes of the existing pictures
            model_name='product',
            name='cover',
            field=pictures.models.PictureField(aspect_ratios=['2/3'], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 576}, container_width=1200, file_types=['AVIF', 'WEBP'], grid_columns=12, height_field='cover_height', pixel_densities=[1, 2], storage=shop.models.public_storage, upload_to='products/', validators=[pictures.validators.MaxSizeValidator(4096, 4096)], width_field='cover_width'),
        ),
        pictures.migrations.AlterPictureField(
            model_name='productimage',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 576}, container_width=1200, file_types=['AVIF', 'WEBP'], grid_columns=12, height_field='height', pixel_densities=[1, 2], storage=shop.models.public_storage, upload_to='products/', validators=[pictures.validators.MaxSizeValidator(4096, 4096)], width_field='width'),
        ),
    ]
