# Generated by Django 6.1.2 on 2026-10-08 03:50

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.FileField(blank=True, editable=False, storage=shop.models.public_storage, upload_to='og/'),
        ),
    ]
