# Generated by Django 6.1.2 on 2026-10-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_og_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('pin', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='PIN code')),
                ('states', models.JSONField(help_text='Two-letter state codes.')),
                ('districts', models.JSONField()),
            ],
            options={
                'verbose_name': 'PIN code',
            },
        ),
    ]
