# Generated by Django 6.1.2 on 2026-10-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_pin_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='courier',
            field=models.CharField(choices=[('India Post', 'India Post'), ('Delhivery', 'Delhivery'), ('Blue Dart', 'Blue Dart'), ('Ekart', 'Ekart'), ('DTDC', 'DTDC'), ('Xpressbees', 'Xpressbees'), ('Other', 'another courier')], default='India Post', max_length=80),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(blank=True, help_text="Empty: the courier's tracking page, or 17TRACK's."),
        ),
    ]
