# Generated by Django 6.1.2 on 2026-10-08 04:08

import django.core.validators
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('school', models.CharField(max_length=200, verbose_name='school or organisation')),
                ('contact_name', models.CharField(max_length=120, verbose_name='contact person')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', validators=[shop.models.validate_indian_mobile], verbose_name='mobile number')),
                ('gstin', models.CharField(blank=True, max_length=15, validators=[shop.models.validate_gstin], verbose_name='GSTIN')),
                ('items', models.JSONField(help_text='The books asked for: [{product (slug), title, quantity}].')),
                ('delivery_pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9]\\d{5}$', 'Enter the 6-digit PIN code.')], verbose_name='delivery PIN code')),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('new', 'new'), ('quoted', 'quotation made'), ('ordered', 'ordered'), ('closed', 'closed')], db_index=True, default='new', max_length=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='On the books, in the next quotation.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='discount (%)')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='shipping (₹)')),
                ('quotation', models.FileField(blank=True, editable=False, upload_to='quotations/')),
                ('quoted_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
