# Generated by Django 6.1.2 on 2026-10-08 04:40

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_stock_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, help_text='Markdown, at the top of its page.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'permissions': [('export_category', 'Can export categories'), ('import_category', 'Can import categories')],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, help_text='Markdown, at the top of its page.')),
                ('is_active', models.BooleanField(default=True, verbose_name='shown')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Collections are listed by this number.')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['subject', 'kind', 'title'], 'permissions': [('export_product', 'Can export products'), ('import_product', 'Can import products')]},
        ),
        migrations.AddField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(blank=True, help_text='Shown on its page (and it on theirs).', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('sample-papers', 'Sample Papers'), ('solutions', 'Solutions'), ('bundle', 'Bundle'), ('digital', 'Digital (in the app)')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.category'),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.SlugField(help_text="The API's filter: ?attr_<code>=… (e.g. language).", max_length=40)),
                ('kind', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('choice', 'one of a list'), ('boolean', 'yes or no')], default='text', max_length=10)),
                ('choices', models.TextField(blank=True, help_text='For “one of a list”: one choice per line.')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shop.producttype')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, help_text='Gives the product its attributes (edition year, language…), shown on its page.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.producttype'),
        ),
        migrations.CreateModel(
            name='SlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'slug history',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='shop.product')),
            ],
            options={
                'ordering': ['attribute__position', 'attribute__pk'],
                'constraints': [models.UniqueConstraint(fields=('product', 'attribute'), name='one_value_per_attribute')],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='shop.product')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('collection', 'product'), name='unique_collection_product')],
            },
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(fields=('product_type', 'code'), name='unique_attribute_code'),
        ),
    ]
