# Generated by Django 6.1.2 on 2026-10-08 04:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, null=True, verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text="Customers see it on the saving's line: “Board 2027 offer”.", max_length=80)),
                ('kind', models.CharField(choices=[('percent', 'per cent off'), ('fixed', 'rupees off')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('scope', models.CharField(choices=[('cart', 'the whole cart'), ('products', 'the products chosen below'), ('categories', 'the products of the categories below (with their sub-categories)'), ('collections', 'the products of the collections below')], default='cart', max_length=12, verbose_name='on')),
                ('min_quantity', models.PositiveSmallIntegerField(default=0, help_text='Of the products covered.', verbose_name='minimum copies')),
                ('min_value_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('min_value', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', help_text='Of the products covered, after the coupon.', max_digits=10, verbose_name='minimum value')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Orders, all customers together. Empty: no limit.', null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, help_text='Per account and per email address. Empty: no limit.', null=True)),
                ('combinable', models.BooleanField(default=True, help_text='Off: it applies alone, never with a coupon.', verbose_name='with coupons and other offers')),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='offers', to='shop.category')),
                ('collections', models.ManyToManyField(blank=True, related_name='offers', to='shop.collection')),
                ('products', models.ManyToManyField(blank=True, related_name='offers', to='shop.product')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='amount')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='shop.offer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_lines', to='shop.order')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
