# Generated by Django 6.1.2 on 2026-10-08 04:58

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_offers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='payment_link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='razorpay_payment_link_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='reference',
            field=models.CharField(blank=True, help_text='A payment recorded by staff (offline).', max_length=60, verbose_name='bank or UPI reference'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_link_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='A payment recorded by staff (offline).', max_length=60, verbose_name='bank or UPI reference'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'online (UPI, card, net banking)'), ('cod', 'cash on delivery'), ('offline', 'bank transfer or UPI to our account')], default='razorpay', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='method',
            field=models.CharField(choices=[('razorpay', 'online (UPI, card, net banking)'), ('cod', 'cash on delivery'), ('offline', 'bank transfer or UPI to our account')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'online (UPI, card, net banking)'), ('cod', 'cash on delivery'), ('offline', 'bank transfer or UPI to our account')], default='razorpay', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('razorpay', 'online (UPI, card, net banking)'), ('cod', 'cash on delivery'), ('offline', 'bank transfer or UPI to our account')], max_length=10),
        ),
        migrations.CreateModel(
            name='HistoricalOrderNote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(max_length=2000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.order')),
            ],
            options={
                'verbose_name': 'historical order note',
                'verbose_name_plural': 'historical order notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(max_length=2000)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='shop.order')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
