# Generated by Django 6.1.2 on 2026-10-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_store_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='token_expires',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
