# Generated by Django 6.1.2 on 2026-10-09 16:43, the data steps (the master's seed, the backfills) by hand

from datetime import date
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import localflavor.in_.models
from django.conf import settings
from django.db import migrations, models

GST_BEGAN, CHANGED = date(2017, 7, 1), date(2025, 9, 22)
BEFORE = (
    "The rate before 22 September 2025, as the GST Council's 56th meeting (3 September 2025) lists it; when it began "
    "is not recorded here (GST began on 1 July 2017)."
)
SINCE = "The rate in force when the master begins (22 September 2025); unchanged that day."
# The HSN and SAC master as research-commerce-gst.md section 5.1 gives it (its sources, numbered as there, in
# sources-commerce-gst.md): code, kind, description, unit, [(rate, taxability, from, notification, serial, note)].
SEED = [
    ("4901", "hsn", "Printed books, including Braille books", "NOS", [
        ("0", "exempt", CHANGED, "10/2025-Central Tax (Rate)", "132", "The sample papers and solutions [2]."),
    ]),
    ("4903", "hsn", "Children's picture, drawing or colouring books", "NOS", [
        ("0", "exempt", CHANGED, "10/2025-Central Tax (Rate)", "134", "[2]"),
    ]),
    ("4905", "hsn", "Maps and charts of all kinds, including atlases, wall maps and globes, printed", "NOS", [
        ("12", "taxable", GST_BEGAN, "1/2017-Central Tax (Rate), as amended", "", BEFORE),
        ("0", "exempt", CHANGED, "10/2025-Central Tax (Rate)", "136", "[1][2]"),
    ]),
    ("4820", "hsn", "Exercise books, graph books, laboratory notebooks and notebooks", "NOS", [
        ("12", "taxable", GST_BEGAN, "1/2017-Central Tax (Rate), as amended", "", BEFORE),
        ("0", "exempt", CHANGED, "10/2025-Central Tax (Rate)", "130", "[1][2]"),
    ]),
    ("4802", "hsn", "Uncoated paper for printing and writing, other than for exercise books", "KGS", [
        ("12", "taxable", GST_BEGAN, "1/2017-Central Tax (Rate), as amended", "", BEFORE),
        ("18", "taxable", CHANGED, "9/2025-Central Tax (Rate)", "", "A purchase [1]; the serial number to confirm."),
    ]),
    ("4810", "hsn", "Coated paper and paperboard (covers)", "KGS", [
        ("12", "taxable", GST_BEGAN, "1/2017-Central Tax (Rate), as amended", "", BEFORE),
        ("18", "taxable", CHANGED, "9/2025-Central Tax (Rate)", "", "A purchase [1]; the serial number to confirm."),
    ]),
    ("998431", "sac", "E-books: electronic versions of printed books, supplied online", "NA", [
        ("5", "taxable", CHANGED, "11/2017-Central Tax (Rate), as amended by 13/2018-Central Tax (Rate)", "",
         SINCE + " Not changed by 15/2025 [3][26]; the CA confirms the SAC code."),
    ]),
    ("999293", "sac", "Commercial training and coaching services: the revision course", "NA", [
        ("18", "taxable", CHANGED, "11/2017-Central Tax (Rate), as amended", "",
         SINCE + " ExamLeaf is not an educational institution [27]."),
    ]),
    ("9988", "sac", "Job-work printing of books on the publisher's own paper", "NA", [
        ("12", "taxable", GST_BEGAN, "11/2017-Central Tax (Rate), as amended", "", BEFORE),
        ("5", "taxable", CHANGED, "15/2025-Central Tax (Rate)", "", "A purchase [1][3]."),
    ]),
    ("9968", "sac", "Courier and local delivery services", "NA", [
        ("18", "taxable", CHANGED, "11/2017-Central Tax (Rate), as amended", "", SINCE + " A purchase [1]."),
    ]),
    ("9971", "sac", "Payment gateway fees (financial services)", "NA", [
        ("18", "taxable", CHANGED, "11/2017-Central Tax (Rate), as amended", "", SINCE + " On the fee only [79]."),
    ]),
]  # fmt: skip


def seed_master(apps, schema_editor):
    """The master's codes and rates (left as they are when present), then each product whose code is on the master
    points to it."""
    HsnCode, HsnRate, Product = (apps.get_model("shop", name) for name in ("HsnCode", "HsnRate", "Product"))
    for code, kind, description, uqc, rates in SEED:
        hsn, _ = HsnCode.objects.get_or_create(code=code, defaults={"kind": kind, "description": description, "uqc": uqc})
        for rate, taxability, effective_from, notification, serial, note in rates:
            HsnRate.objects.get_or_create(
                hsn=hsn,
                effective_from=effective_from,
                defaults={"rate": Decimal(rate), "taxability": taxability, "notification": notification,
                          "serial": serial, "note": note},  # fmt: skip
            )
    codes = [row[0] for row in SEED]
    for product in Product.objects.filter(hsn__isnull=True, hsn_code__in=codes).only("pk", "hsn_code"):
        Product.objects.filter(pk=product.pk).update(hsn_id=product.hsn_code)


def backfill(apps, schema_editor):
    """What the documents and orders made before this kept implicitly: each order's place of supply (its parcel's
    state, else Assam), each document's series (its number's prefix), and its type as it was issued (a tax invoice
    whenever a line was taxed: the rule then; a credit note its invoice's)."""
    Order, Invoice, CreditNote, OrderItem = (
        apps.get_model("shop", name) for name in ("Order", "Invoice", "CreditNote", "OrderItem")
    )
    batch = []
    for order in Order.objects.filter(billing_state="").only("pk", "shipping_address").iterator(chunk_size=500):
        state = (order.shipping_address or {}).get("state") or "AS"
        order.billing_state = state[:2]
        batch.append(order)
        if len(batch) == 500:
            Order.objects.bulk_update(batch, ["billing_state"])
            batch = []
    Order.objects.bulk_update(batch, ["billing_state"])
    taxed = set(OrderItem.objects.filter(gst_rate__gt=0).values_list("order_id", flat=True))
    for invoice in Invoice.objects.filter(series="").only("pk", "number", "order_id"):
        kind = "tax_invoice" if invoice.order_id in taxed else "bill_of_supply"
        Invoice.objects.filter(pk=invoice.pk).update(series=invoice.number.split("/")[0], document_type=kind)
    kinds = dict(Invoice.objects.values_list("pk", "document_type"))
    for note in CreditNote.objects.filter(series="").only("pk", "number", "invoice_id"):
        CreditNote.objects.filter(pk=note.pk).update(
            series=note.number.split("/")[0], document_type=kinds.get(note.invoice_id, "")
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_cart_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=2)),
                ('financial_year', models.CharField(help_text='2026-27', max_length=7)),
                ('document_type', models.CharField(choices=[('invoice', 'invoices of every kind'), ('tax_invoice', 'tax invoices'), ('bill_of_supply', 'bills of supply'), ('invoice_cum_bill_of_supply', 'invoices-cum-bills of supply'), ('credit_note', 'credit notes'), ('debit_note', 'debit notes'), ('receipt_voucher', 'receipt vouchers'), ('refund_voucher', 'refund vouchers')], max_length=26)),
                ('live', models.BooleanField(default=True, help_text="Off: a test series (Razorpay's test keys).")),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'document series',
                'ordering': ['-financial_year', 'prefix'],
            },
        ),
        migrations.CreateModel(
            name='HsnCode',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{4}(\\d{2}){0,2}$', 'An HSN or SAC code has 4, 6 or 8 digits.')])),
                ('kind', models.CharField(choices=[('hsn', 'HSN (goods)'), ('sac', 'SAC (services)')], max_length=3)),
                ('description', models.CharField(max_length=200)),
                ('uqc', models.CharField(default='NOS', help_text="GSTR-1's unit in the HSN summary: NOS for books, NA for services (the CA confirms).", max_length=3, validators=[django.core.validators.RegexValidator('^([A-Z]{3}|NA)$', 'A unit quantity code: three capitals (NOS, KGS), or NA.')], verbose_name='unit (UQC)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'HSN or SAC code',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HsnRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='GST rate (%)')),
                ('taxability', models.CharField(choices=[('taxable', 'taxable'), ('nil', 'nil-rated'), ('exempt', 'exempt'), ('non_gst', 'non-GST')], max_length=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Empty: until the next row starts.', null=True)),
                ('notification', models.CharField(help_text='e.g. 10/2025-Central Tax (Rate)', max_length=100)),
                ('serial', models.CharField(blank=True, max_length=20, verbose_name='serial number')),
                ('note', models.CharField(blank=True, help_text='Where it was read; what the CA should confirm.', max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['hsn', 'effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TaxThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('line', models.CharField(choices=[('gstr9', '₹2 crore: the annual return (GSTR-9) is due'), ('warning', '₹4 crore: e-invoicing and monthly returns come at ₹5 crore'), ('e_invoice', '₹5 crore: e-invoicing, QRMP ends, 6-digit HSN codes'), ('irp_30_days', '₹10 crore: e-invoices reported to the IRP within 30 days'), ('b2c_large', 'invoices above ₹1 lakh to another state (GSTR-1 table 5)'), ('eway_bill', 'taxable goods above ₹50,000 in one parcel: an e-way bill')], max_length=12)),
                ('financial_year', models.CharField(max_length=7)),
                ('value', models.DecimalField(decimal_places=2, help_text='Rupees, or documents for the counts.', max_digits=14)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('crossed', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict, help_text="The documents' numbers, for the counts.")),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date', 'line'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='creditnote',
            name='unique_credit_note_serial',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_serial',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='document_type',
            field=models.CharField(blank=True, choices=[('tax_invoice', 'Tax invoice'), ('bill_of_supply', 'Bill of supply'), ('invoice_cum_bill_of_supply', 'Invoice-cum-bill of supply')], help_text="Its invoice's: the document it reduces.", max_length=26),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='exempt_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='series',
            field=models.CharField(blank=True, help_text='Its prefix: CN, or TC in the test series.', max_length=2),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='GST'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='taxable_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='billing_state',
            field=localflavor.in_.models.INStateField(blank=True, help_text="The place of supply: the delivery address's state for goods; for courses alone the state the buyer gave, else the address's, else Assam (shop/tax.py).", max_length=2, verbose_name='billing state'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(blank=True, choices=[('tax_invoice', 'Tax invoice'), ('bill_of_supply', 'Bill of supply'), ('invoice_cum_bill_of_supply', 'Invoice-cum-bill of supply')], max_length=26),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exempt_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Its exempt, nil-rated and non-GST lines.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='series',
            field=models.CharField(blank=True, help_text='Its prefix: EL or T; from FY 2027-28 one a type.', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='GST'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxable_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_state',
            field=localflavor.in_.models.INStateField(blank=True, help_text="The place of supply: the delivery address's state for goods; for courses alone the state the buyer gave, else the address's, else Assam (shop/tax.py).", max_length=2, verbose_name='billing state'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='parts',
            field=models.JSONField(blank=True, help_text='A bundle invoiced split: its components as they were sold (shop/tax.py `split_bundle`), each a line of the invoice.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_note',
            field=models.TextField(blank=True, help_text='As written, with whose it is.', verbose_name="the CA's decision"),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_note_date',
            field=models.DateField(blank=True, null=True, verbose_name="date of the CA's decision"),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_treatment',
            field=models.CharField(choices=[('split', 'split: each component a line of its own, the price shared by their MRPs'), ('composite', "composite: one line at the principal supply's rate"), ('mixed', 'mixed: one line at the highest rate')], default='split', help_text="A bundle's GST, as the CA decides: split (recommended), composite or mixed.", max_length=10),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(fields=('series', 'financial_year', 'serial'), name='unique_credit_note_series_serial'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('series', 'financial_year', 'serial'), name='unique_invoice_series_serial'),
        ),
        migrations.AddConstraint(
            model_name='documentseries',
            constraint=models.UniqueConstraint(fields=('prefix', 'financial_year'), name='one_series_per_prefix_and_year'),
        ),
        migrations.AddConstraint(
            model_name='hsncode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code__startswith', '99'), ('kind', 'sac')), models.Q(('kind', 'hsn'), models.Q(('code__startswith', '99'), _negated=True)), _connector='OR'), name='sac_codes_are_chapter_99'),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn',
            field=models.ForeignKey(blank=True, help_text='From the master: the GST rate is its rate on the day (shop/tax.py); hsn_code and gst_rate follow it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.hsncode', verbose_name='HSN or SAC code'),
        ),
        migrations.AddField(
            model_name='hsnrate',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hsnrate',
            name='hsn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='shop.hsncode'),
        ),
        migrations.AddConstraint(
            model_name='taxthreshold',
            constraint=models.UniqueConstraint(fields=('date', 'line'), name='one_threshold_line_a_day'),
        ),
        migrations.AddConstraint(
            model_name='hsnrate',
            constraint=models.UniqueConstraint(fields=('hsn', 'effective_from'), name='one_rate_per_code_and_day'),
        ),
        migrations.AddConstraint(
            model_name='hsnrate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rate__gt', 0), ('taxability', 'taxable')), models.Q(models.Q(('taxability', 'taxable'), _negated=True), ('rate', 0)), _connector='OR'), name='a_rate_matches_its_taxability'),
        ),
        migrations.AddConstraint(
            model_name='hsnrate',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='a_rate_ends_after_it_starts'),
        ),
        migrations.RunPython(seed_master, migrations.RunPython.noop),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
