# Generated by Django 6.1.2 on 2026-10-09 16:22

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import djmoney.models.fields
import djmoney.money
import model_utils.fields
import simple_history.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_cart_token'),
        ('staff', '0007_phase_b_orders'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='held_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='on hold since'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='held_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='hold_reason',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='risk_bucket',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], editable=False, max_length=6, verbose_name='COD risk'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='risk_reasons',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='The strongest three.'),
        ),
        migrations.AddField(
            model_name='order',
            name='held_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='on hold since'),
        ),
        migrations.AddField(
            model_name='order',
            name='held_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='hold_reason',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_bucket',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], editable=False, max_length=6, verbose_name='COD risk'),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_reasons',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='The strongest three.'),
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Words staff give it: school, awaiting reprint.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='order',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote', to='shop.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='arn',
            field=models.CharField(blank=True, help_text="The bank's reference, from Razorpay.", max_length=40, verbose_name='ARN'),
        ),
        migrations.AddField(
            model_name='refund',
            name='change_request',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.changerequest'),
        ),
        migrations.AddField(
            model_name='refund',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='refund',
            name='lines',
            field=models.JSONField(blank=True, default=list, help_text='[{item, quantity, amount}]: the books refunded; empty: an amount.'),
        ),
        migrations.AddField(
            model_name='refund',
            name='method',
            field=models.CharField(choices=[('source', 'to the way it was paid (Razorpay)'), ('bank', 'by bank transfer or UPI to the account the customer gave'), ('none', 'nothing was paid: the credit note only')], default='source', max_length=6),
        ),
        migrations.AddField(
            model_name='refund',
            name='paid_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='payee',
            field=models.TextField(blank=True, editable=False, help_text="The customer's bank account or UPI ID, encrypted."),
        ),
        migrations.AddField(
            model_name='refund',
            name='payee_masked',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='refund',
            name='restock',
            field=models.BooleanField(default=False, help_text='The copies refunded went back into stock.'),
        ),
        migrations.AddField(
            model_name='refund',
            name='shipping_amount',
            field=djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='shipping refunded'),
        ),
        migrations.AddField(
            model_name='refund',
            name='shipping_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='refund',
            name='speed',
            field=models.CharField(choices=[('normal', 'normal (5 to 7 working days)'), ('optimum', 'optimum (instant where the bank allows, else normal)')], default='normal', max_length=8),
        ),
        migrations.AddField(
            model_name='refund',
            name='utr',
            field=models.CharField(blank=True, help_text='Of a transfer by bank or UPI.', max_length=60, verbose_name='UTR or UPI reference'),
        ),
        migrations.CreateModel(
            name='HistoricalReturnRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lines', models.JSONField(help_text="[{item, quantity}]: the order's lines and the copies sent back.")),
                ('reason', models.CharField(choices=[('damaged', 'damaged in transit'), ('misprint', 'misprinted or pages missing'), ('wrong_item', 'not the book ordered'), ('late', 'delivered late'), ('not_as_described', 'not as described'), ('other', 'another reason')], max_length=20)),
                ('by_customer', models.BooleanField(default=False, help_text='Asked for on the website, not by staff.')),
                ('status', django_fsm.FSMField(choices=[('requested', 'requested'), ('approved', 'approved: send it back'), ('declined', 'declined'), ('label_sent', 'return label sent'), ('received', 'received'), ('restocked', 'inspected: back in stock'), ('damaged', 'inspected: damaged'), ('refunded', 'refunded')], db_index=True, default='requested', max_length=50, protected=True)),
                ('decision_note', models.CharField(blank=True, help_text='Told to the customer: why it was declined.', max_length=300)),
                ('return_courier', models.CharField(blank=True, max_length=80)),
                ('return_awb', models.CharField(blank=True, max_length=80, verbose_name='return AWB')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Their names in the private storage.')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.order')),
                ('refund', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.refund')),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical return request',
                'verbose_name_plural': 'historical return requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('email', models.BooleanField(default=True)),
                ('sms', models.CharField(blank=True, choices=[('', 'no SMS'), ('sent', 'sent'), ('held', 'held for the morning'), ('dropped', 'not sent: no longer true in the morning')], db_index=True, max_length=8)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.order')),
            ],
            options={
                'ordering': ['created', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lines', models.JSONField(help_text="[{item, quantity}]: the order's lines and the copies sent back.")),
                ('reason', models.CharField(choices=[('damaged', 'damaged in transit'), ('misprint', 'misprinted or pages missing'), ('wrong_item', 'not the book ordered'), ('late', 'delivered late'), ('not_as_described', 'not as described'), ('other', 'another reason')], max_length=20)),
                ('note', models.TextField(blank=True, max_length=1000, verbose_name="the customer's words")),
                ('by_customer', models.BooleanField(default=False, help_text='Asked for on the website, not by staff.')),
                ('status', django_fsm.FSMField(choices=[('requested', 'requested'), ('approved', 'approved: send it back'), ('declined', 'declined'), ('label_sent', 'return label sent'), ('received', 'received'), ('restocked', 'inspected: back in stock'), ('damaged', 'inspected: damaged'), ('refunded', 'refunded')], db_index=True, default='requested', max_length=50, protected=True)),
                ('decision_note', models.CharField(blank=True, help_text='Told to the customer: why it was declined.', max_length=300)),
                ('return_courier', models.CharField(blank=True, max_length=80)),
                ('return_awb', models.CharField(blank=True, max_length=80, verbose_name='return AWB')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Their names in the private storage.')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='shop.order')),
                ('refund', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_request', to='shop.refund')),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
    ]
