# Generated by Django 6.1.2 on 2026-10-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_phase_b_orders'),
        ('shop', '0021_phase_b_tax'),
    ]

    operations = [
    ]
