# Generated by Django 6.1.2 on 2026-10-09 20:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money
import model_utils.fields
import pictures.validators
import simple_history.models
from django.conf import settings
from django.db import migrations, models
from django.db.models.fields.files import FieldFile

HISTORY = {"history_id", "history_date", "history_change_reason", "history_type", "history_user_id"}
SCOPES = {"Offer": ["products", "categories", "collections"]}  # the m2m fields whose history is kept (models.py)


def physical_and_history(apps, schema_editor):
    """Phase B: catalogue. The products with something to post (books and solutions; a bundle holding one) are packed in
    a flyer, the courier's standard size, until staff say otherwise; their weight stays as it is (0 for most: the
    panel's `incomplete` list shows them). Then one version of each product, coupon, offer and shipping rate as it is
    now (simple-history's populate_history), so that its next change has one to be compared with and the prior price
    its starting price; an offer's version holds what it covers."""
    Product, BundleItem = apps.get_model("shop", "Product"), apps.get_model("shop", "BundleItem")
    goods = ["sample-papers", "solutions"]
    bundles = BundleItem.objects.filter(product__kind__in=goods).values_list("bundle_id", flat=True)
    Product.objects.filter(models.Q(kind__in=goods) | models.Q(pk__in=bundles, kind="bundle")).update(packaging="flyer")
    now = django.utils.timezone.now()
    for name in ("Product", "Coupon", "Offer", "ShippingRate"):
        model, historical = apps.get_model("shop", name), apps.get_model("shop", f"Historical{name}")
        names = [field.attname for field in historical._meta.concrete_fields if field.attname not in HISTORY]
        rows = []
        for obj in model.objects.order_by("pk"):
            values = {attname: getattr(obj, attname) for attname in names}
            values = {key: value.name if isinstance(value, FieldFile) else value for key, value in values.items()}
            rows.append(historical(**values, history_date=now, history_type="+", history_change_reason="When its history began"))
        historical.objects.bulk_create(rows, batch_size=500)
        for field in SCOPES.get(name, []):
            m2m = apps.get_model("shop", f"Historical{name}_{field}")
            through, owner = getattr(model, field).through, name.lower()
            target = m2m._meta.get_field(field.rstrip("s") if field != "categories" else "category").attname
            versions = dict(historical.objects.values_list("id", "history_id"))
            links = through.objects.values_list("id", f"{owner}_id", target)  # the version keeps the row's id
            m2m.objects.bulk_create(
                [m2m(id=pk, history_id=versions[obj], **{f"{owner}_id": obj, target: other}) for pk, obj, other in links],
                batch_size=500,
            )


def nothing_to_undo(apps, schema_editor):
    """Going back drops the tables and fields this migration made, the versions with them."""


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_phase_b_content'),
        ('shop', '0022_merge_0021_phase_b_orders_0021_phase_b_tax'),
        ('staff', '0018_phase_b_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, help_text='What it is for, in words a customer may read (shop/copy_rules.py).', max_length=200),
        ),
        migrations.AddField(
            model_name='coupon',
            name='exclude_categories',
            field=models.ManyToManyField(blank=True, related_name='+', to='shop.category', verbose_name='not these categories (with their sub-categories)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='exclude_products',
            field=models.ManyToManyField(blank=True, related_name='+', to='shop.product', verbose_name='not these products'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='first_order_only',
            field=models.BooleanField(default=False, help_text='For an account or email address with no order placed before.', verbose_name='first order only'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='include_categories',
            field=models.ManyToManyField(blank=True, related_name='+', to='shop.category', verbose_name='only these categories (with their sub-categories)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='include_products',
            field=models.ManyToManyField(blank=True, related_name='+', to='shop.product', verbose_name='only these products'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='note',
            field=models.CharField(blank=True, help_text='For staff: who it is for.', max_length=200, verbose_name='internal note'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='single_use',
            field=models.BooleanField(default=False, help_text="Used only through its single-use codes (a school's batch); its own code is refused at the cart.", verbose_name='single-use codes only'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='stackable',
            field=models.BooleanField(default=True, help_text='Off: no automatic offer applies beside it.', verbose_name='with automatic offers'),
        ),
        migrations.AddField(
            model_name='offer',
            name='banner',
            field=models.CharField(blank=True, help_text='The line the site may show for it, checked as its name is.', max_length=160),
        ),
        migrations.AddField(
            model_name='offer',
            name='show_countdown',
            field=models.BooleanField(default=False, help_text='Only with a real end date, which never moves later once a countdown has shown.', verbose_name='a countdown to its end'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='height (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='length (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, choices=[('flyer', "a flyer (the courier's bag, of the standard size)"), ('box', 'a box (its length, width and height)')], help_text='A flyer has the standard size (SHIPPING_PARCEL_CM); a box needs its dimensions. Empty: not said.', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='width (cm)'),
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Capitals and figures, its batch's prefix first.", max_length=30, unique=True)),
                ('note', models.CharField(blank=True, help_text="Its batch's: the school's name.", max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='shop.coupon')),
                ('job', models.ForeignKey(blank=True, help_text='Its batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.job')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.order')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.couponcode'),
        ),
        migrations.CreateModel(
            name='HistoricalCoupon',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(db_index=True, help_text='Stored in capitals; customers may type any case.', max_length=30)),
                ('kind', models.CharField(choices=[('percent', 'per cent off'), ('fixed', 'rupees off')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('min_order', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', help_text='Value of the books, before shipping.', max_digits=10, verbose_name='minimum order')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='All customers together. Empty: no limit.', null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, default=1, help_text='Per account and per email address. Empty: no limit.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, help_text='What it is for, in words a customer may read (shop/copy_rules.py).', max_length=200)),
                ('note', models.CharField(blank=True, help_text='For staff: who it is for.', max_length=200, verbose_name='internal note')),
                ('first_order_only', models.BooleanField(default=False, help_text='For an account or email address with no order placed before.', verbose_name='first order only')),
                ('stackable', models.BooleanField(default=True, help_text='Off: no automatic offer applies beside it.', verbose_name='with automatic offers')),
                ('single_use', models.BooleanField(default=False, help_text="Used only through its single-use codes (a school's batch); its own code is refused at the cart.", verbose_name='single-use codes only')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical coupon',
                'verbose_name_plural': 'historical coupons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCoupon_exclude_categories',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.category')),
                ('coupon', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.coupon')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.historicalcoupon')),
            ],
            options={
                'verbose_name': 'HistoricalCoupon_exclude_categories',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCoupon_exclude_products',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.coupon')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.historicalcoupon')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.product')),
            ],
            options={
                'verbose_name': 'HistoricalCoupon_exclude_products',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCoupon_include_categories',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.category')),
                ('coupon', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.coupon')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.historicalcoupon')),
            ],
            options={
                'verbose_name': 'HistoricalCoupon_include_categories',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCoupon_include_products',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.coupon')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.historicalcoupon')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.product')),
            ],
            options={
                'verbose_name': 'HistoricalCoupon_include_products',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOffer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text="Customers see it on the saving's line: “Board 2027 offer”.", max_length=80)),
                ('kind', models.CharField(choices=[('percent', 'per cent off'), ('fixed', 'rupees off')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('scope', models.CharField(choices=[('cart', 'the whole cart'), ('products', 'the products chosen below'), ('categories', 'the products of the categories below (with their sub-categories)'), ('collections', 'the products of the collections below')], default='cart', max_length=12, verbose_name='on')),
                ('min_quantity', models.PositiveSmallIntegerField(default=0, help_text='Of the products covered.', verbose_name='minimum copies')),
                ('min_value_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('min_value', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', help_text='Of the products covered, after the coupon.', max_digits=10, verbose_name='minimum value')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Orders, all customers together. Empty: no limit.', null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, help_text='Per account and per email address. Empty: no limit.', null=True)),
                ('combinable', models.BooleanField(default=True, help_text='Off: it applies alone, never with a coupon.', verbose_name='with coupons and other offers')),
                ('is_active', models.BooleanField(default=True)),
                ('show_countdown', models.BooleanField(default=False, help_text='Only with a real end date, which never moves later once a countdown has shown.', verbose_name='a countdown to its end')),
                ('banner', models.CharField(blank=True, help_text='The line the site may show for it, checked as its name is.', max_length=160)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical offer',
                'verbose_name_plural': 'historical offers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOffer_categories',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.category')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.historicaloffer')),
                ('offer', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.offer')),
            ],
            options={
                'verbose_name': 'HistoricalOffer_categories',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOffer_collections',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.collection')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.historicaloffer')),
                ('offer', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.offer')),
            ],
            options={
                'verbose_name': 'HistoricalOffer_collections',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOffer_products',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.historicaloffer')),
                ('offer', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.offer')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.product')),
            ],
            options={
                'verbose_name': 'HistoricalOffer_products',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('kind', models.CharField(choices=[('sample-papers', 'Sample Papers'), ('solutions', 'Solutions'), ('bundle', 'Bundle'), ('digital', 'Digital (in the app)')], max_length=20)),
                ('isbn', models.CharField(blank=True, max_length=17, verbose_name='ISBN')),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Markdown.')),
                ('cover', models.TextField(blank=True, max_length=100, validators=[pictures.validators.MaxSizeValidator(4096, 4096)])),
                ('mrp_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('mrp', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='MRP')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='selling price')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, help_text='Printed books are exempt: 0.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(28)], verbose_name='GST rate (%)')),
                ('hsn_code', models.CharField(default='4901', max_length=8, verbose_name='HSN code')),
                ('weight_grams', models.PositiveIntegerField(default=0, verbose_name='weight (g)')),
                ('stock', models.PositiveIntegerField(default=0, help_text="Copies in hand. A bundle sells its books' copies.")),
                ('is_active', models.BooleanField(default=True, verbose_name='on sale')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='page title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='meta description')),
                ('tax_treatment', models.CharField(choices=[('split', 'split: each component a line of its own, the price shared by their MRPs'), ('composite', "composite: one line at the principal supply's rate"), ('mixed', 'mixed: one line at the highest rate')], default='split', help_text="A bundle's GST, as the CA decides: split (recommended), composite or mixed.", max_length=10)),
                ('tax_note', models.TextField(blank=True, help_text='As written, with whose it is.', verbose_name="the CA's decision")),
                ('tax_note_date', models.DateField(blank=True, null=True, verbose_name="date of the CA's decision")),
                ('length_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='length (cm)')),
                ('width_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='width (cm)')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='height (cm)')),
                ('packaging', models.CharField(blank=True, choices=[('flyer', "a flyer (the courier's bag, of the standard size)"), ('box', 'a box (its length, width and height)')], help_text='A flyer has the standard size (SHIPPING_PARCEL_CM); a box needs its dimensions. Empty: not said.', max_length=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('book', models.ForeignKey(blank=True, db_constraint=False, help_text="The papers it holds: “what's inside” and the sample paper link on the product page.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.book')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hsn', models.ForeignKey(blank=True, db_constraint=False, help_text='From the master: the GST rate is its rate on the day (shop/tax.py); hsn_code and gst_rate follow it.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.hsncode', verbose_name='HSN or SAC code')),
                ('product_type', models.ForeignKey(blank=True, db_constraint=False, help_text='Gives the product its attributes (edition year, language…), shown on its page.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shop.producttype')),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, help_text='Gives the board and the class.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.subject')),
            ],
            options={
                'verbose_name': 'historical product',
                'verbose_name_plural': 'historical products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShippingRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('states', models.JSONField(blank=True, default=list, help_text='None ticked: every state no other rate names.')),
                ('fee_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('fee', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='fee')),
                ('free_above_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3, null=True)),
                ('free_above', djmoney.models.fields.MoneyField(blank=True, currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', help_text='Books worth this much or more ship free.', max_digits=10, null=True, verbose_name='free from')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shipping rate',
                'verbose_name_plural': 'historical shipping rates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='couponcode',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order',), name='one_code_an_order'),
        ),
        migrations.RunPython(physical_and_history, nothing_to_undo),
    ]
