# Generated by Django 6.1.2 on 2026-10-09 20:11

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
        ('shop', '0022_merge_0021_phase_b_orders_0021_phase_b_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='payment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='shop.payment'),
        ),
        migrations.CreateModel(
            name='InvoicePaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('invoice', models.CharField(db_index=True, max_length=140, verbose_name='ERPNext invoice')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default_currency='INR', max_digits=10, verbose_name='amount')),
                ('razorpay_payment_link_id', models.CharField(max_length=40, unique=True)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'made, waiting for the payment'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('expired', 'expired unpaid')], db_index=True, default='sent', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('livemode', models.BooleanField(default=False, editable=False, verbose_name='live mode')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('erp_name', models.CharField(blank=True, max_length=140, verbose_name="ERPNext's payment entry")),
                ('cancelled_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('settlement_id', models.CharField(max_length=40, unique=True, verbose_name="Razorpay's id")),
                ('date', models.DateField(db_index=True, help_text='The day Razorpay settled it (India).')),
                ('utr', models.CharField(blank=True, help_text="The bank's reference of the transfer.", max_length=60, verbose_name='UTR')),
                ('gross_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('gross', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='gross')),
                ('fees_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('fees', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', help_text='Without their GST.', max_digits=10, verbose_name="Razorpay's fees")),
                ('tax_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('tax', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='GST on the fees')),
                ('adjustments_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('adjustments', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='adjustments')),
                ('net_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('net', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', help_text='What reached the bank.', max_digits=10, verbose_name='net')),
                ('state', models.CharField(choices=[('fetched', 'fetched'), ('matched', 'matched'), ('posted', 'posted to ERPNext'), ('mismatched', 'mismatched')], db_index=True, default='fetched', max_length=10)),
                ('problem', models.CharField(blank=True, help_text='Why it is mismatched: counts, never a name.', max_length=300)),
                ('livemode', models.BooleanField(default=False, editable=False, verbose_name='live mode')),
                ('matched_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('erp_outbox', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erp.erpoutbox')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payment', 'payment'), ('refund', 'refund'), ('adjustment', 'adjustment')], max_length=10)),
                ('entity_id', models.CharField(db_index=True, max_length=40, verbose_name="Razorpay's id")),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='amount')),
                ('fee_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('fee', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', help_text='Without its GST.', max_digits=10, verbose_name="Razorpay's fee")),
                ('tax_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('tax', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='GST on the fee')),
                ('credit_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('credit', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='credited')),
                ('debit_currency', djmoney.models.fields.CurrencyField(choices=[('INR', '₹')], default='INR', editable=False, max_length=3)),
                ('debit', djmoney.models.fields.MoneyField(currency_choices=[('INR', '₹')], decimal_places=2, default=djmoney.money.Money(0, 'INR'), default_currency='INR', max_digits=10, verbose_name='debited')),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('order_receipt', models.CharField(blank=True, help_text='Our number.', max_length=40, verbose_name="Razorpay order's receipt")),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='Why it was matched by hand.', max_length=300)),
                ('raw', models.JSONField(blank=True, default=dict, help_text="Razorpay's fields, the allowed ones (no card or bank).")),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='shop.invoicepaymentlink')),
                ('matched_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='shop.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='shop.payment')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='shop.refund')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shop.settlement')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoicepaymentlink',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'sent')), fields=('invoice',), name='one_open_link_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='settlementline',
            constraint=models.UniqueConstraint(fields=('settlement', 'entity_id'), name='one_settlement_line_per_entity'),
        ),
    ]
