# Generated by Django 6.1.2 on 2026-10-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_phase_b_catalogue'),
        ('shop', '0023_phase_b_finance'),
    ]

    operations = [
    ]
