# Generated by Django 6.1.2 on 2026-10-07 20:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("privacy", "privacy"),
                            ("terms", "terms"),
                            ("refunds", "refunds"),
                            ("shipping", "shipping"),
                            ("contact", "contact"),
                        ],
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body_md", models.TextField(verbose_name="text (Markdown)")),
                (
                    "version",
                    models.CharField(
                        help_text="Change it (e.g. to today's date) when the meaning changes. Consent records keep the privacy policy's version, and the History button shows the text of every version.",
                        max_length=20,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPage",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("privacy", "privacy"),
                            ("terms", "terms"),
                            ("refunds", "refunds"),
                            ("shipping", "shipping"),
                            ("contact", "contact"),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body_md", models.TextField(verbose_name="text (Markdown)")),
                (
                    "version",
                    models.CharField(
                        help_text="Change it (e.g. to today's date) when the meaning changes. Consent records keep the privacy policy's version, and the History button shows the text of every version.",
                        max_length=20,
                    ),
                ),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical page",
                "verbose_name_plural": "historical pages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
