# Generated by Django 6.1.2 on 2026-10-09 16:50

import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone
from django.utils.dateparse import parse_date


def effective_dates(apps, schema_editor):
    """Each version so far in force from its label's date (they are dates: "2026-10-08"), else from the day it was
    saved: on the page and on every history row of that version."""
    Page, HistoricalPage = apps.get_model("pages", "Page"), apps.get_model("pages", "HistoricalPage")
    for page in Page.objects.all():
        run_version, run_day = None, None
        for row in HistoricalPage.objects.filter(id=page.id).order_by("history_date", "history_id"):
            if row.version != run_version:
                try:
                    run_day = parse_date(row.version) or timezone.localdate(row.history_date)
                except ValueError:
                    run_day = timezone.localdate(row.history_date)
                run_version = row.version
            HistoricalPage.objects.filter(history_id=row.history_id).update(effective_from=run_day)
        try:
            day = parse_date(page.version) or timezone.localdate(page.updated)
        except ValueError:
            day = timezone.localdate(page.updated)
        Page.objects.filter(pk=page.pk).update(effective_from=run_day if run_version == page.version else day)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_shop_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpage',
            name='effective_from',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, help_text='The day this version came into force (a new version: today, unless set).'),
        ),
        migrations.AddField(
            model_name='historicalpage',
            name='summary',
            field=models.CharField(blank=True, help_text='What this version changed, in a line.', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='effective_from',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, help_text='The day this version came into force (a new version: today, unless set).'),
        ),
        migrations.AddField(
            model_name='page',
            name='scheduled',
            field=models.JSONField(blank=True, editable=False, help_text='A version published for a later day, until that day.', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='summary',
            field=models.CharField(blank=True, help_text='What this version changed, in a line.', max_length=200),
        ),
        migrations.RunPython(effective_dates, migrations.RunPython.noop),
    ]
