# Generated by Django 6.1.2 on 2026-10-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consentrecord',
            options={'ordering': ['-created'], 'permissions': [('export_consentrecord', 'Can export consent records')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('export_user', 'Can export users')]},
        ),
    ]
