# Generated by Django 6.1.2 on 2026-10-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_export_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='method',
            field=models.CharField(choices=[('declared', 'ticked on the form'), ('email_link', 'confirmed through the link emailed to the parent')], default='declared', max_length=10, verbose_name='how'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the parent confirmed.', null=True, verbose_name='verified at'),
        ),
    ]
