# Generated by Django 6.1.2 on 2026-10-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_consent_method'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='mobile number for log-in'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_phone_verified',
            field=models.BooleanField(default=False, verbose_name='mobile number confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_updates',
            field=models.BooleanField(default=False, verbose_name='order updates by SMS'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='method',
            field=models.CharField(choices=[('declared', 'ticked on the form'), ('email_link', 'confirmed through the link emailed to the parent'), ('sms_link', 'confirmed through the link texted to the parent')], default='declared', max_length=10, verbose_name='how'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('login_phone_verified', True)), fields=('login_phone',), name='uniq_verified_login_phone'),
        ),
    ]
