# Generated by Django 6.1.2 on 2026-10-09 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_login_phone'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='channel',
            field=models.CharField(blank=True, choices=[('email', 'email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], help_text="A marketing consent's channel; empty: every one.", max_length=10),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='evidence_ref',
            field=models.CharField(blank=True, help_text="Where the evidence is (a ticket's number, a letter's date): never the document itself.", max_length=200, verbose_name='evidence reference'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='The member of staff who recorded it by hand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='ledger_copied_at',
            field=models.DateTimeField(blank=True, help_text="When the ledger's line was copied to the backups' bucket.", null=True),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='parent_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='A student under 18: when the parent or guardian confirmed the erasure.', null=True),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='parent_confirmed_by',
            field=models.ForeignKey(blank=True, help_text="The member of staff who recorded the confirmation by hand; empty: the parent's own link.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='parent_evidence_ref',
            field=models.CharField(blank=True, help_text="How staff had it (a ticket's number, a letter's date), not the document.", max_length=200),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='registration_until',
            field=models.DateTimeField(blank=True, help_text='The intermediary rule: the registration details stay until then.', null=True),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='subject_hash',
            field=models.CharField(blank=True, db_index=True, help_text='The ledger: a keyed hash of the email address erased.', max_length=64),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='method',
            field=models.CharField(choices=[('declared', 'ticked on the form'), ('email_link', 'confirmed through the link emailed to the parent'), ('sms_link', 'confirmed through the link texted to the parent'), ('adult_account', "confirmed by the parent's own verified adult account"), ('digilocker', 'confirmed with a DigiLocker token'), ('staff_manual', 'recorded by staff, with evidence')], default='declared', max_length=20, verbose_name='how'),
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(help_text='An email address or an Indian mobile number.', max_length=120)),
                ('relation', models.CharField(help_text='Mother, brother, friend …', max_length=60)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When a claim proved the nomination.', null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nominee', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(choices=[('dispute', 'a dispute'), ('chargeback', 'a chargeback'), ('claim', 'a legal claim'), ('investigation', 'an investigation'), ('other', 'another reason (in the note)')], max_length=15)),
                ('note', models.TextField(blank=True, help_text='The case: its reference and what it is about, briefly.')),
                ('until', models.DateField(blank=True, help_text='The last day it holds; empty: until released.', null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-pk'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='accounts_hold_target')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('target_type__isnull', True)), models.Q(('user__isnull', True), ('target_type__isnull', False), models.Q(('target_id', ''), _negated=True)), _connector='OR'), name='legal_hold_one_target')],
            },
        ),
    ]
