# Generated by Django 6.1.2 on 2026-10-09 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phase_b_legal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLinkSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'email'), ('sms', 'SMS')], max_length=5)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_by', models.ForeignKey(blank=True, help_text='The member of staff who sent it again; empty: the site or the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at', '-pk'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['user', '-sent_at'], name='accounts_parentlink_user')],
            },
        ),
    ]
