# Generated by Django 6.1.2 on 2026-10-09 04:26

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('shop', '0020_cart_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='expected (₹)')),
                ('expected_on', models.DateField()),
                ('remitted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='remitted (₹)')),
                ('utr', models.CharField(blank=True, max_length=60, verbose_name='UTR')),
                ('remitted_at', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('expected', 'expected'), ('overdue', 'overdue'), ('remitted', 'remitted'), ('mismatch', 'remitted, another amount'), ('not_expected', 'not expected')], db_index=True, default='expected', max_length=15)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cod_remittance', to='shop.shipment')),
            ],
            options={
                'ordering': ['expected_on'],
            },
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nickname', models.CharField(max_length=36, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=40, verbose_name="carrier's id")),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('pin_code', models.CharField(max_length=6, verbose_name='PIN code')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_default', 'nickname'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_default_pickup')],
            },
        ),
        migrations.CreateModel(
            name='PinServiceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(db_index=True, max_length=6, verbose_name='PIN code')),
                ('courier_company_id', models.PositiveIntegerField()),
                ('courier_name', models.CharField(blank=True, max_length=80)),
                ('cod', models.BooleanField(default=False)),
                ('prepaid', models.BooleanField(default=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rate (₹)')),
                ('etd_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='days to deliver')),
                ('surveyed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'PIN serviceability',
                'ordering': ['pin', 'rate'],
                'constraints': [models.UniqueConstraint(fields=('pin', 'courier_company_id'), name='one_answer_per_pin')],
            },
        ),
        migrations.CreateModel(
            name='PostalTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('book_post', 'Book Post (open, untracked)'), ('gyan_post', 'Gyan Post (tracked, surface)'), ('speed_post', 'Speed Post')], max_length=12)),
                ('weight_to_g', models.PositiveIntegerField(verbose_name='up to (g)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price (₹)')),
                ('effective_from', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['service', '-effective_from', 'weight_to_g'],
                'constraints': [models.UniqueConstraint(fields=('service', 'weight_to_g', 'effective_from'), name='one_price_per_slab')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('freight', 'freight'), ('freight_reversal', 'freight reversed'), ('cod', 'COD charge'), ('cod_reversal', 'COD charge reversed'), ('rto_freight', 'RTO freight'), ('rto_freight_reversal', 'RTO freight reversed'), ('excess_weight', 'excess weight'), ('excess_weight_reversal', 'excess weight reversed'), ('other', 'other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive: charged to us; negative: given back.', max_digits=10, verbose_name='amount (₹)')),
                ('statement_line_id', models.CharField(max_length=64, unique=True)),
                ('charged_weight_g', models.PositiveIntegerField(blank=True, null=True)),
                ('awb', models.CharField(blank=True, max_length=40, verbose_name='AWB')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('charged_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='integrations.integrationaccount')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='shop.shipment')),
            ],
            options={
                'ordering': ['-charged_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('webhook', 'webhook'), ('poll', 'tracking read'), ('manual', 'staff')], max_length=10)),
                ('carrier_code', models.CharField(blank=True, help_text="Shiprocket's status code, e.g. 18.", max_length=40)),
                ('carrier_label', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('booked', 'booked'), ('pickup_problem', 'pickup problem'), ('in_transit', 'in transit'), ('out_for_delivery', 'out for delivery'), ('delivered', 'delivered'), ('delivery_failed', 'delivery failed'), ('returning', 'returning to us'), ('returned', 'returned to us'), ('lost_or_damaged', 'lost or damaged'), ('cancelled', 'cancelled'), ('partial', 'partly delivered')], max_length=20, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('activity', models.CharField(blank=True, max_length=300)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shop.shipment')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('carrier', models.CharField(choices=[('manual', 'by hand (staff type the courier and number)'), ('shiprocket', 'Shiprocket')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('booked', 'booked'), ('pickup_problem', 'pickup problem'), ('in_transit', 'in transit'), ('out_for_delivery', 'out for delivery'), ('delivered', 'delivered'), ('delivery_failed', 'delivery failed'), ('returning', 'returning to us'), ('returned', 'returned to us'), ('lost_or_damaged', 'lost or damaged'), ('cancelled', 'cancelled'), ('partial', 'partly delivered')], db_index=True, max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='our order id at the carrier')),
                ('external_order_id', models.CharField(blank=True, max_length=40, verbose_name="carrier's order id")),
                ('external_shipment_id', models.CharField(blank=True, max_length=40, verbose_name="carrier's shipment id")),
                ('courier_company_id', models.PositiveIntegerField(blank=True, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=80)),
                ('label', models.FileField(blank=True, upload_to='shipping/labels/')),
                ('parcel_photo', models.FileField(blank=True, help_text='The parcel on the scale, label side up: the evidence.', upload_to='shipping/photos/')),
                ('weight_g', models.PositiveIntegerField(blank=True, help_text='As weighed at packing.', null=True, verbose_name='weight (g)')),
                ('length_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('breadth_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('charged_weight_g', models.PositiveIntegerField(blank=True, null=True, verbose_name='charged weight (g)')),
                ('quoted_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quoted rate (₹)')),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Empty: prepaid.', max_digits=10, null=True, verbose_name='cash to collect (₹)')),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='declared value (₹)')),
                ('last_event_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('manifested_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sms_held', models.CharField(blank=True, editable=False, help_text='An SMS kept for the morning (none from 21:00 to 08:00).', max_length=30)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='integrations.integrationaccount')),
                ('pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='shipping.pickuplocation')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='shop.shipment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('carrier', 'reference'), name='one_parcel_per_reference')],
            },
        ),
        migrations.CreateModel(
            name='ShippingException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('kind', models.CharField(choices=[('pickup_problem', 'pickup problem'), ('ndr', 'delivery failed (NDR)'), ('rto', 'returning or returned (RTO)'), ('lost', 'lost or damaged'), ('partial', 'partly delivered'), ('weight_dispute', 'weight dispute'), ('cod_overdue', 'COD overdue or mismatched'), ('no_movement', 'no movement')], max_length=20)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('state', models.CharField(choices=[('open', 'open'), ('resolved', 'resolved'), ('dismissed', 'dismissed')], db_index=True, default='open', max_length=10)),
                ('reference', models.CharField(blank=True, help_text="The carrier's id of it, if it has one.", max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('resolution', models.CharField(blank=True, max_length=300)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='shop.shipment')),
            ],
            options={
                'ordering': ['due_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('kind', 'reference'), name='one_exception_per_reference')],
            },
        ),
    ]
